3D Forest: ClassificationList Class Reference
ClassificationList Class Reference
#include <ClassificationList.hpp>
Public Member Functions
ClassificationList ()
void clear ()
bool isEnabled () const
void setEnabled (bool b)
size_t size () const
bool isEnabled (size_t i) const
void setEnabled (size_t i, bool b)
std::unordered_set< size_t > enabledList () const
const std::string & label (size_t i) const
void setEnabledAll (bool b)
void setInvertAll ()
void read (const Json &in)
Json & write (Json &out) const
Protected Attributes
std::vector< Classification > classes_
bool enabled_
Constructor & Destructor Documentation
ClassificationList()
ClassificationList::ClassificationList ()
Member Function Documentation
clear()
void ClassificationList::clear ()
Referenced by ClassificationList(), Editor::close(), and read().
enabledList()
std::unordered_set< size_t > ClassificationList::enabledList () const inline
Referenced by Editor::setClassifications().
isEnabled() [1/2]
bool ClassificationList::isEnabled () const inline
Referenced by Editor::setClassifications().
isEnabled() [2/2]
bool ClassificationList::isEnabled (size_t i) const inline
label()
const std::string & ClassificationList::label (size_t i) const inline
read()
void ClassificationList::read (const Json & in)
Referenced by Editor::openProject().
setEnabled() [1/2]
void ClassificationList::setEnabled (bool b)
setEnabled() [2/2]
void ClassificationList::setEnabled (size_t i, bool b) inline
setEnabledAll()
void ClassificationList::setEnabledAll (bool b)
setInvertAll()
void ClassificationList::setInvertAll ()
size()
size_t ClassificationList::size () const inline
write()
Json & ClassificationList::write (Json & out) const
Referenced by Editor::save().
Member Data Documentation
classes_
std::vector<Classification> ClassificationList::classes_ protected
Referenced by clear(), enabledList(), isEnabled(), label(), read(), setEnabled(), setEnabledAll(), setInvertAll(), size(), and write().
enabled_
bool ClassificationList::enabled_ protected
Referenced by isEnabled(), read(), setEnabled(), and write().
The documentation for this class was generated from the following files:
ClassificationList.hpp
ClassificationList.cpp