3D Forest: ExportFileProperties Class Reference
ExportFileProperties Class Reference
#include <ExportFileProperties.hpp>
Public Member Functions
ExportFileProperties ()
~ExportFileProperties ()
void clear ()
void setFileName (const std::string &fileName)
const std::string & fileName () const
void setNumberOfPoints (uint64_t n)
uint64_t numberOfPoints () const
void setFormat (const LasFile::Format &format)
const LasFile::Format & format () const
void setRegion (const Box< double > &region)
const Box< double > & region () const
void setScale (const Vector3< double > &scale)
void setScale (double scale)
const Vector3< double > & scale () const
void setOffset (const Vector3< double > &offset)
const Vector3< double > & offset () const
void setFilterEnabled (bool b)
bool isFilterEnabled () const
Private Attributes
std::string fileName_
uint64_t numberOfPoints_
LasFile::Format format_
Box< double > region_
Vector3< double > scale_
Vector3< double > offset_
bool filterEnabled_
Constructor & Destructor Documentation
ExportFileProperties()
ExportFileProperties::ExportFileProperties ()
~ExportFileProperties()
ExportFileProperties::~ExportFileProperties ()
Member Function Documentation
clear()
void ExportFileProperties::clear ()
Referenced by ExportFileProperties().
fileName()
const std::string & ExportFileProperties::fileName () const inline
Referenced by setFileName(), ExportFilePlugin::slotExportFile(), and ExportFileAction::step().
format()
const LasFile::Format & ExportFileProperties::format () const inline
Referenced by ExportFileFormatCsv::create(), setFormat(), ExportFileFormatCsv::write(), and ExportFileFormatLas::write().
isFilterEnabled()
bool ExportFileProperties::isFilterEnabled () const inline
Referenced by ExportFileAction::initialize().
numberOfPoints()
uint64_t ExportFileProperties::numberOfPoints () const inline
offset()
const Vector3< double > & ExportFileProperties::offset () const inline
Referenced by setOffset().
region()
const Box< double > & ExportFileProperties::region () const inline
Referenced by setRegion().
scale()
const Vector3< double > & ExportFileProperties::scale () const inline
Referenced by setScale(), and ExportFileFormatCsv::write().
setFileName()
void ExportFileProperties::setFileName (const std::string & fileName) inline
Referenced by ExportFileDialog::properties().
setFilterEnabled()
void ExportFileProperties::setFilterEnabled (bool b) inline
Referenced by ExportFileDialog::properties().
setFormat()
void ExportFileProperties::setFormat (const LasFile::Format & format) inline
Referenced by ExportFileDialog::properties().
setNumberOfPoints()
void ExportFileProperties::setNumberOfPoints (uint64_t n) inline
Referenced by ExportFileAction::determineMaximum().
setOffset()
void ExportFileProperties::setOffset (const Vector3< double > & offset) inline
setRegion()
void ExportFileProperties::setRegion (const Box< double > & region) inline
Referenced by ExportFileAction::determineMaximum().
setScale() [1/2]
void ExportFileProperties::setScale (const Vector3< double > & scale) inline
Referenced by ExportFileDialog::properties().
setScale() [2/2]
void ExportFileProperties::setScale (double scale) inline
Member Data Documentation
fileName_
std::string ExportFileProperties::fileName_ private
Referenced by fileName(), and setFileName().
filterEnabled_
bool ExportFileProperties::filterEnabled_ private
Referenced by clear(), isFilterEnabled(), and setFilterEnabled().
format_
LasFile::Format ExportFileProperties::format_ private
Referenced by clear(), format(), and setFormat().
numberOfPoints_
uint64_t ExportFileProperties::numberOfPoints_ private
Referenced by clear(), numberOfPoints(), and setNumberOfPoints().
offset_
Vector3<double> ExportFileProperties::offset_ private
Referenced by clear(), offset(), and setOffset().
region_
Box<double> ExportFileProperties::region_ private
Referenced by clear(), region(), and setRegion().
scale_
Vector3<double> ExportFileProperties::scale_ private
Referenced by clear(), scale(), and setScale().
The documentation for this class was generated from the following files:
ExportFileProperties.hpp
ExportFileProperties.cpp