3D Forest: Box< T > Class Template Reference
Box< T > Class Template Reference
#include <Box.hpp>
Public Member Functions
Box ()
~Box ()
template<class B >
Box (const Box< B > &box)
template<class B >
Box (B x1, B y1, B z1, B x2, B y2, B z2)
template<class B >
Box (B cx, B cy, B cz, B r)
template<class B >
Box (B min, B max)
template<class B >
Box (const Vector3< B > &min, const Vector3< B > &max)
void set (T x1, T y1, T z1, T x2, T y2, T z2)
void set (T cx, T cy, T cz, T r)
void set (T min, T max)
void set (const Vector3< T > &min, const Vector3< T > &max)
void set (const std::vector< T > &xyz)
void set (const Box< T > &box)
void setPercent (const Box< T > &box, const Box< T > &a, const Box< T > &b)
void translate (const Vector3< T > &v)
void extend (const Box< T > &box)
void extend (T x, T y, T z)
void clear ()
bool empty () const
const T & min (size_t idx) const
const T & max (size_t idx) const
Vector3< T > length () const
T length (size_t idx) const
T maximumLength () const
void center (T &x, T &y, T &z) const
Vector3< T > center () const
T distance (T x, T y, T z) const
T radius () const
bool intersects (const Box< T > &box) const
bool contains (const Box< T > &box) const
bool contains (T x, T y, T z) const
Private Member Functions
void validate ()
Private Attributes
T min_ [3]
T max_ [3]
bool empty_
Constructor & Destructor Documentation
Box() [1/6]
template<class T > Box< T >::Box () inline
~Box()
template<class T > Box< T >::~Box () inline
Box() [2/6]
template<class T > template<class B > Box< T >::Box (const Box< B > & box) inline
Box() [3/6]
template<class T > template<class B > Box< T >::Box (B x1, B y1, B z1, B x2, B y2, B z2) inline
Box() [4/6]
template<class T > template<class B > Box< T >::Box (B cx, B cy, B cz, B r) inline
Box() [5/6]
template<class T > template<class B > Box< T >::Box (B min, B max) inline
Box() [6/6]
template<class T > template<class B > Box< T >::Box (const Vector3< B > & min, const Vector3< B > & max) inline
Member Function Documentation
center() [1/2]
template<class T > Vector3< T > Box< T >::center () const inline
center() [2/2]
template<class T > void Box< T >::center (T & x, T & y, T & z) const inline
Referenced by IndexFile::boundary(), ComputeDescriptorPca::computeDescriptor(), IndexFile::insert(), Dataset::read(), IndexFile::selectLeaf(), IndexFile::selectLeaves(), IndexFile::selectLeaves(), IndexFile::selectNode(), and IndexFile::selectNodes().
clear()
template<class T > void Box< T >::clear () inline
Referenced by Datasets::boundary(), Region::clear(), Datasets::clear(), IndexFile::clear(), Query::clear(), ComputeSegmentationNNAction::Group::clear(), ExportFileProperties::clear(), Query::setGrid(), IndexFileBuilder::start(), and Datasets::updateBoundary().
contains() [1/2]
template<class T > bool Box< T >::contains (const Box< T > & box) const inline
Referenced by Page::queryWhereBox(), IndexFile::selectLeaf(), IndexFile::selectLeaves(), IndexFile::selectLeaves(), IndexFile::selectNode(), and IndexFile::selectNodes().
contains() [2/2]
template<class T > bool Box< T >::contains (T x, T y, T z) const inline
distance()
template<class T > T Box< T >::distance (T x, T y, T z) const inline
Referenced by Query::applyCamera().
empty()
template<class T > bool Box< T >::empty () const inline
Referenced by Box< T >::extend(), and Page::queryWhereBox().
extend() [1/2]
template<class T > void Box< T >::extend (const Box< T > & box) inline
Referenced by Datasets::boundary(), ComputeSegmentationNNAction::continueGroup(), ComputeSegmentationNNAction::mergeToGroup(), ComputeSegmentationNNAction::startGroup(), IndexFileBuilder::stateCopyPoints(), and Datasets::updateBoundary().
extend() [2/2]
template<class T > void Box< T >::extend (T x, T y, T z) inline
intersects()
template<class T > bool Box< T >::intersects (const Box< T > & box) const inline
Referenced by Query::applyCamera(), IndexFile::selectLeaves(), IndexFile::selectLeaves(), and IndexFile::selectNodes().
length() [1/2]
template<class T > Vector3< T > Box< T >::length () const inline
Referenced by ViewerOpenGLViewport::renderAttributes(), Page::runColorModifier(), Query::setGrid(), and Query::setVoxels().
length() [2/2]
template<class T > T Box< T >::length (size_t idx) const inline
max()
template<class T > const T & Box< T >::max (size_t idx) const inline
Referenced by ComputeHeightMapModifier::applyModifier(), Box< T >::Box(), IndexFile::divide(), IndexFile::insert(), Query::nextGrid(), Query::nextVoxel(), ViewerAabb::set(), ViewerAabb::set(), LasFile::Header::set(), FilterAreaBoxWidget::setRegion(), ComputeElevationAction::start(), IndexFileBuilder::stateMainBegin(), ComputeTreeAttributesAction::stepPointsToTrees(), and IndexFile::write().
maximumLength()
template<class T > T Box< T >::maximumLength () const inline
Referenced by ComputeDescriptorPca::computeDescriptor().
min()
template<class T > const T & Box< T >::min (size_t idx) const inline
Referenced by ComputeHeightMapModifier::applyModifier(), Box< T >::Box(), IndexFile::divide(), IndexFile::insert(), Query::nextGrid(), Query::nextVoxel(), Dataset::read(), ViewerAabb::set(), ViewerAabb::set(), LasFile::Header::set(), FilterAreaBoxWidget::setRegion(), ComputeElevationAction::start(), IndexFileBuilder::stateMainBegin(), ComputeTreeAttributesAction::stepPointsToTrees(), and IndexFile::write().
radius()
template<class T > T Box< T >::radius () const inline
Referenced by Query::applyCamera().
set() [1/6]
template<class T > void Box< T >::set (const Box< T > & box) inline
set() [2/6]
template<class T > void Box< T >::set (const std::vector< T > & xyz) inline
set() [3/6]
template<class T > void Box< T >::set (const Vector3< T > & min, const Vector3< T > & max) inline
set() [4/6]
template<class T > void Box< T >::set (T cx, T cy, T cz, T r) inline
set() [5/6]
template<class T > void Box< T >::set (T min, T max) inline
set() [6/6]
template<class T > void Box< T >::set (T x1, T y1, T z1, T x2, T y2, T z2) inline
Referenced by LasFile::create(), IndexFile::divide(), FilterAreaBoxWidget::filterChanged(), IndexFile::insert(), Query::nextGrid(), Query::nextVoxel(), IndexFile::readPayload(), Query::setGrid(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateMainBegin(), IndexFileBuilder::stateNodeInsert(), and PageData::transform().
setPercent()
template<class T > void Box< T >::setPercent (const Box< T > & box, const Box< T > & a, const Box< T > & b) inline
translate()
template<class T > void Box< T >::translate (const Vector3< T > & v) inline
Referenced by IndexFile::translate(), and Dataset::updateBoundary().
validate()
template<class T > void Box< T >::validate () inline private
Member Data Documentation
empty_
template<class T > bool Box< T >::empty_ private
Referenced by Box< T >::empty().
max_
template<class T > T Box< T >::max_[3] private
Referenced by Box< T >::contains(), Box< T >::extend(), Box< T >::intersects(), Box< T >::length(), Box< T >::max(), Box< T >::set(), and Box< T >::setPercent().
min_
template<class T > T Box< T >::min_[3] private
Referenced by Box< T >::contains(), Box< T >::extend(), Box< T >::intersects(), Box< T >::length(), Box< T >::min(), Box< T >::set(), and Box< T >::setPercent().
The documentation for this class was generated from the following file:
Box.hpp