3D Forest: Voxels Class Reference
Voxels Class Reference
#include <Voxels.hpp>
Public Member Functions
Voxels ()
void clear ()
void create (const Box< double > &spaceRegion, double voxelSize)
const Box< double > & spaceRegion () const
const Vector3< double > & voxelSize () const
bool next (Voxel *voxel, Box< double > *cell=nullptr, Query *query=nullptr)
uint64_t visitedVoxelsCount () const
size_t size () const
void addVoxel (const Voxel &voxel)
Voxel & at (size_t index)
const Voxel & at (size_t index) const
Voxel & at (size_t x, size_t y, size_t z)
const Voxel & at (size_t x, size_t y, size_t z) const
void sort (double elevationMinimum, double elevationMaximum)
size_t sortedSize () const
Voxel & sortedAt (size_t index)
const Voxel & sortedAt (size_t index) const
size_t sizeX () const
size_t sizeY () const
size_t sizeZ () const
size_t indexSize () const
bool contains (size_t x, size_t y, size_t z) const
size_t find (size_t x, size_t y, size_t z) const
size_t indexOf (size_t x, size_t y, size_t z) const
size_t indexOf (const Voxel &voxel) const
void box (const Voxel &voxel, Box< double > *box)
float descriptorMin () const
float descriptorMax () const
void normalize (Voxel *voxel)
void dump () const
Static Public Attributes
static const size_t npos = SIZE_MAX
Private Member Functions
void push (size_t x1, size_t y1, size_t z1, size_t x2, size_t y2, size_t z2)
bool next (Query *query, Box< double > *cell=nullptr, size_t *index=nullptr, uint32_t *x=nullptr, uint32_t *y=nullptr, uint32_t *z=nullptr)
Private Attributes
Box< double > spaceRegion_
double voxelSizeInput_
Vector3< double > voxelSize_
size_t nx_
size_t ny_
size_t nz_
std::vector< size_t > index_
std::vector< Voxel > voxels_
std::vector< Voxel * > sortedVoxels_
float descriptorMin_
float descriptorMax_
std::vector< Box< size_t > > stack_
uint64_t visitedVoxelsCount_
Constructor & Destructor Documentation
Voxels()
Voxels::Voxels ()
Member Function Documentation
addVoxel()
void Voxels::addVoxel (const Voxel & voxel)
Referenced by SegmentationThread::computeCreateVoxels().
at() [1/4]
Voxel & Voxels::at (size_t index) inline
Referenced by SegmentationElement::computeBase(), SegmentationThread::computeCreateElements(), SegmentationThread::computeCreateLayers(), SegmentationThread::computeInitializeElements(), and dump().
at() [2/4]
const Voxel & Voxels::at (size_t index) const inline
at() [3/4]
Voxel & Voxels::at (size_t x, size_t y, size_t z) inline
at() [4/4]
const Voxel & Voxels::at (size_t x, size_t y, size_t z) const inline
box()
void Voxels::box (const Voxel & voxel, Box< double > * box)
Referenced by box().
clear()
void Voxels::clear ()
Referenced by SegmentationThread::clear(), Editor::close(), SegmentationThread::computeCreateVoxels(), create(), and Voxels().
contains()
bool Voxels::contains (size_t x, size_t y, size_t z) const inline
create()
void Voxels::create (const Box< double > & spaceRegion, double voxelSize)
Referenced by SegmentationThread::computeCreateVoxels().
descriptorMax()
float Voxels::descriptorMax () const inline
descriptorMin()
float Voxels::descriptorMin () const inline
dump()
void Voxels::dump () const
find()
size_t Voxels::find (size_t x, size_t y, size_t z) const inline
Referenced by SegmentationElement::computeBase(), and SegmentationMap::process().
indexOf() [1/2]
size_t Voxels::indexOf (const Voxel & voxel) const inline
indexOf() [2/2]
size_t Voxels::indexOf (size_t x, size_t y, size_t z) const inline
Referenced by addVoxel().
indexSize()
size_t Voxels::indexSize () const inline
Referenced by SegmentationThread::computeCreateVoxels().
next() [1/2]
bool Voxels::next (Query * query, Box< double > * cell = nullptr, size_t * index = nullptr, uint32_t * x = nullptr, uint32_t * y = nullptr, uint32_t * z = nullptr) private
next() [2/2]
bool Voxels::next (Voxel * voxel, Box< double > * cell = nullptr, Query * query = nullptr)
Referenced by SegmentationThread::computeCreateVoxels(), and next().
normalize()
void Voxels::normalize (Voxel * voxel)
Referenced by normalize().
push()
void Voxels::push (size_t x1, size_t y1, size_t z1, size_t x2, size_t y2, size_t z2) private
Referenced by create(), and next().
size()
size_t Voxels::size () const inline
Referenced by SegmentationThread::computeCreateLayers(), SegmentationThread::computeCreateVoxels(), SegmentationThread::computeInitializeElements(), SegmentationThread::computeMergeElements(), SegmentationThread::computeSortVoxels(), and dump().
sizeX()
size_t Voxels::sizeX () const inline
Referenced by SegmentationMap::create(), and SegmentationElement::pushNext1().
sizeY()
size_t Voxels::sizeY () const inline
Referenced by SegmentationMap::create(), and SegmentationElement::pushNext1().
sizeZ()
size_t Voxels::sizeZ () const inline
Referenced by SegmentationMap::create(), and SegmentationElement::pushNext1().
sort()
void Voxels::sort (double elevationMinimum, double elevationMaximum)
Referenced by SegmentationThread::computeSortVoxels().
sortedAt() [1/2]
Voxel & Voxels::sortedAt (size_t index) inline
Referenced by SegmentationElements::computeBase(), and SegmentationElement::computeStart().
sortedAt() [2/2]
const Voxel & Voxels::sortedAt (size_t index) const inline
sortedSize()
size_t Voxels::sortedSize () const inline
Referenced by SegmentationThread::computeCreateElements().
spaceRegion()
const Box< double > & Voxels::spaceRegion () const inline
Referenced by create().
visitedVoxelsCount()
uint64_t Voxels::visitedVoxelsCount () const inline
Referenced by SegmentationThread::computeCreateVoxels().
voxelSize()
const Vector3< double > & Voxels::voxelSize () const inline
Referenced by create().
Member Data Documentation
descriptorMax_
float Voxels::descriptorMax_ private
Referenced by addVoxel(), clear(), and normalize().
descriptorMin_
float Voxels::descriptorMin_ private
Referenced by addVoxel(), and clear().
index_
std::vector<size_t> Voxels::index_ private
Referenced by addVoxel(), clear(), and create().
npos
const size_t Voxels::npos = SIZE_MAX static
Referenced by SegmentationElement::computeBase(), SegmentationThread::computeCreateLayers(), SegmentationThread::computeInitializeVoxels(), create(), and SegmentationMap::process().
nx_
size_t Voxels::nx_ private
Referenced by clear(), create(), and next().
ny_
size_t Voxels::ny_ private
Referenced by clear(), create(), and next().
nz_
size_t Voxels::nz_ private
Referenced by clear(), and create().
sortedVoxels_
std::vector<Voxel *> Voxels::sortedVoxels_ private
Referenced by clear(), and sort().
spaceRegion_
Box<double> Voxels::spaceRegion_ private
Referenced by box(), clear(), create(), and next().
stack_
std::vector<Box<size_t> > Voxels::stack_ private
Referenced by clear(), next(), and push().
visitedVoxelsCount_
uint64_t Voxels::visitedVoxelsCount_ private
Referenced by clear(), and next().
voxels_
std::vector<Voxel> Voxels::voxels_ private
Referenced by addVoxel(), clear(), and sort().
voxelSize_
Vector3<double> Voxels::voxelSize_ private
Referenced by box(), clear(), create(), and next().
voxelSizeInput_
double Voxels::voxelSizeInput_ private
Referenced by clear(), and create().
The documentation for this class was generated from the following files:
Voxels.hpp
Voxels.cpp