3D Forest: SettingsView Class Reference
SettingsView Class Reference
#include <SettingsView.hpp>
Public Types
enum class ColorSource {
COLOR , INTENSITY , RETURN_NUMBER , NUMBER_OF_RETURNS ,
CLASSIFICATION , SEGMENT , ELEVATION , DESCRIPTOR ,
UNKNOWN
}
Public Member Functions
SettingsView ()
double pointSize () const
void setPointSize (double size)
const Vector3< double > & pointColor () const
void setPointColor (const Vector3< double > &rgb)
const Vector3< double > & backgroundColor () const
void setBackgroundColor (const Vector3< double > &rgb)
SettingsView::ColorSource colorSource () const
void setColorSource (SettingsView::ColorSource colorSource)
size_t colorSourceSize () const
const char * colorSourceString (size_t idx) const
bool distanceBasedFadingVisible () const
void setDistanceBasedFadingVisible (bool b)
bool sceneBoundingBoxVisible () const
void setSceneBoundingBoxVisible (bool b)
bool treeAttributesVisible () const
void setTreeAttributesVisible (bool b)
Protected Attributes
double pointSize_
Vector3< double > pointColor_
Vector3< double > backgroundColor_
SettingsView::ColorSource colorSource_
bool distanceBasedFadingVisible_
bool sceneBoundingBoxVisible_
bool treeAttributesVisible_
std::vector< std::string > colorSourceString_
Friends
void fromJson (SettingsView &out, const Json &in)
void toJson (Json &out, const SettingsView &in)
Member Enumeration Documentation
ColorSource
enum class SettingsView::ColorSource strong
Enumerator
COLOR
INTENSITY
RETURN_NUMBER
NUMBER_OF_RETURNS
CLASSIFICATION
SEGMENT
ELEVATION
DESCRIPTOR
UNKNOWN
Constructor & Destructor Documentation
SettingsView()
SettingsView::SettingsView ()
Member Function Documentation
backgroundColor()
const Vector3< double > & SettingsView::backgroundColor () const inline
Referenced by ViewerOpenGLViewport::renderSceneSettingsEnable(), and SettingsViewWidget::setViewSettings().
colorSource()
SettingsView::ColorSource SettingsView::colorSource () const
Referenced by Page::runColorModifier(), setColorSource(), SettingsViewWidget::SettingsViewWidget(), and SettingsViewWidget::setViewSettings().
colorSourceSize()
size_t SettingsView::colorSourceSize () const
Referenced by SettingsViewWidget::SettingsViewWidget().
colorSourceString()
const char * SettingsView::colorSourceString (size_t idx) const
Referenced by SettingsViewWidget::SettingsViewWidget().
distanceBasedFadingVisible()
bool SettingsView::distanceBasedFadingVisible () const
Referenced by ViewerOpenGLViewport::renderFirstFrame(), ViewerOpenGLViewport::renderSceneSettingsDisable(), ViewerOpenGLViewport::renderSceneSettingsEnable(), SettingsViewWidget::SettingsViewWidget(), and SettingsViewWidget::setViewSettings().
pointColor()
const Vector3< double > & SettingsView::pointColor () const inline
Referenced by SettingsViewWidget::setViewSettings().
pointSize()
double SettingsView::pointSize () const
Referenced by ViewerOpenGLViewport::renderSceneSettingsEnable(), and SettingsViewWidget::setViewSettings().
sceneBoundingBoxVisible()
bool SettingsView::sceneBoundingBoxVisible () const
Referenced by ViewerOpenGLViewport::renderFirstFrame(), SettingsViewWidget::SettingsViewWidget(), and SettingsViewWidget::setViewSettings().
setBackgroundColor()
void SettingsView::setBackgroundColor (const Vector3< double > & rgb)
Referenced by SettingsViewWidget::slotSetColor().
setColorSource()
void SettingsView::setColorSource (SettingsView::ColorSource colorSource)
Referenced by SettingsViewWidget::slotColorSourceChanged().
setDistanceBasedFadingVisible()
void SettingsView::setDistanceBasedFadingVisible (bool b)
Referenced by SettingsViewWidget::slotSetDistanceBasedFadingVisible().
setPointColor()
void SettingsView::setPointColor (const Vector3< double > & rgb)
Referenced by SettingsViewWidget::slotSetColor().
setPointSize()
void SettingsView::setPointSize (double size)
Referenced by SettingsViewWidget::slotSetPointSize().
setSceneBoundingBoxVisible()
void SettingsView::setSceneBoundingBoxVisible (bool b)
Referenced by SettingsViewWidget::slotSetSceneBoundingBoxVisible().
setTreeAttributesVisible()
void SettingsView::setTreeAttributesVisible (bool b)
Referenced by SettingsViewWidget::slotSetTreeAttributesVisible().
treeAttributesVisible()
bool SettingsView::treeAttributesVisible () const
Referenced by ViewerOpenGLViewport::renderAttributes(), SettingsViewWidget::SettingsViewWidget(), and SettingsViewWidget::setViewSettings().
Friends And Related Symbol Documentation
fromJson
void fromJson (SettingsView & out, const Json & in) friend
toJson
void toJson (Json & out, const SettingsView & in) friend
Member Data Documentation
backgroundColor_
Vector3<double> SettingsView::backgroundColor_ protected
Referenced by setBackgroundColor().
colorSource_
SettingsView::ColorSource SettingsView::colorSource_ protected
Referenced by colorSource(), and setColorSource().
colorSourceString_
std::vector<std::string> SettingsView::colorSourceString_ protected
Referenced by colorSourceSize(), colorSourceString(), and SettingsView().
distanceBasedFadingVisible_
bool SettingsView::distanceBasedFadingVisible_ protected
Referenced by distanceBasedFadingVisible(), and setDistanceBasedFadingVisible().
pointColor_
Vector3<double> SettingsView::pointColor_ protected
Referenced by setPointColor().
pointSize_
double SettingsView::pointSize_ protected
Referenced by pointSize(), and setPointSize().
sceneBoundingBoxVisible_
bool SettingsView::sceneBoundingBoxVisible_ protected
Referenced by sceneBoundingBoxVisible(), and setSceneBoundingBoxVisible().
treeAttributesVisible_
bool SettingsView::treeAttributesVisible_ protected
Referenced by setTreeAttributesVisible(), and treeAttributesVisible().
The documentation for this class was generated from the following files:
SettingsView.hpp
SettingsView.cpp