3D Forest: Cone< T > Class Template Reference
Cone< T > Class Template Reference
#include <Cone.hpp>
Public Member Functions
Cone ()
~Cone ()
void set (T x, T y, T z1, T z2, T angle)
void clear ()
bool empty () const
const Box< T > & box () const
bool isInside (T x, T y, T z) const
Protected Member Functions
void validate ()
Protected Attributes
T x_
T y_
T z_
T z2_
T radius_
T angle_
Box< T > box_
Constructor & Destructor Documentation
Cone()
template<class T > Cone< T >::Cone inline
~Cone()
template<class T > Cone< T >::~Cone inline
Member Function Documentation
box()
template<class T > const Box< T > & Cone< T >::box () const inline
Referenced by Query::exec(), and Page::selectCone().
clear()
template<class T > void Cone< T >::clear inline
empty()
template<class T > bool Cone< T >::empty () const inline
Referenced by Query::exec(), Page::select(), and Page::selectCone().
isInside()
template<class T > bool Cone< T >::isInside (T x, T y, T z) const inline
Referenced by Page::selectCone().
set()
template<class T > void Cone< T >::set (T x, T y, T z1, T z2, T angle) inline
Referenced by Query::selectCone().
validate()
template<class T > void Cone< T >::validate inline protected
Member Data Documentation
angle_
template<class T > T Cone< T >::angle_ protected
box_
template<class T > Box<T> Cone< T >::box_ protected
Referenced by Cone< T >::box(), and Cone< T >::empty().
radius_
template<class T > T Cone< T >::radius_ protected
x_
template<class T > T Cone< T >::x_ protected
y_
template<class T > T Cone< T >::y_ protected
z2_
template<class T > T Cone< T >::z2_ protected
z_
template<class T > T Cone< T >::z_ protected
The documentation for this class was generated from the following file:
Cone.hpp