3D Forest: DatasetList Class Reference
DatasetList Class Reference
#include <DatasetList.hpp>
Public Member Functions
DatasetList ()
void clear ()
size_t size () const
const Dataset & at (size_t i) const
const Dataset & key (size_t id) const
void erase (size_t i)
size_t id (size_t i) const
size_t index (size_t id)
size_t unusedId () const
bool isEnabled (size_t i) const
void setEnabled (size_t i, bool b)
void setEnabledAll (bool b)
void setInvertAll ()
const std::string & label (size_t i) const
void setLabel (size_t i, const std::string &label)
const Vector3< float > & color (size_t i) const
void setColor (size_t i, const Vector3< float > &color)
const std::string & fileName (size_t i) const
const std::string & dateCreated (size_t i) const
const Vector3< double > & translation (size_t i) const
void setTranslation (size_t i, const Vector3< double > &translation)
const Vector3< double > & scaling (size_t i) const
const Vector3< double > & scalingFile (size_t i) const
const Box< double > & boundary () const
void updateBoundary ()
uint64_t nPoints () const
void select (std::vector< IndexFile::Selection > &selected, const Box< double > &box) const
void read (const std::string &path, const std::string &projectPath, const SettingsImport &settings, const Box< double > &projectBoundary)
void read (const Json &in, const std::string &projectPath)
Json & write (Json &out) const
Protected Attributes
std::vector< Dataset > datasets_
std::unordered_map< size_t, size_t > hashTable_
Box< double > boundary_
Constructor & Destructor Documentation
DatasetList()
DatasetList::DatasetList ()
Member Function Documentation
at()
const Dataset & DatasetList::at (size_t i) const inline
Referenced by Query::selectCamera().
boundary()
const Box< double > & DatasetList::boundary () const inline
Referenced by Editor::boundary(), Editor::clipBoundary(), Editor::openDataset(), Editor::resetClipFilter(), ViewerOpenGLViewport::resetScene(), Editor::setClipFilter(), and Editor::updateAfterRead().
clear()
void DatasetList::clear ()
Referenced by Editor::close(), and DatasetList().
color()
const Vector3< float > & DatasetList::color (size_t i) const inline
Referenced by ProjectNavigatorFiles::addItem(), and setColor().
dateCreated()
const std::string & DatasetList::dateCreated (size_t i) const inline
Referenced by ProjectNavigatorFiles::addItem().
erase()
void DatasetList::erase (size_t i)
Referenced by ProjectNavigatorFiles::slotDelete().
fileName()
const std::string & DatasetList::fileName (size_t i) const inline
id()
size_t DatasetList::id (size_t i) const inline
Referenced by ProjectNavigatorFiles::addItem(), index(), and read().
index()
size_t DatasetList::index (size_t id) inline
Referenced by ProjectNavigatorFiles::index().
isEnabled()
bool DatasetList::isEnabled (size_t i) const inline
Referenced by ProjectNavigatorFiles::addItem(), and ProjectNavigatorFiles::updateTree().
key()
const Dataset & DatasetList::key (size_t id) const inline
Referenced by Page::read(), Query::selectCamera(), Page::transform(), and Page::write().
label()
const std::string & DatasetList::label (size_t i) const inline
Referenced by ProjectNavigatorFiles::addItem(), and setLabel().
nPoints()
uint64_t DatasetList::nPoints () const
Referenced by Query::setGrid().
read() [1/2]
void DatasetList::read (const Json & in, const std::string & projectPath)
read() [2/2]
void DatasetList::read (const std::string & path, const std::string & projectPath, const SettingsImport & settings, const Box< double > & projectBoundary)
Referenced by Editor::openDataset(), and Editor::openProject().
scaling()
const Vector3< double > & DatasetList::scaling (size_t i) const inline
scalingFile()
const Vector3< double > & DatasetList::scalingFile (size_t i) const inline
select()
void DatasetList::select (std::vector< IndexFile::Selection > & selected, const Box< double > & box) const
Referenced by Query::exec().
setColor()
void DatasetList::setColor (size_t i, const Vector3< float > & color)
setEnabled()
void DatasetList::setEnabled (size_t i, bool b)
Referenced by ProjectNavigatorFiles::slotItemChanged().
setEnabledAll()
void DatasetList::setEnabledAll (bool b)
setInvertAll()
void DatasetList::setInvertAll ()
setLabel()
void DatasetList::setLabel (size_t i, const std::string & label)
setTranslation()
void DatasetList::setTranslation (size_t i, const Vector3< double > & translation)
size()
size_t DatasetList::size () const inline
Referenced by ProjectNavigatorFiles::setDatasets().
translation()
const Vector3< double > & DatasetList::translation (size_t i) const inline
Referenced by setTranslation().
unusedId()
size_t DatasetList::unusedId () const
Referenced by read().
updateBoundary()
void DatasetList::updateBoundary ()
Referenced by read().
write()
Json & DatasetList::write (Json & out) const
Referenced by Editor::save().
Member Data Documentation
boundary_
Box<double> DatasetList::boundary_ protected
Referenced by boundary(), clear(), and updateBoundary().
datasets_
std::vector<Dataset> DatasetList::datasets_ protected
Referenced by at(), clear(), color(), dateCreated(), erase(), fileName(), id(), isEnabled(), key(), label(), nPoints(), read(), scaling(), scalingFile(), select(), setColor(), setEnabled(), setEnabledAll(), setInvertAll(), setLabel(), setTranslation(), size(), translation(), updateBoundary(), and write().
hashTable_
std::unordered_map<size_t, size_t> DatasetList::hashTable_ protected
Referenced by clear(), erase(), index(), key(), read(), and unusedId().
The documentation for this class was generated from the following files:
DatasetList.hpp
DatasetList.cpp