3D Forest: SettingsViewWidget Class Reference
SettingsViewWidget Class Reference
#include <SettingsViewWidget.hpp>
Inherits QWidget.
Public Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_OPACITY ,
COLUMN_LAST
}
Public Slots
void slotUpdate ()
void slotSetPointSize (int v)
void slotSetFogEnabled (int v)
void slotSetColorFg ()
void slotSetColorBg ()
void slotClearSelection ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
SettingsViewWidget (MainWindow *mainWindow)
Protected Member Functions
void settingsChanged ()
void settingsChangedApply ()
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addItem (size_t i)
void setColorSource (const SettingsView &settings)
void setSettings (const SettingsView &settings)
bool colorDialog (Vector3< float > &rgb)
void setColor (QPushButton *button, const Vector3< float > &rgb)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QPushButton * deselectButton_
QSlider * pointSizeSlider_
QCheckBox * fogCheckBox_
QPushButton * colorFgButton_
QPushButton * colorBgButton_
SettingsView settings_
Member Enumeration Documentation
Column
enum SettingsViewWidget::Column
Settings View Widget Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_OPACITY
COLUMN_LAST
Constructor & Destructor Documentation
SettingsViewWidget()
SettingsViewWidget::SettingsViewWidget (MainWindow * mainWindow)
Member Function Documentation
addItem()
void SettingsViewWidget::addItem (size_t i) protected
Referenced by setColorSource().
block()
void SettingsViewWidget::block () protected
Referenced by setSettings(), and updateTree().
colorDialog()
bool SettingsViewWidget::colorDialog (Vector3< float > & rgb) protected
Referenced by slotSetColorBg(), and slotSetColorFg().
index()
size_t SettingsViewWidget::index (const QTreeWidgetItem * item) protected
Referenced by slotItemChanged(), and updateTree().
setColor()
void SettingsViewWidget::setColor (QPushButton * button, const Vector3< float > & rgb) protected
Referenced by setSettings(), slotSetColorBg(), and slotSetColorFg().
setColorSource()
void SettingsViewWidget::setColorSource (const SettingsView & settings) protected
Referenced by setSettings().
setSettings()
void SettingsViewWidget::setSettings (const SettingsView & settings) protected
Referenced by slotUpdate().
settingsChanged()
void SettingsViewWidget::settingsChanged () protected
Referenced by slotSetFogEnabled(), and slotSetPointSize().
settingsChangedApply()
void SettingsViewWidget::settingsChangedApply () protected
Referenced by slotClearSelection(), slotItemChanged(), slotSetColorBg(), and slotSetColorFg().
slotClearSelection
void SettingsViewWidget::slotClearSelection () slot
Referenced by SettingsViewWidget().
slotItemChanged
void SettingsViewWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotSetColorBg
void SettingsViewWidget::slotSetColorBg () slot
Referenced by SettingsViewWidget().
slotSetColorFg
void SettingsViewWidget::slotSetColorFg () slot
Referenced by SettingsViewWidget().
slotSetFogEnabled
void SettingsViewWidget::slotSetFogEnabled (int v) slot
Referenced by SettingsViewWidget().
slotSetPointSize
void SettingsViewWidget::slotSetPointSize (int v) slot
Referenced by SettingsViewWidget().
slotUpdate
void SettingsViewWidget::slotUpdate () slot
Referenced by SettingsViewWidget().
unblock()
void SettingsViewWidget::unblock () protected
Referenced by setSettings(), and updateTree().
updateTree()
void SettingsViewWidget::updateTree () protected
Referenced by slotClearSelection().
Member Data Documentation
colorBgButton_
QPushButton* SettingsViewWidget::colorBgButton_ protected
Referenced by setSettings(), SettingsViewWidget(), and slotSetColorBg().
colorFgButton_
QPushButton* SettingsViewWidget::colorFgButton_ protected
Referenced by setSettings(), SettingsViewWidget(), and slotSetColorFg().
deselectButton_
QPushButton* SettingsViewWidget::deselectButton_ protected
Referenced by SettingsViewWidget().
fogCheckBox_
QCheckBox* SettingsViewWidget::fogCheckBox_ protected
Referenced by SettingsViewWidget(), and slotSetFogEnabled().
mainWindow_
MainWindow* SettingsViewWidget::mainWindow_ protected
Referenced by settingsChanged(), settingsChangedApply(), SettingsViewWidget(), and slotUpdate().
pointSizeSlider_
QSlider* SettingsViewWidget::pointSizeSlider_ protected
Referenced by setSettings(), and SettingsViewWidget().
settings_
SettingsView SettingsViewWidget::settings_ protected
Referenced by addItem(), setSettings(), settingsChanged(), settingsChangedApply(), SettingsViewWidget(), slotClearSelection(), slotItemChanged(), slotSetColorBg(), slotSetColorFg(), slotSetFogEnabled(), slotSetPointSize(), and updateTree().
tree_
QTreeWidget* SettingsViewWidget::tree_ protected
Referenced by addItem(), block(), setColorSource(), SettingsViewWidget(), unblock(), and updateTree().
The documentation for this class was generated from the following files:
SettingsViewWidget.hpp
SettingsViewWidget.cpp