3D Forest: Layer Class Reference
Layer Class Reference
#include <Layer.hpp>
Public Member Functions
Layer ()
void set (size_t id, const std::string &label, const Vector3< double > &color)
size_t id () const
const std::string & label () const
void setLabel (const std::string &label)
const Vector3< double > & color () const
void setColor (const Vector3< double > &color)
const LayerData & data () const
void setData (const LayerData &data)
size_t meshSize () const
const Mesh & mesh (size_t index) const
void addMesh (const Mesh &mesh)
void read (const Json &in)
Json & write (Json &out) const
Protected Attributes
std::string label_
Vector3< double > color_
size_t id_
LayerData data_
std::vector< Mesh > meshList_
Constructor & Destructor Documentation
Layer()
Layer::Layer ()
Member Function Documentation
addMesh()
void Layer::addMesh (const Mesh & mesh) inline
color()
const Vector3< double > & Layer::color () const inline
Referenced by set(), and setColor().
data()
const LayerData & Layer::data () const inline
id()
size_t Layer::id () const inline
Referenced by Layers::push_back(), and set().
label()
const std::string & Layer::label () const inline
Referenced by set(), and setLabel().
mesh()
const Mesh & Layer::mesh (size_t index) const inline
Referenced by ViewerOpenGLViewport::renderLayers().
meshSize()
size_t Layer::meshSize () const inline
Referenced by ViewerOpenGLViewport::renderLayers().
read()
void Layer::read (const Json & in)
set()
void Layer::set (size_t id, const std::string & label, const Vector3< double > & color)
Referenced by SegmentationAction::stepCreateLayers().
setColor()
void Layer::setColor (const Vector3< double > & color)
setData()
void Layer::setData (const LayerData & data) inline
setLabel()
void Layer::setLabel (const std::string & label)
write()
Json & Layer::write (Json & out) const
Member Data Documentation
color_
Vector3<double> Layer::color_ protected
Referenced by read(), set(), setColor(), and write().
data_
LayerData Layer::data_ protected
id_
size_t Layer::id_ protected
Referenced by read(), set(), and write().
label_
std::string Layer::label_ protected
Referenced by read(), set(), setLabel(), and write().
meshList_
std::vector<Mesh> Layer::meshList_ protected
The documentation for this class was generated from the following files:
Layer.hpp
Layer.cpp