3D Forest: FilterElevationWidget Class Reference
FilterElevationWidget Class Reference
#include <FilterElevationWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
FilterElevationWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Member Functions
void setElevation (const Range< double > &elevationRange)
void filterChanged ()
Protected Attributes
MainWindow * mainWindow_
DoubleRangeSliderWidget * elevationInput_
Range< double > elevationRange_
Constructor & Destructor Documentation
FilterElevationWidget()
FilterElevationWidget::FilterElevationWidget (MainWindow * mainWindow)
Member Function Documentation
filterChanged()
void FilterElevationWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
setElevation()
void FilterElevationWidget::setElevation (const Range< double > & elevationRange) protected
Referenced by slotUpdate().
setFilterEnabled()
void FilterElevationWidget::setFilterEnabled (bool b)
Referenced by FilterElevationWindow::closeEvent(), and FilterElevationWindow::showEvent().
sizeHint()
QSize FilterElevationWidget::sizeHint () const inline override
slotRangeIntermediateMaximumValue
void FilterElevationWidget::slotRangeIntermediateMaximumValue () slot
Referenced by FilterElevationWidget().
slotRangeIntermediateMinimumValue
void FilterElevationWidget::slotRangeIntermediateMinimumValue () slot
Referenced by FilterElevationWidget().
slotUpdate
void FilterElevationWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterElevationWidget().
Member Data Documentation
elevationInput_
DoubleRangeSliderWidget* FilterElevationWidget::elevationInput_ protected
Referenced by FilterElevationWidget(), setElevation(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
elevationRange_
Range<double> FilterElevationWidget::elevationRange_ protected
Referenced by filterChanged(), setElevation(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
mainWindow_
MainWindow* FilterElevationWidget::mainWindow_ protected
Referenced by filterChanged(), FilterElevationWidget(), setElevation(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
The documentation for this class was generated from the following files:
FilterElevationWidget.hpp
FilterElevationWidget.cpp