3D Forest: ProjectNavigatorItemDensity Class Reference
ProjectNavigatorItemDensity Class Reference
#include <ProjectNavigatorItemDensity.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
ProjectNavigatorItemDensity (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void densityInputChanged ()
Protected Attributes
RangeSliderWidget * densityInput_
Range< float > densityRange_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ProjectNavigatorItemDensity()
ProjectNavigatorItemDensity::ProjectNavigatorItemDensity (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemDensity::colorSource () const inline virtual
Implements ProjectNavigatorItem.
densityInputChanged()
void ProjectNavigatorItemDensity::densityInputChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ProjectNavigatorItemDensity::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemDensity::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
isFilterEnabled()
bool ProjectNavigatorItemDensity::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setFilterEnabled()
void ProjectNavigatorItemDensity::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotRangeIntermediateMaximumValue
void ProjectNavigatorItemDensity::slotRangeIntermediateMaximumValue () slot
Referenced by ProjectNavigatorItemDensity().
slotRangeIntermediateMinimumValue
void ProjectNavigatorItemDensity::slotRangeIntermediateMinimumValue () slot
Referenced by ProjectNavigatorItemDensity().
slotUpdate
void ProjectNavigatorItemDensity::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemDensity().
Member Data Documentation
densityInput_
RangeSliderWidget* ProjectNavigatorItemDensity::densityInput_ protected
Referenced by ProjectNavigatorItemDensity(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
densityRange_
Range<float> ProjectNavigatorItemDensity::densityRange_ protected
Referenced by densityInputChanged(), isFilterEnabled(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
The documentation for this class was generated from the following files:
ProjectNavigatorItemDensity.hpp
ProjectNavigatorItemDensity.cpp