3D Forest: Layers Class Reference
Layers Class Reference
#include <Layers.hpp>
Public Member Functions
Layers ()
void clear ()
void setDefault ()
bool isEnabled () const
void setEnabled (bool b)
size_t size () const
const Layer & at (size_t i) const
void push_back (const Layer &layer)
void erase (size_t i)
size_t id (size_t i) const
size_t index (size_t id) const
size_t unusedId () const
bool isEnabledId (size_t id) const
bool isEnabled (size_t i) const
const std::unordered_set< size_t > & enabledList () const
void setEnabled (size_t i, bool b)
void setEnabledAll (bool b)
void setInvertAll ()
const std::string & label (size_t i) const
void setLabel (size_t i, const std::string &label)
const Vector3< float > & color (size_t i) const
void setColor (size_t i, const Vector3< float > &color)
void read (const Json &in)
Json & write (Json &out) const
Protected Attributes
std::vector< Layer > layers_
std::unordered_map< size_t, size_t > hashTableId_
std::unordered_set< size_t > hashTableEnabledId_
bool enabled_
Constructor & Destructor Documentation
Layers()
Layers::Layers ()
Member Function Documentation
at()
const Layer & Layers::at (size_t i) const inline
clear()
void Layers::clear ()
Referenced by SegmentationThread::computeInitializeLayers(), and read().
color()
const Vector3< float > & Layers::color (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), and setColor().
enabledList()
const std::unordered_set< size_t > & Layers::enabledList () const inline
Referenced by Editor::setLayers().
erase()
void Layers::erase (size_t i)
Referenced by ProjectNavigatorLayers::slotDelete().
id()
size_t Layers::id (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), erase(), push_back(), read(), and setDefault().
index()
size_t Layers::index (size_t id) const inline
Referenced by ProjectNavigatorLayers::index().
isEnabled() [1/2]
bool Layers::isEnabled () const inline
Referenced by ProjectNavigatorLayers::addItem(), read(), and ProjectNavigatorLayers::updateTree().
isEnabled() [2/2]
bool Layers::isEnabled (size_t i) const inline
isEnabledId()
bool Layers::isEnabledId (size_t id) const inline
label()
const std::string & Layers::label (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), and setLabel().
push_back()
void Layers::push_back (const Layer & layer)
read()
void Layers::read (const Json & in)
Referenced by Editor::openProject().
setColor()
void Layers::setColor (size_t i, const Vector3< float > & color)
setDefault()
void Layers::setDefault ()
Referenced by Editor::close(), SegmentationThread::computeInitializeLayers(), Layers(), and read().
setEnabled() [1/2]
void Layers::setEnabled (bool b)
Referenced by ProjectNavigatorLayers::slotItemChanged().
setEnabled() [2/2]
void Layers::setEnabled (size_t i, bool b)
setEnabledAll()
void Layers::setEnabledAll (bool b)
setInvertAll()
void Layers::setInvertAll ()
setLabel()
void Layers::setLabel (size_t i, const std::string & label)
size()
size_t Layers::size () const inline
Referenced by ProjectNavigatorLayers::setLayers().
unusedId()
size_t Layers::unusedId () const
write()
Json & Layers::write (Json & out) const
Referenced by Editor::save().
Member Data Documentation
enabled_
bool Layers::enabled_ protected
Referenced by read(), setEnabled(), and write().
hashTableEnabledId_
std::unordered_set<size_t> Layers::hashTableEnabledId_ protected
Referenced by clear(), erase(), push_back(), read(), setDefault(), setEnabled(), setEnabledAll(), and setInvertAll().
hashTableId_
std::unordered_map<size_t, size_t> Layers::hashTableId_ protected
Referenced by clear(), erase(), push_back(), read(), setDefault(), and unusedId().
layers_
std::vector<Layer> Layers::layers_ protected
Referenced by clear(), erase(), push_back(), read(), setColor(), setDefault(), setEnabled(), setEnabledAll(), setInvertAll(), setLabel(), and write().
The documentation for this class was generated from the following files:
Layers.hpp
Layers.cpp