3D Forest: ProgressActionInterface Class Reference
ProgressActionInterface Class Reference abstract
#include <ProgressActionInterface.hpp>
Inherited by ClassificationAction, DensityAction, DescriptorAction, ElevationAction, and ExportFileAction.
Public Member Functions
ProgressActionInterface ()
virtual ~ProgressActionInterface ()=default
virtual void step ()=0
void initialize (uint64_t nElements=npos, uint64_t interleave=1, double secondsPerStep=0.25)
void startTimer ()
bool timedOut ()
bool end () const
double percent () const
uint64_t processed () const
uint64_t process () const
uint64_t maximum () const
bool initializing () const
void increment (uint64_t nElementsProcessed)
Static Public Attributes
static const uint64_t npos = UINT64_MAX
Private Attributes
uint64_t nElements_
uint64_t nElementsProcessed_
uint64_t interleave_
double secondsPerStep_
double timeBegin_
double timeNow_
uint64_t interleaveCounter_
Constructor & Destructor Documentation
ProgressActionInterface()
ProgressActionInterface::ProgressActionInterface ()
~ProgressActionInterface()
virtual ProgressActionInterface::~ProgressActionInterface () virtual default
Member Function Documentation
end()
bool ProgressActionInterface::end () const inline
Referenced by ProgressDialog::run(), ClassificationAction::step(), ElevationAction::step(), and ExportFileAction::step().
increment()
void ProgressActionInterface::increment (uint64_t nElementsProcessed)
Referenced by ClassificationAction::step(), ElevationAction::step(), ExportFileAction::step(), DensityAction::stepComputeDensity(), DescriptorAction::stepComputeDescriptor(), DensityAction::stepNormalizeDensity(), and DescriptorAction::stepNormalizeDescriptor().
initialize()
void ProgressActionInterface::initialize (uint64_t nElements = npos, uint64_t interleave = 1, double secondsPerStep = 0.25)
Referenced by DensityAction::determineMaximum(), DescriptorAction::determineMaximum(), ExportFileAction::determineMaximum(), DensityAction::initialize(), DescriptorAction::initialize(), ElevationAction::initialize(), ClassificationAction::initialize(), and ExportFileAction::initialize().
initializing()
bool ProgressActionInterface::initializing () const inline
Referenced by DensityAction::step(), DescriptorAction::step(), and ExportFileAction::step().
maximum()
uint64_t ProgressActionInterface::maximum () const inline
percent()
double ProgressActionInterface::percent () const
Referenced by ProgressDialog::run().
process()
uint64_t ProgressActionInterface::process () const inline
Referenced by ExportFileAction::step().
processed()
uint64_t ProgressActionInterface::processed () const inline
Referenced by ElevationAction::exportGroundMesh(), and DensityAction::stepComputeDensity().
startTimer()
void ProgressActionInterface::startTimer ()
Referenced by DensityAction::determineMaximum(), DescriptorAction::determineMaximum(), ExportFileAction::determineMaximum(), ExportFileAction::step(), DensityAction::stepComputeDensity(), DescriptorAction::stepComputeDescriptor(), DensityAction::stepNormalizeDensity(), and DescriptorAction::stepNormalizeDescriptor().
step()
virtual void ProgressActionInterface::step () pure virtual
Implemented in ClassificationAction, DensityAction, DescriptorAction, ElevationAction, and ExportFileAction.
Referenced by ProgressDialog::run().
timedOut()
bool ProgressActionInterface::timedOut ()
Referenced by DensityAction::determineMaximum(), DescriptorAction::determineMaximum(), ExportFileAction::determineMaximum(), ExportFileAction::step(), DensityAction::stepComputeDensity(), DescriptorAction::stepComputeDescriptor(), DensityAction::stepNormalizeDensity(), and DescriptorAction::stepNormalizeDescriptor().
Member Data Documentation
interleave_
uint64_t ProgressActionInterface::interleave_ private
Referenced by initialize(), and timedOut().
interleaveCounter_
uint64_t ProgressActionInterface::interleaveCounter_ private
Referenced by initialize(), and timedOut().
nElements_
uint64_t ProgressActionInterface::nElements_ private
Referenced by increment(), initialize(), and percent().
nElementsProcessed_
uint64_t ProgressActionInterface::nElementsProcessed_ private
Referenced by increment(), initialize(), and percent().
npos
const uint64_t ProgressActionInterface::npos = UINT64_MAX static
Referenced by DensityAction::initialize(), DescriptorAction::initialize(), ExportFileAction::initialize(), and percent().
secondsPerStep_
double ProgressActionInterface::secondsPerStep_ private
Referenced by initialize(), and timedOut().
timeBegin_
double ProgressActionInterface::timeBegin_ private
Referenced by initialize(), startTimer(), and timedOut().
timeNow_
double ProgressActionInterface::timeNow_ private
Referenced by initialize(), and timedOut().
The documentation for this class was generated from the following files:
ProgressActionInterface.hpp
ProgressActionInterface.cpp