3D Forest: ImportPlugin Class Reference
ImportPlugin Class Reference
#include <ImportPlugin.hpp>
Inherits QObject.
Public Slots
void slotImport ()
Public Member Functions
ImportPlugin ()
void initialize (MainWindow *mainWindow)
Static Public Member Functions
static void import (MainWindow *mainWindow)
Protected Attributes
MainWindow * mainWindow_
QAction * actionImport_
Constructor & Destructor Documentation
ImportPlugin()
ImportPlugin::ImportPlugin ()
Member Function Documentation
import()
void ImportPlugin::import (MainWindow * mainWindow) static
Referenced by ProjectNavigatorFiles::slotAdd(), and slotImport().
initialize()
void ImportPlugin::initialize (MainWindow * mainWindow)
Referenced by MainWindow::MainWindow().
slotImport
void ImportPlugin::slotImport () slot
Referenced by initialize().
Member Data Documentation
actionImport_
QAction* ImportPlugin::actionImport_ protected
Referenced by initialize().
mainWindow_
MainWindow* ImportPlugin::mainWindow_ protected
Referenced by initialize(), and slotImport().
The documentation for this class was generated from the following files:
ImportPlugin.hpp
ImportPlugin.cpp