3D Forest: ProjectNavigatorPlugin Class Reference
ProjectNavigatorPlugin Class Reference
#include <ProjectNavigatorPlugin.hpp>
Inherits QObject.
Public Slots
void slotPlugin ()
Public Member Functions
ProjectNavigatorPlugin ()
void initialize (MainWindow *mainWindow)
Protected Attributes
MainWindow * mainWindow_
ProjectNavigatorWindow * projectWindow_
Constructor & Destructor Documentation
ProjectNavigatorPlugin()
ProjectNavigatorPlugin::ProjectNavigatorPlugin ()
Member Function Documentation
initialize()
void ProjectNavigatorPlugin::initialize (MainWindow * mainWindow)
Referenced by MainWindow::MainWindow().
slotPlugin
void ProjectNavigatorPlugin::slotPlugin () slot
Referenced by initialize(), and MainWindow::MainWindow().
Member Data Documentation
mainWindow_
MainWindow* ProjectNavigatorPlugin::mainWindow_ protected
Referenced by initialize(), and slotPlugin().
projectWindow_
ProjectNavigatorWindow* ProjectNavigatorPlugin::projectWindow_ protected
Referenced by slotPlugin().
The documentation for this class was generated from the following files:
ProjectNavigatorPlugin.hpp
ProjectNavigatorPlugin.cpp