3D Forest: SegmentationWindow Class Reference
SegmentationWindow Class Reference
#include <SegmentationWindow.hpp>
Inherits QDialog, and ThreadCallbackInterface.
Public Slots
void slotThread (bool finished, int progressPercent)
Signals
void signalThread (bool finished, int progressPercent)
Public Member Functions
SegmentationWindow (MainWindow *mainWindow)
virtual ~SegmentationWindow ()
virtual void threadProgress (bool finished)
Public Member Functions inherited from ThreadCallbackInterface
virtual ~ThreadCallbackInterface ()=default
virtual void threadProgress (bool finished)=0
Protected Slots
void slotVoxelSizeFinalValue ()
void slotSeedElevationMinimumValue ()
void slotSeedElevationMaximumValue ()
void slotTreeHeightFinalValue ()
void slotSearchRadiusFinalValue ()
void slotNeighborPointsFinalValue ()
void slotAccept ()
void slotReject ()
Private Member Functions
virtual void showEvent (QShowEvent *event)
virtual void closeEvent (QCloseEvent *event)
void suspendThreads ()
void resumeThreads ()
void updateRange ()
Private Attributes
MainWindow * mainWindow_
SliderWidget * voxelSizeInput_
RangeSliderWidget * seedElevationInput_
SliderWidget * treeHeightInput_
SliderWidget * searchRadiusInput_
SliderWidget * neighborPointsInput_
QPushButton * acceptButton_
QPushButton * rejectButton_
SegmentationThread segmentationThread_
Constructor & Destructor Documentation
SegmentationWindow()
SegmentationWindow::SegmentationWindow (MainWindow * mainWindow)
~SegmentationWindow()
SegmentationWindow::~SegmentationWindow () virtual
Member Function Documentation
closeEvent()
void SegmentationWindow::closeEvent (QCloseEvent * event) private virtual
resumeThreads()
void SegmentationWindow::resumeThreads () private
Referenced by showEvent(), slotNeighborPointsFinalValue(), slotSearchRadiusFinalValue(), slotSeedElevationMaximumValue(), slotSeedElevationMinimumValue(), slotTreeHeightFinalValue(), and slotVoxelSizeFinalValue().
showEvent()
void SegmentationWindow::showEvent (QShowEvent * event) private virtual
signalThread
void SegmentationWindow::signalThread (bool finished, int progressPercent) signal
Referenced by SegmentationWindow(), and threadProgress().
slotAccept
void SegmentationWindow::slotAccept () protected slot
Referenced by SegmentationWindow().
slotNeighborPointsFinalValue
void SegmentationWindow::slotNeighborPointsFinalValue () protected slot
Referenced by SegmentationWindow().
slotReject
void SegmentationWindow::slotReject () protected slot
Referenced by SegmentationWindow().
slotSearchRadiusFinalValue
void SegmentationWindow::slotSearchRadiusFinalValue () protected slot
Referenced by SegmentationWindow().
slotSeedElevationMaximumValue
void SegmentationWindow::slotSeedElevationMaximumValue () protected slot
Referenced by SegmentationWindow().
slotSeedElevationMinimumValue
void SegmentationWindow::slotSeedElevationMinimumValue () protected slot
Referenced by SegmentationWindow().
slotThread
void SegmentationWindow::slotThread (bool finished, int progressPercent) slot
Referenced by SegmentationWindow().
slotTreeHeightFinalValue
void SegmentationWindow::slotTreeHeightFinalValue () protected slot
Referenced by SegmentationWindow().
slotVoxelSizeFinalValue
void SegmentationWindow::slotVoxelSizeFinalValue () protected slot
Referenced by SegmentationWindow().
suspendThreads()
void SegmentationWindow::suspendThreads () private
Referenced by closeEvent().
threadProgress()
void SegmentationWindow::threadProgress (bool finished) virtual
Implements ThreadCallbackInterface.
updateRange()
void SegmentationWindow::updateRange () private
Referenced by showEvent().
Member Data Documentation
acceptButton_
QPushButton* SegmentationWindow::acceptButton_ private
Referenced by SegmentationWindow().
mainWindow_
MainWindow* SegmentationWindow::mainWindow_ private
Referenced by closeEvent(), resumeThreads(), showEvent(), slotThread(), and suspendThreads().
neighborPointsInput_
SliderWidget* SegmentationWindow::neighborPointsInput_ private
Referenced by resumeThreads(), SegmentationWindow(), and slotNeighborPointsFinalValue().
rejectButton_
QPushButton* SegmentationWindow::rejectButton_ private
Referenced by SegmentationWindow().
searchRadiusInput_
SliderWidget* SegmentationWindow::searchRadiusInput_ private
Referenced by resumeThreads(), and SegmentationWindow().
seedElevationInput_
RangeSliderWidget* SegmentationWindow::seedElevationInput_ private
Referenced by resumeThreads(), SegmentationWindow(), slotSeedElevationMaximumValue(), and slotSeedElevationMinimumValue().
segmentationThread_
SegmentationThread SegmentationWindow::segmentationThread_ private
Referenced by resumeThreads(), SegmentationWindow(), suspendThreads(), threadProgress(), updateRange(), and ~SegmentationWindow().
treeHeightInput_
SliderWidget* SegmentationWindow::treeHeightInput_ private
Referenced by resumeThreads(), SegmentationWindow(), slotSearchRadiusFinalValue(), and slotTreeHeightFinalValue().
voxelSizeInput_
SliderWidget* SegmentationWindow::voxelSizeInput_ private
Referenced by resumeThreads(), SegmentationWindow(), slotVoxelSizeFinalValue(), and updateRange().
The documentation for this class was generated from the following files:
SegmentationWindow.hpp
SegmentationWindow.cpp