3D Forest: ExplorerPlugin Class Reference
ExplorerPlugin Class Reference
#include <ExplorerPlugin.hpp>
Inherits QObject.
Public Slots
void slotPlugin ()
Public Member Functions
ExplorerPlugin ()
void initialize (MainWindow *mainWindow)
QDockWidget * window () const
Protected Attributes
MainWindow * mainWindow_
ExplorerWindow * projectWindow_
Constructor & Destructor Documentation
ExplorerPlugin()
ExplorerPlugin::ExplorerPlugin ()
Member Function Documentation
initialize()
void ExplorerPlugin::initialize (MainWindow * mainWindow)
Referenced by MainWindow::MainWindow().
slotPlugin
void ExplorerPlugin::slotPlugin () slot
Referenced by initialize(), and MainWindow::MainWindow().
window()
QDockWidget * ExplorerPlugin::window () const
Referenced by MainWindow::showEvent().
Member Data Documentation
mainWindow_
MainWindow* ExplorerPlugin::mainWindow_ protected
Referenced by initialize(), and slotPlugin().
projectWindow_
ExplorerWindow* ExplorerPlugin::projectWindow_ protected
Referenced by slotPlugin(), and window().
The documentation for this class was generated from the following files:
ExplorerPlugin.hpp
ExplorerPlugin.cpp