3D Forest: FilterClassificationWidget Class Reference
FilterClassificationWidget Class Reference
#include <FilterClassificationWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
FilterClassificationWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void setClassifications (const Classifications &classifications, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
bool updatesEnabled_
Classifications classifications_
QueryFilterSet filter_
Member Enumeration Documentation
Column
enum FilterClassificationWidget::Column protected
Filter Classification Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
FilterClassificationWidget()
FilterClassificationWidget::FilterClassificationWidget (MainWindow * mainWindow)
Member Function Documentation
addTreeItem()
void FilterClassificationWidget::addTreeItem (size_t index) protected
Referenced by setClassifications().
block()
void FilterClassificationWidget::block () protected
Referenced by setClassifications(), and updateTree().
dataChanged()
void FilterClassificationWidget::dataChanged () protected
filterChanged()
void FilterClassificationWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
identifier()
size_t FilterClassificationWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotItemChanged().
setClassifications()
void FilterClassificationWidget::setClassifications (const Classifications & classifications, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
setFilterEnabled()
void FilterClassificationWidget::setFilterEnabled (bool b)
Referenced by FilterClassificationWindow::closeEvent(), and FilterClassificationWindow::showEvent().
sizeHint()
QSize FilterClassificationWidget::sizeHint () const inline override
slotHide
void FilterClassificationWidget::slotHide () slot
Referenced by FilterClassificationWidget().
slotItemChanged
void FilterClassificationWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void FilterClassificationWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void FilterClassificationWidget::slotSelectAll () slot
Referenced by FilterClassificationWidget().
slotSelectInvert
void FilterClassificationWidget::slotSelectInvert () slot
Referenced by FilterClassificationWidget().
slotSelectNone
void FilterClassificationWidget::slotSelectNone () slot
Referenced by FilterClassificationWidget().
slotShow
void FilterClassificationWidget::slotShow () slot
Referenced by FilterClassificationWidget().
slotUpdate
void FilterClassificationWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterClassificationWidget().
unblock()
void FilterClassificationWidget::unblock () protected
Referenced by setClassifications(), and updateTree().
updateTree()
void FilterClassificationWidget::updateTree () protected
Member Data Documentation
classifications_
Classifications FilterClassificationWidget::classifications_ protected
Referenced by addTreeItem(), dataChanged(), and setClassifications().
filter_
QueryFilterSet FilterClassificationWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), setClassifications(), setFilterEnabled(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* FilterClassificationWidget::hideButton_ protected
Referenced by FilterClassificationWidget(), and slotItemSelectionChanged().
mainWindow_
MainWindow* FilterClassificationWidget::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), FilterClassificationWidget(), and slotUpdate().
selectAllButton_
QToolButton* FilterClassificationWidget::selectAllButton_ protected
Referenced by FilterClassificationWidget().
selectInvertButton_
QToolButton* FilterClassificationWidget::selectInvertButton_ protected
Referenced by FilterClassificationWidget().
selectNoneButton_
QToolButton* FilterClassificationWidget::selectNoneButton_ protected
Referenced by FilterClassificationWidget().
showButton_
QToolButton* FilterClassificationWidget::showButton_ protected
Referenced by FilterClassificationWidget(), and slotItemSelectionChanged().
tree_
QTreeWidget* FilterClassificationWidget::tree_ protected
Referenced by addTreeItem(), block(), FilterClassificationWidget(), setClassifications(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool FilterClassificationWidget::updatesEnabled_ protected
Referenced by FilterClassificationWidget(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
FilterClassificationWidget.hpp
FilterClassificationWidget.cpp