3D Forest: ExplorerClassificationsWidget Class Reference
ExplorerClassificationsWidget Class Reference
#include <ExplorerClassificationsWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ExplorerClassificationsWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void setClassifications (const Classifications &classifications, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
QTreeWidget * tree_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Classifications classifications_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ExplorerClassificationsWidget::Column protected
Explorer Classifications Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ExplorerClassificationsWidget()
ExplorerClassificationsWidget::ExplorerClassificationsWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ExplorerClassificationsWidget::addTreeItem (size_t index) protected
Referenced by setClassifications().
block()
void ExplorerClassificationsWidget::block () protected
Referenced by setClassifications(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ExplorerClassificationsWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
dataChanged()
void ExplorerClassificationsWidget::dataChanged () protected
filterChanged()
void ExplorerClassificationsWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ExplorerClassificationsWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerClassificationsWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
identifier()
size_t ExplorerClassificationsWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotItemChanged().
isFilterEnabled()
bool ExplorerClassificationsWidget::isFilterEnabled () const virtual
Reimplemented from ExplorerWidgetInterface.
setClassifications()
void ExplorerClassificationsWidget::setClassifications (const Classifications & classifications, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
setFilterEnabled()
void ExplorerClassificationsWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
slotHide
void ExplorerClassificationsWidget::slotHide () slot
Referenced by ExplorerClassificationsWidget().
slotItemChanged
void ExplorerClassificationsWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ExplorerClassificationsWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ExplorerClassificationsWidget::slotSelectAll () slot
Referenced by ExplorerClassificationsWidget().
slotSelectInvert
void ExplorerClassificationsWidget::slotSelectInvert () slot
Referenced by ExplorerClassificationsWidget().
slotSelectNone
void ExplorerClassificationsWidget::slotSelectNone () slot
Referenced by ExplorerClassificationsWidget().
slotShow
void ExplorerClassificationsWidget::slotShow () slot
Referenced by ExplorerClassificationsWidget().
slotUpdate
void ExplorerClassificationsWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerClassificationsWidget().
unblock()
void ExplorerClassificationsWidget::unblock () protected
Referenced by setClassifications(), and updateTree().
updateTree()
void ExplorerClassificationsWidget::updateTree () protected
Member Data Documentation
classifications_
Classifications ExplorerClassificationsWidget::classifications_ protected
Referenced by addTreeItem(), dataChanged(), and setClassifications().
filter_
QueryFilterSet ExplorerClassificationsWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setClassifications(), setFilterEnabled(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ExplorerClassificationsWidget::hideButton_ protected
Referenced by ExplorerClassificationsWidget(), and slotItemSelectionChanged().
selectAllButton_
QToolButton* ExplorerClassificationsWidget::selectAllButton_ protected
Referenced by ExplorerClassificationsWidget().
selectInvertButton_
QToolButton* ExplorerClassificationsWidget::selectInvertButton_ protected
Referenced by ExplorerClassificationsWidget().
selectNoneButton_
QToolButton* ExplorerClassificationsWidget::selectNoneButton_ protected
Referenced by ExplorerClassificationsWidget().
showButton_
QToolButton* ExplorerClassificationsWidget::showButton_ protected
Referenced by ExplorerClassificationsWidget(), and slotItemSelectionChanged().
tree_
QTreeWidget* ExplorerClassificationsWidget::tree_ protected
Referenced by addTreeItem(), block(), ExplorerClassificationsWidget(), setClassifications(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ExplorerClassificationsWidget::updatesEnabled_ protected
Referenced by ExplorerClassificationsWidget(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ExplorerClassificationsWidget.hpp
ExplorerClassificationsWidget.cpp