3D Forest: ViewerOpenGL Class Reference
ViewerOpenGL Class Reference
#include <ViewerOpenGL.hpp>
Public Types
enum Mode { POINTS , LINES , QUADS }
Public Member Functions
ViewerOpenGL ()
~ViewerOpenGL ()
Static Public Member Functions
static void render (Mode mode, const float *xyz, size_t xyzSize, const float *rgb, size_t rgbSize)
static void render (Mode mode, const float *xyz, size_t xyzSize, const float *rgb, size_t rgbSize, const unsigned int *indices, size_t indicesSize)
static void renderClipFilter (const Region &clipFilter)
static void renderAabb (const ViewerAabb &box)
static void renderCylinder (const Vector3< float > &a, const Vector3< float > &b, float radius, size_t slices=16)
static void renderAxis ()
static void renderCross (const Vector3< float > &p, float lengthX, float lengthY)
static void renderLine (const Vector3< float > &a, const Vector3< float > &b)
static void renderCircle (const Vector3< float > &p, float radius, size_t pointCount=16)
Member Enumeration Documentation
Mode
enum ViewerOpenGL::Mode
Enumerator
POINTS
LINES
QUADS
Constructor & Destructor Documentation
ViewerOpenGL()
ViewerOpenGL::ViewerOpenGL ()
~ViewerOpenGL()
ViewerOpenGL::~ViewerOpenGL ()
Member Function Documentation
render() [1/2]
void ViewerOpenGL::render (Mode mode, const float * xyz, size_t xyzSize, const float * rgb, size_t rgbSize) static
Referenced by ViewerOpenGLViewport::renderScene(), and ViewerOpenGLViewport::renderSegments().
render() [2/2]
void ViewerOpenGL::render (Mode mode, const float * xyz, size_t xyzSize, const float * rgb, size_t rgbSize, const unsigned int * indices, size_t indicesSize) static
renderAabb()
void ViewerOpenGL::renderAabb (const ViewerAabb & box) static
Referenced by renderClipFilter(), ViewerOpenGLViewport::renderFirstFrame(), and ViewerOpenGLViewport::renderSegments().
renderAxis()
void ViewerOpenGL::renderAxis () static
Referenced by ViewerOpenGLViewport::renderGuides().
renderCircle()
void ViewerOpenGL::renderCircle (const Vector3< float > & p, float radius, size_t pointCount = 16) static
Referenced by ViewerOpenGLViewport::renderAttributes().
renderClipFilter()
void ViewerOpenGL::renderClipFilter (const Region & clipFilter) static
Referenced by ViewerOpenGLViewport::renderFirstFrame().
renderCross()
void ViewerOpenGL::renderCross (const Vector3< float > & p, float lengthX, float lengthY) static
Referenced by ViewerOpenGLViewport::renderAttributes().
renderCylinder()
void ViewerOpenGL::renderCylinder (const Vector3< float > & a, const Vector3< float > & b, float radius, size_t slices = 16) static
Referenced by renderClipFilter().
renderLine()
void ViewerOpenGL::renderLine (const Vector3< float > & a, const Vector3< float > & b) static
Referenced by ViewerOpenGLViewport::renderAttributes().
The documentation for this class was generated from the following files:
ViewerOpenGL.hpp
ViewerOpenGL.cpp