3D Forest: FilterDescriptorWidget Class Reference
FilterDescriptorWidget Class Reference
#include <FilterDescriptorWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
FilterDescriptorWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Member Functions
void setDescriptor (const Range< double > &descriptorRange)
void filterChanged ()
Protected Attributes
MainWindow * mainWindow_
DoubleRangeSliderWidget * descriptorInput_
Range< double > descriptorRange_
Constructor & Destructor Documentation
FilterDescriptorWidget()
FilterDescriptorWidget::FilterDescriptorWidget (MainWindow * mainWindow)
Member Function Documentation
filterChanged()
void FilterDescriptorWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
setDescriptor()
void FilterDescriptorWidget::setDescriptor (const Range< double > & descriptorRange) protected
Referenced by slotUpdate().
setFilterEnabled()
void FilterDescriptorWidget::setFilterEnabled (bool b)
Referenced by FilterDescriptorWindow::closeEvent(), and FilterDescriptorWindow::showEvent().
sizeHint()
QSize FilterDescriptorWidget::sizeHint () const inline override
slotRangeIntermediateMaximumValue
void FilterDescriptorWidget::slotRangeIntermediateMaximumValue () slot
Referenced by FilterDescriptorWidget().
slotRangeIntermediateMinimumValue
void FilterDescriptorWidget::slotRangeIntermediateMinimumValue () slot
Referenced by FilterDescriptorWidget().
slotUpdate
void FilterDescriptorWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterDescriptorWidget().
Member Data Documentation
descriptorInput_
DoubleRangeSliderWidget* FilterDescriptorWidget::descriptorInput_ protected
Referenced by FilterDescriptorWidget(), setDescriptor(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
descriptorRange_
Range<double> FilterDescriptorWidget::descriptorRange_ protected
Referenced by filterChanged(), setDescriptor(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
mainWindow_
MainWindow* FilterDescriptorWidget::mainWindow_ protected
Referenced by filterChanged(), FilterDescriptorWidget(), and slotUpdate().
The documentation for this class was generated from the following files:
FilterDescriptorWidget.hpp
FilterDescriptorWidget.cpp