3D Forest: ProjectNavigatorItemElevation Class Reference
ProjectNavigatorItemElevation Class Reference
#include <ProjectNavigatorItemElevation.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
ProjectNavigatorItemElevation (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void elevationInputChanged ()
Protected Attributes
RangeSliderWidget * rangeInput_
Range< double > elevationRange_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ProjectNavigatorItemElevation()
ProjectNavigatorItemElevation::ProjectNavigatorItemElevation (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemElevation::colorSource () const inline virtual
Implements ProjectNavigatorItem.
elevationInputChanged()
void ProjectNavigatorItemElevation::elevationInputChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ProjectNavigatorItemElevation::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemElevation::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
isFilterEnabled()
bool ProjectNavigatorItemElevation::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setFilterEnabled()
void ProjectNavigatorItemElevation::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotRangeIntermediateMaximumValue
void ProjectNavigatorItemElevation::slotRangeIntermediateMaximumValue () slot
Referenced by ProjectNavigatorItemElevation().
slotRangeIntermediateMinimumValue
void ProjectNavigatorItemElevation::slotRangeIntermediateMinimumValue () slot
Referenced by ProjectNavigatorItemElevation().
slotUpdate
void ProjectNavigatorItemElevation::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemElevation().
Member Data Documentation
elevationRange_
Range<double> ProjectNavigatorItemElevation::elevationRange_ protected
Referenced by elevationInputChanged(), isFilterEnabled(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
rangeInput_
RangeSliderWidget* ProjectNavigatorItemElevation::rangeInput_ protected
Referenced by ProjectNavigatorItemElevation(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
The documentation for this class was generated from the following files:
ProjectNavigatorItemElevation.hpp
ProjectNavigatorItemElevation.cpp