3D Forest: ComputeTreeAttributesAction Class Reference
ComputeTreeAttributesAction Class Reference
#include <ComputeTreeAttributesAction.hpp>
Inherits ProgressActionInterface.
Public Member Functions
ComputeTreeAttributesAction (Editor *editor)
virtual ~ComputeTreeAttributesAction ()
void start (const ComputeTreeAttributesParameters &parameters)
virtual void next ()
void clear ()
Public Member Functions inherited from ProgressActionInterface
ProgressActionInterface ()
virtual ~ProgressActionInterface ()=default
bool end () const
size_t progressMaximumSteps () const
size_t progressValueSteps () const
uint64_t progressMaximumStep () const
uint64_t progressValueStep () const
double progressPercent () const
Private Member Functions
void stepPointsToTrees ()
void stepCalculateComputeTreeAttributes ()
void stepUpdateComputeTreeAttributes ()
void calculateDbh (ComputeTreeAttributesData &tree)
void calculateTreePosition (ComputeTreeAttributesData &tree)
void calculateTreeHeight (ComputeTreeAttributesData &tree)
void validateAttributes (TreeAttributes &treeAttributes)
size_t treeIndex (size_t treeId)
Private Attributes
Editor * editor_
Query query_
ComputeTreeAttributesParameters parameters_
std::map< size_t, size_t > treesMap_
std::vector< ComputeTreeAttributesData > trees_
size_t currentTreeIndex_
Additional Inherited Members
Protected Attributes inherited from ProgressActionInterface
ProgressCounter progress_
Constructor & Destructor Documentation
ComputeTreeAttributesAction()
ComputeTreeAttributesAction::ComputeTreeAttributesAction (Editor * editor)
~ComputeTreeAttributesAction()
ComputeTreeAttributesAction::~ComputeTreeAttributesAction () virtual
Member Function Documentation
calculateDbh()
void ComputeTreeAttributesAction::calculateDbh (ComputeTreeAttributesData & tree) private
Referenced by stepCalculateComputeTreeAttributes().
calculateTreeHeight()
void ComputeTreeAttributesAction::calculateTreeHeight (ComputeTreeAttributesData & tree) private
Referenced by stepCalculateComputeTreeAttributes().
calculateTreePosition()
void ComputeTreeAttributesAction::calculateTreePosition (ComputeTreeAttributesData & tree) private
Referenced by stepCalculateComputeTreeAttributes().
clear()
void ComputeTreeAttributesAction::clear ()
Referenced by ComputeTreeAttributesWidget::hideEvent().
next()
void ComputeTreeAttributesAction::next () virtual
Implements ProgressActionInterface.
start()
void ComputeTreeAttributesAction::start (const ComputeTreeAttributesParameters & parameters)
Referenced by ComputeTreeAttributesWidget::slotApply().
stepCalculateComputeTreeAttributes()
void ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes () private
Referenced by next().
stepPointsToTrees()
void ComputeTreeAttributesAction::stepPointsToTrees () private
Referenced by next().
stepUpdateComputeTreeAttributes()
void ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes () private
Referenced by next().
treeIndex()
size_t ComputeTreeAttributesAction::treeIndex (size_t treeId) private
Referenced by stepPointsToTrees().
validateAttributes()
void ComputeTreeAttributesAction::validateAttributes (TreeAttributes & treeAttributes) private
Referenced by stepUpdateComputeTreeAttributes().
Member Data Documentation
currentTreeIndex_
size_t ComputeTreeAttributesAction::currentTreeIndex_ private
Referenced by stepCalculateComputeTreeAttributes().
editor_
Editor* ComputeTreeAttributesAction::editor_ private
Referenced by start(), stepPointsToTrees(), and stepUpdateComputeTreeAttributes().
parameters_
ComputeTreeAttributesParameters ComputeTreeAttributesAction::parameters_ private
Referenced by calculateDbh(), start(), stepPointsToTrees(), and validateAttributes().
query_
Query ComputeTreeAttributesAction::query_ private
Referenced by clear(), and stepPointsToTrees().
trees_
std::vector<ComputeTreeAttributesData> ComputeTreeAttributesAction::trees_ private
Referenced by clear(), start(), stepCalculateComputeTreeAttributes(), stepPointsToTrees(), stepUpdateComputeTreeAttributes(), and treeIndex().
treesMap_
std::map<size_t, size_t> ComputeTreeAttributesAction::treesMap_ private
Referenced by clear(), start(), and treeIndex().
The documentation for this class was generated from the following files:
ComputeTreeAttributesAction.hpp
ComputeTreeAttributesAction.cpp