3D Forest: TreeTableExportProperties Class Reference
TreeTableExportProperties Class Reference
#include <TreeTableExportProperties.hpp>
Public Member Functions
void setFileName (const std::string &fileName)
const std::string & fileName () const
void setExportValidValuesOnly (bool b)
bool exportValidValuesOnly () const
void setPointsPerMeter (double ppm)
double pointsPerMeter () const
Private Attributes
std::string fileName_
bool exportValidValuesOnly_ {true}
double pointsPerMeter_ {1000.0}
Member Function Documentation
exportValidValuesOnly()
bool TreeTableExportProperties::exportValidValuesOnly () const inline
Referenced by TreeTableExportCsv::create(), and TreeTableExportCsv::write().
fileName()
const std::string & TreeTableExportProperties::fileName () const inline
Referenced by setFileName().
pointsPerMeter()
double TreeTableExportProperties::pointsPerMeter () const inline
Referenced by TreeTableExportCsv::write().
setExportValidValuesOnly()
void TreeTableExportProperties::setExportValidValuesOnly (bool b) inline
Referenced by TreeTableExportDialog::properties().
setFileName()
void TreeTableExportProperties::setFileName (const std::string & fileName) inline
Referenced by TreeTableExportDialog::properties().
setPointsPerMeter()
void TreeTableExportProperties::setPointsPerMeter (double ppm) inline
Referenced by TreeTableExportDialog::properties().
Member Data Documentation
exportValidValuesOnly_
bool TreeTableExportProperties::exportValidValuesOnly_ {true} private
Referenced by exportValidValuesOnly(), and setExportValidValuesOnly().
fileName_
std::string TreeTableExportProperties::fileName_ private
Referenced by fileName(), and setFileName().
pointsPerMeter_
double TreeTableExportProperties::pointsPerMeter_ {1000.0} private
Referenced by pointsPerMeter(), and setPointsPerMeter().
The documentation for this class was generated from the following file:
TreeTableExportProperties.hpp