3D Forest: SettingsColorWidget Class Reference
SettingsColorWidget Class Reference
#include <SettingsColorWidget.hpp>
Inherits QWidget.
Public Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_OPACITY ,
COLUMN_LAST
}
Public Slots
void slotUpdate ()
void slotSetPointSize (int v)
void slotSetFogEnabled (int v)
void slotSetColorFg ()
void slotSetColorBg ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
SettingsColorWidget (MainWindow *mainWindow)
Protected Member Functions
void settingsChanged ()
void settingsChangedApply ()
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addItem (size_t i)
void setColorSource (const SettingsView &settings)
void setSettings (const SettingsView &settings)
bool colorDialog (Vector3< float > &rgb)
void setColor (QPushButton *button, const Vector3< float > &rgb)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * treeWidget_
QCheckBox * fogCheckBox_
QPushButton * colorFgButton_
QPushButton * colorBgButton_
QSlider * pointSizeSlider_
SettingsView settings_
Member Enumeration Documentation
Column
enum SettingsColorWidget::Column
Settings Color Widget Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_OPACITY
COLUMN_LAST
Constructor & Destructor Documentation
SettingsColorWidget()
SettingsColorWidget::SettingsColorWidget (MainWindow * mainWindow)
Member Function Documentation
addItem()
void SettingsColorWidget::addItem (size_t i) protected
Referenced by setColorSource().
block()
void SettingsColorWidget::block () protected
Referenced by setSettings(), and updateTree().
colorDialog()
bool SettingsColorWidget::colorDialog (Vector3< float > & rgb) protected
Referenced by slotSetColorBg(), and slotSetColorFg().
index()
size_t SettingsColorWidget::index (const QTreeWidgetItem * item) protected
Referenced by slotItemChanged(), and updateTree().
setColor()
void SettingsColorWidget::setColor (QPushButton * button, const Vector3< float > & rgb) protected
Referenced by setSettings(), slotSetColorBg(), and slotSetColorFg().
setColorSource()
void SettingsColorWidget::setColorSource (const SettingsView & settings) protected
Referenced by setSettings().
setSettings()
void SettingsColorWidget::setSettings (const SettingsView & settings) protected
Referenced by slotUpdate().
settingsChanged()
void SettingsColorWidget::settingsChanged () protected
Referenced by slotSetFogEnabled(), and slotSetPointSize().
settingsChangedApply()
void SettingsColorWidget::settingsChangedApply () protected
Referenced by slotItemChanged(), slotSetColorBg(), and slotSetColorFg().
slotItemChanged
void SettingsColorWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotSetColorBg
void SettingsColorWidget::slotSetColorBg () slot
Referenced by SettingsColorWidget().
slotSetColorFg
void SettingsColorWidget::slotSetColorFg () slot
Referenced by SettingsColorWidget().
slotSetFogEnabled
void SettingsColorWidget::slotSetFogEnabled (int v) slot
Referenced by SettingsColorWidget().
slotSetPointSize
void SettingsColorWidget::slotSetPointSize (int v) slot
Referenced by SettingsColorWidget().
slotUpdate
void SettingsColorWidget::slotUpdate () slot
Referenced by SettingsColorWidget().
unblock()
void SettingsColorWidget::unblock () protected
Referenced by setSettings(), and updateTree().
updateTree()
void SettingsColorWidget::updateTree () protected
Member Data Documentation
colorBgButton_
QPushButton* SettingsColorWidget::colorBgButton_ protected
Referenced by setSettings(), SettingsColorWidget(), and slotSetColorBg().
colorFgButton_
QPushButton* SettingsColorWidget::colorFgButton_ protected
Referenced by setSettings(), SettingsColorWidget(), and slotSetColorFg().
fogCheckBox_
QCheckBox* SettingsColorWidget::fogCheckBox_ protected
Referenced by SettingsColorWidget(), and slotSetFogEnabled().
mainWindow_
MainWindow* SettingsColorWidget::mainWindow_ protected
Referenced by settingsChanged(), settingsChangedApply(), SettingsColorWidget(), and slotUpdate().
pointSizeSlider_
QSlider* SettingsColorWidget::pointSizeSlider_ protected
Referenced by setSettings(), and SettingsColorWidget().
settings_
SettingsView SettingsColorWidget::settings_ protected
Referenced by addItem(), setSettings(), settingsChanged(), settingsChangedApply(), SettingsColorWidget(), slotItemChanged(), slotSetColorBg(), slotSetColorFg(), slotSetFogEnabled(), slotSetPointSize(), and updateTree().
treeWidget_
QTreeWidget* SettingsColorWidget::treeWidget_ protected
Referenced by addItem(), block(), setColorSource(), SettingsColorWidget(), unblock(), and updateTree().
The documentation for this class was generated from the following files:
SettingsColorWidget.hpp
SettingsColorWidget.cpp