3D Forest: IndexFile Class Reference
IndexFile Class Reference
#include <IndexFile.hpp>
Classes
struct BuildNode
struct Node
struct Selection
struct SelectionTile
Public Member Functions
IndexFile ()
~IndexFile ()
void clear ()
void translate (const Vector3< double > &v)
const Box< double > & boundary () const
const Box< double > & boundaryPoints () const
size_t size () const
bool empty () const
void selectLeaves (std::vector< SelectionTile > &selection, const Box< double > &window, size_t datasetId, size_t tileId) const
void selectLeaves (std::vector< Selection > &selection, const Box< double > &window, size_t id) const
void selectNodes (std::vector< Selection > &selection, const Box< double > &window, size_t id) const
const Node * selectNode (std::map< const Node *, uint64_t > &used, double x, double y, double z) const
const Node * selectLeaf (double x, double y, double z) const
const Node * root () const
const Node * next (const Node *node, size_t idx) const
const Node * prev (const Node *node) const
const Node * at (size_t idx) const
Node * at (size_t idx)
Box< double > boundary (const Node *node, const Box< double > &box) const
void read (const std::string &path)
void read (const std::string &path, uint64_t offset)
void read (ChunkFile &file)
void readPayload (ChunkFile &file, const ChunkFile::Chunk &chunk)
void write (const std::string &path) const
void write (ChunkFile &file) const
void insertBegin (const Box< double > &boundary, const Box< double > &boundaryPoints, size_t maxSize, size_t maxLevel=0, bool insertOnlyToLeaves=false)
uint64_t insert (double x, double y, double z)
void insertEnd ()
Static Public Attributes
static const uint32_t CHUNK_TYPE = 0x38584449U
Protected Member Functions
void selectLeaves (std::vector< SelectionTile > &selection, const Box< double > &window, const Box< double > &boundary, size_t datasetId, size_t tileId, size_t idx) const
void selectLeaves (std::vector< Selection > &idxList, const Box< double > &window, const Box< double > &boundary, size_t idx, size_t id) const
void selectNodes (std::vector< Selection > &idxList, const Box< double > &window, const Box< double > &boundary, size_t idx, size_t id) const
const Node * selectNode (std::map< const Node *, uint64_t > &used, double x, double y, double z, const Box< double > &boundary, size_t idx) const
const Node * selectLeaf (double x, double y, double z, const Box< double > &boundary, size_t idx) const
void divide (Box< double > &boundary, double x, double y, double z, uint64_t code) const
uint64_t insertEndToLeaves (Node *data, BuildNode *node, uint32_t prev, uint32_t &idx, uint64_t &from)
size_t countNodes () const
size_t countNodes (BuildNode *node) const
Protected Attributes
Box< double > boundary_
Box< double > boundaryFile_
Box< double > boundaryPoints_
Box< double > boundaryPointsFile_
std::vector< Node > nodes_
std::shared_ptr< BuildNode > root_
size_t maxSize_
size_t maxLevel_
bool insertOnlyToLeaves_
Friends
void toJson (Json &out, const IndexFile &in)
Constructor & Destructor Documentation
IndexFile()
IndexFile::IndexFile ()
~IndexFile()
IndexFile::~IndexFile ()
Member Function Documentation
at() [1/2]
Node * IndexFile::at (size_t idx) inline
at() [2/2]
const Node * IndexFile::at (size_t idx) const inline
Referenced by Query::applyCamera(), Page::queryWhereBox(), Page::queryWhereCone(), Page::queryWhereCylinder(), Page::queryWhereSphere(), PageData::readPage(), IndexFileBuilder::stateNodeInsert(), and PageData::writePage().
boundary() [1/2]
const Box< double > & IndexFile::boundary () const inline
Referenced by Query::applyCamera(), boundary(), divide(), insertBegin(), selectLeaf(), selectLeaves(), selectLeaves(), selectNode(), and selectNodes().
boundary() [2/2]
Box< double > IndexFile::boundary (const Node * node, const Box< double > & box) const
boundaryPoints()
const Box< double > & IndexFile::boundaryPoints () const inline
Referenced by insertBegin().
clear()
void IndexFile::clear ()
Referenced by insertBegin(), IndexFileBuilder::start(), and IndexFileBuilder::stateNodeInsert().
countNodes() [1/2]
size_t IndexFile::countNodes () const protected
Referenced by countNodes(), countNodes(), and insertEnd().
countNodes() [2/2]
size_t IndexFile::countNodes (BuildNode * node) const protected
divide()
void IndexFile::divide (Box< double > & boundary, double x, double y, double z, uint64_t code) const protected
Referenced by boundary(), selectLeaf(), selectLeaves(), selectLeaves(), selectNode(), and selectNodes().
empty()
bool IndexFile::empty () const inline
Referenced by selectLeaves(), selectLeaves(), and selectNodes().
insert()
uint64_t IndexFile::insert (double x, double y, double z)
Referenced by IndexFileBuilder::stateMainInsert(), and IndexFileBuilder::stateNodeInsert().
insertBegin()
void IndexFile::insertBegin (const Box< double > & boundary, const Box< double > & boundaryPoints, size_t maxSize, size_t maxLevel = 0, bool insertOnlyToLeaves = false)
<
Referenced by IndexFileBuilder::stateMainBegin(), and IndexFileBuilder::stateNodeInsert().
insertEnd()
void IndexFile::insertEnd ()
Referenced by IndexFileBuilder::stateMainEnd(), and IndexFileBuilder::stateNodeInsert().
insertEndToLeaves()
uint64_t IndexFile::insertEndToLeaves (Node * data, BuildNode * node, uint32_t prev, uint32_t & idx, uint64_t & from) protected
Referenced by insertEnd(), and insertEndToLeaves().
next()
const IndexFile::Node * IndexFile::next (const Node * node, size_t idx) const
Referenced by boundary(), and write().
prev()
const IndexFile::Node * IndexFile::prev (const Node * node) const
Referenced by boundary(), insertEnd(), insertEndToLeaves(), and write().
read() [1/3]
void IndexFile::read (ChunkFile & file)
read() [2/3]
void IndexFile::read (const std::string & path)
Referenced by read(), read(), and PageData::readPage().
read() [3/3]
void IndexFile::read (const std::string & path, uint64_t offset)
readPayload()
void IndexFile::readPayload (ChunkFile & file, const ChunkFile::Chunk & chunk)
Referenced by read().
root()
const IndexFile::Node * IndexFile::root () const
Referenced by prev().
selectLeaf() [1/2]
const IndexFile::Node * IndexFile::selectLeaf (double x, double y, double z) const
Referenced by selectLeaf(), and selectLeaf().
selectLeaf() [2/2]
const IndexFile::Node * IndexFile::selectLeaf (double x, double y, double z, const Box< double > & boundary, size_t idx) const protected
selectLeaves() [1/4]
void IndexFile::selectLeaves (std::vector< Selection > & idxList, const Box< double > & window, const Box< double > & boundary, size_t idx, size_t id) const protected
selectLeaves() [2/4]
void IndexFile::selectLeaves (std::vector< Selection > & selection, const Box< double > & window, size_t id) const
selectLeaves() [3/4]
void IndexFile::selectLeaves (std::vector< SelectionTile > & selection, const Box< double > & window, const Box< double > & boundary, size_t datasetId, size_t tileId, size_t idx) const protected
selectLeaves() [4/4]
void IndexFile::selectLeaves (std::vector< SelectionTile > & selection, const Box< double > & window, size_t datasetId, size_t tileId) const
Referenced by Page::queryWhereBox(), Page::queryWhereCone(), Page::queryWhereCylinder(), Page::queryWhereSphere(), selectLeaves(), selectLeaves(), selectLeaves(), and selectLeaves().
selectNode() [1/2]
const IndexFile::Node * IndexFile::selectNode (std::map< const Node *, uint64_t > & used, double x, double y, double z) const
Referenced by selectNode(), selectNode(), and IndexFileBuilder::stateMainSort().
selectNode() [2/2]
const IndexFile::Node * IndexFile::selectNode (std::map< const Node *, uint64_t > & used, double x, double y, double z, const Box< double > & boundary, size_t idx) const protected
selectNodes() [1/2]
void IndexFile::selectNodes (std::vector< Selection > & idxList, const Box< double > & window, const Box< double > & boundary, size_t idx, size_t id) const protected
selectNodes() [2/2]
void IndexFile::selectNodes (std::vector< Selection > & selection, const Box< double > & window, size_t id) const
Referenced by selectNodes(), and selectNodes().
size()
size_t IndexFile::size () const inline
Referenced by IndexFileBuilder::nextState(), selectLeaf(), selectNode(), and write().
translate()
void IndexFile::translate (const Vector3< double > & v)
Referenced by PageData::readPage().
write() [1/2]
void IndexFile::write (ChunkFile & file) const
write() [2/2]
void IndexFile::write (const std::string & path) const
Referenced by IndexFileBuilder::stateMainEnd(), IndexFileBuilder::stateNodeEnd(), IndexFileBuilder::stateNodeInsert(), and write().
Friends And Related Symbol Documentation
toJson
void toJson (Json & out, const IndexFile & in) friend
Member Data Documentation
boundary_
Box<double> IndexFile::boundary_ protected
Referenced by clear(), insert(), insertBegin(), readPayload(), selectLeaf(), selectLeaves(), selectLeaves(), selectNode(), selectNodes(), and translate().
boundaryFile_
Box<double> IndexFile::boundaryFile_ protected
Referenced by clear(), insertBegin(), readPayload(), translate(), and write().
boundaryPoints_
Box<double> IndexFile::boundaryPoints_ protected
Referenced by clear(), insertBegin(), readPayload(), and translate().
boundaryPointsFile_
Box<double> IndexFile::boundaryPointsFile_ protected
Referenced by clear(), insertBegin(), readPayload(), translate(), and write().
CHUNK_TYPE
const uint32_t IndexFile::CHUNK_TYPE = 0x38584449U static
Signature "IDX8".
Referenced by readPayload(), and write().
insertOnlyToLeaves_
bool IndexFile::insertOnlyToLeaves_ protected
Referenced by insert(), insertBegin(), and insertEnd().
maxLevel_
size_t IndexFile::maxLevel_ protected
Referenced by insert(), and insertBegin().
maxSize_
size_t IndexFile::maxSize_ protected
Referenced by insert(), and insertBegin().
nodes_
std::vector<Node> IndexFile::nodes_ protected
Referenced by boundary(), clear(), insertEnd(), next(), prev(), readPayload(), root(), selectLeaf(), selectLeaves(), selectLeaves(), selectNode(), selectNodes(), and write().
root_
std::shared_ptr<BuildNode> IndexFile::root_ protected
Referenced by clear(), countNodes(), insert(), insertBegin(), and insertEnd().
The documentation for this class was generated from the following files:
IndexFile.hpp
IndexFile.cpp