3D Forest: InfoDialog Class Reference
InfoDialog Class Reference
#include <InfoDialog.hpp>
Inherits QDialog.
Public Slots
void slotClose ()
Public Member Functions
InfoDialog (QWidget *parent=nullptr, int w=0, int h=0)
QSize sizeHint () const override
QSize minimumSizeHint () const override
void setText (const QString &text)
Private Attributes
int defaultWidth_
int defaultHeight_
QTextEdit * textEdit_
QPushButton * closeButton_
Constructor & Destructor Documentation
InfoDialog()
InfoDialog::InfoDialog (QWidget * parent = nullptr, int w = 0, int h = 0)
Member Function Documentation
minimumSizeHint()
QSize InfoDialog::minimumSizeHint () const override
setText()
void InfoDialog::setText (const QString & text)
Referenced by ComputeClassificationWidget::slotHelp(), ComputeDescriptorWidget::slotHelp(), ComputeElevationWidget::slotHelp(), ComputeSegmentationNNWidget::slotHelp(), and ImportFileDialog::slotHelp().
sizeHint()
QSize InfoDialog::sizeHint () const override
slotClose
void InfoDialog::slotClose () slot
Referenced by InfoDialog().
Member Data Documentation
closeButton_
QPushButton* InfoDialog::closeButton_ private
Referenced by InfoDialog().
defaultHeight_
int InfoDialog::defaultHeight_ private
Referenced by minimumSizeHint(), and sizeHint().
defaultWidth_
int InfoDialog::defaultWidth_ private
Referenced by minimumSizeHint(), and sizeHint().
textEdit_
QTextEdit* InfoDialog::textEdit_ private
Referenced by InfoDialog(), and setText().
The documentation for this class was generated from the following files:
InfoDialog.hpp
InfoDialog.cpp