3D Forest: TreeTableWidget Class Reference
TreeTableWidget Class Reference
#include <TreeTableWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
Public Member Functions
TreeTableWidget (MainWindow *mainWindow)
QSize sizeHint () const override
Protected Slots
void slotExport ()
Private Types
enum Column {
COLUMN_ID , COLUMN_LABEL , COLUMN_X , COLUMN_Y ,
COLUMN_Z , COLUMN_HEIGHT , COLUMN_DBH , COLUMN_STATUS ,
COLUMN_LAST
}
Private Member Functions
void setSegments (const Segments &segments)
void setRow (size_t index)
void setCell (int row, int col, size_t value)
void setCell (int row, int col, double value)
void setCell (int row, int col, const std::string &value)
void block ()
void unblock ()
Private Attributes
MainWindow * mainWindow_
QTableWidget * tableWidget_
QPushButton * exportButton_
Segments segments_
QString fileName_
Member Enumeration Documentation
Column
enum TreeTableWidget::Column private
Tree Table Column.
Enumerator
COLUMN_ID
COLUMN_LABEL
COLUMN_X
COLUMN_Y
COLUMN_Z
COLUMN_HEIGHT
COLUMN_DBH
COLUMN_STATUS
COLUMN_LAST
Constructor & Destructor Documentation
TreeTableWidget()
TreeTableWidget::TreeTableWidget (MainWindow * mainWindow)
Member Function Documentation
block()
void TreeTableWidget::block () private
Referenced by setSegments().
setCell() [1/3]
void TreeTableWidget::setCell (int row, int col, const std::string & value) private
setCell() [2/3]
void TreeTableWidget::setCell (int row, int col, double value) private
setCell() [3/3]
void TreeTableWidget::setCell (int row, int col, size_t value) private
Referenced by setCell(), setCell(), and setRow().
setRow()
void TreeTableWidget::setRow (size_t index) private
Referenced by setSegments().
setSegments()
void TreeTableWidget::setSegments (const Segments & segments) private
Referenced by slotUpdate().
sizeHint()
QSize TreeTableWidget::sizeHint () const inline override
slotExport
void TreeTableWidget::slotExport () protected slot
Referenced by TreeTableWidget().
slotUpdate
void TreeTableWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by TreeTableWidget().
unblock()
void TreeTableWidget::unblock () private
Referenced by setSegments().
Member Data Documentation
exportButton_
QPushButton* TreeTableWidget::exportButton_ private
Referenced by TreeTableWidget().
fileName_
QString TreeTableWidget::fileName_ private
Referenced by slotExport().
mainWindow_
MainWindow* TreeTableWidget::mainWindow_ private
Referenced by setRow(), slotExport(), slotUpdate(), and TreeTableWidget().
segments_
Segments TreeTableWidget::segments_ private
Referenced by setCell(), setRow(), setSegments(), and slotExport().
tableWidget_
QTableWidget* TreeTableWidget::tableWidget_ private
Referenced by setCell(), setSegments(), and TreeTableWidget().
The documentation for this class was generated from the following files:
TreeTableWidget.hpp
TreeTableWidget.cpp