3D Forest: ExplorerFilesWidget Class Reference
ExplorerFilesWidget Class Reference
#include <ExplorerFilesWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ExplorerFilesWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_DATE_CREATED ,
COLUMN_LAST
}
Protected Member Functions
void setDatasets (const Datasets &datasets, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Datasets datasets_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ExplorerFilesWidget::Column protected
Explorer Files Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_DATE_CREATED
COLUMN_LAST
Constructor & Destructor Documentation
ExplorerFilesWidget()
ExplorerFilesWidget::ExplorerFilesWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ExplorerFilesWidget::addTreeItem (size_t index) protected
Referenced by setDatasets().
block()
void ExplorerFilesWidget::block () protected
Referenced by setDatasets(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ExplorerFilesWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
dataChanged()
void ExplorerFilesWidget::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ExplorerFilesWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ExplorerFilesWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerFilesWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
identifier()
size_t ExplorerFilesWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
index()
size_t ExplorerFilesWidget::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), and slotDelete().
isFilterEnabled()
bool ExplorerFilesWidget::isFilterEnabled () const virtual
Reimplemented from ExplorerWidgetInterface.
setDatasets()
void ExplorerFilesWidget::setDatasets (const Datasets & datasets, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
setFilterEnabled()
void ExplorerFilesWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
slotAdd
void ExplorerFilesWidget::slotAdd () slot
Referenced by ExplorerFilesWidget().
slotDelete
void ExplorerFilesWidget::slotDelete () slot
Referenced by ExplorerFilesWidget().
slotHide
void ExplorerFilesWidget::slotHide () slot
Referenced by ExplorerFilesWidget().
slotItemChanged
void ExplorerFilesWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ExplorerFilesWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ExplorerFilesWidget::slotSelectAll () slot
Referenced by ExplorerFilesWidget().
slotSelectInvert
void ExplorerFilesWidget::slotSelectInvert () slot
Referenced by ExplorerFilesWidget().
slotSelectNone
void ExplorerFilesWidget::slotSelectNone () slot
Referenced by ExplorerFilesWidget(), and slotDelete().
slotShow
void ExplorerFilesWidget::slotShow () slot
Referenced by ExplorerFilesWidget().
slotUpdate
void ExplorerFilesWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerFilesWidget().
unblock()
void ExplorerFilesWidget::unblock () protected
Referenced by setDatasets(), and updateTree().
updateTree()
void ExplorerFilesWidget::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ExplorerFilesWidget::addButton_ protected
Referenced by ExplorerFilesWidget().
datasets_
Datasets ExplorerFilesWidget::datasets_ protected
Referenced by addTreeItem(), dataChanged(), index(), setDatasets(), and slotDelete().
deleteButton_
QToolButton* ExplorerFilesWidget::deleteButton_ protected
Referenced by ExplorerFilesWidget(), and slotItemSelectionChanged().
filter_
QueryFilterSet ExplorerFilesWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setDatasets(), setFilterEnabled(), slotDelete(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ExplorerFilesWidget::hideButton_ protected
Referenced by ExplorerFilesWidget(), and slotItemSelectionChanged().
selectAllButton_
QToolButton* ExplorerFilesWidget::selectAllButton_ protected
Referenced by ExplorerFilesWidget().
selectInvertButton_
QToolButton* ExplorerFilesWidget::selectInvertButton_ protected
Referenced by ExplorerFilesWidget().
selectNoneButton_
QToolButton* ExplorerFilesWidget::selectNoneButton_ protected
Referenced by ExplorerFilesWidget().
showButton_
QToolButton* ExplorerFilesWidget::showButton_ protected
Referenced by ExplorerFilesWidget(), and slotItemSelectionChanged().
tree_
QTreeWidget* ExplorerFilesWidget::tree_ protected
Referenced by addTreeItem(), block(), ExplorerFilesWidget(), setDatasets(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ExplorerFilesWidget::updatesEnabled_ protected
Referenced by ExplorerFilesWidget(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ExplorerFilesWidget.hpp
ExplorerFilesWidget.cpp