3D Forest: Settings Class Reference
Settings Class Reference
#include <Settings.hpp>
Public Member Functions
const SettingsView & view () const
const SettingsUnits & units () const
void view (const SettingsView &view)
bool units (const SettingsUnits &units)
Protected Attributes
SettingsView view_
SettingsUnits units_
Friends
void fromJson (Settings &out, const Json &in)
void toJson (Json &out, const Settings &in)
std::string toString (const Settings &in)
Member Function Documentation
units() [1/2]
const SettingsUnits & Settings::units () const inline
Referenced by TreeTableExportDialog::properties(), FilterElevationWidget::setElevation(), FilterAreaBoxWidget::setRegion(), TreeTableWidget::setRow(), FilterTreesTreeWidget::setSegment(), Editor::setSettingsUnits(), FilterAreaBoxWidget::slotRangeIntermediateMaximumValue(), FilterElevationWidget::slotRangeIntermediateMaximumValue(), FilterAreaBoxWidget::slotRangeIntermediateMinimumValue(), FilterElevationWidget::slotRangeIntermediateMinimumValue(), SettingsUnitsWidget::slotUpdate(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), ComputeElevationAction::start(), units(), and Editor::updateAfterRead().
units() [2/2]
bool Settings::units (const SettingsUnits & units)
view() [1/2]
const SettingsView & Settings::view () const inline
Referenced by ViewerOpenGLViewport::renderAttributes(), ViewerOpenGLViewport::renderFirstFrame(), ViewerOpenGLViewport::renderSceneSettingsDisable(), ViewerOpenGLViewport::renderSceneSettingsEnable(), Page::runColorModifier(), Editor::setSettingsView(), SettingsViewWidget::slotUpdate(), and view().
view() [2/2]
void Settings::view (const SettingsView & view)
Friends And Related Symbol Documentation
fromJson
void fromJson (Settings & out, const Json & in) friend
toJson
void toJson (Json & out, const Settings & in) friend
toString
std::string toString (const Settings & in) friend
Member Data Documentation
units_
SettingsUnits Settings::units_ protected
Referenced by units().
view_
SettingsView Settings::view_ protected
Referenced by view().
The documentation for this class was generated from the following files:
Settings.hpp
Settings.cpp