3D Forest: Segments Class Reference
Segments Class Reference
#include <Segments.hpp>
Public Member Functions
Segments ()
void clear ()
void setDefault ()
size_t size () const
Segment & operator[] (size_t index)
const Segment & operator[] (size_t index) const
void push_back (const Segment &segment)
void erase (size_t pos)
size_t id (size_t pos) const
size_t index (size_t id) const
bool contains (size_t id) const
size_t unusedId () const
Protected Attributes
std::vector< Segment > segments_
std::unordered_map< size_t, size_t > hashTableId_
Friends
void fromJson (Segments &out, const Json &in)
void toJson (Json &out, const Segments &in)
Constructor & Destructor Documentation
Segments()
Segments::Segments ()
Member Function Documentation
clear()
void Segments::clear ()
Referenced by TreeTableWidget::setSegments().
contains()
bool Segments::contains (size_t id) const inline
Referenced by Page::queryWhereSegment().
erase()
void Segments::erase (size_t pos)
Referenced by FilterTreesWidget::slotDelete().
id()
size_t Segments::id (size_t pos) const inline
Referenced by FilterTreesWidget::addTreeItem(), erase(), push_back(), and setDefault().
index()
size_t Segments::index (size_t id) const inline
Referenced by FilterTreesWidget::index(), FilterTreesWidget::slotItemClicked(), and ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes().
operator[]() [1/2]
Segment & Segments::operator[] (size_t index) inline
operator[]() [2/2]
const Segment & Segments::operator[] (size_t index) const inline
push_back()
void Segments::push_back (const Segment & segment)
Referenced by ComputeSegmentationNNAction::stepCreateSegments().
setDefault()
void Segments::setDefault ()
Referenced by Editor::close(), Segments(), ComputeSegmentationNNAction::stepCreateSegments(), and ComputeSegmentationNNAction::stepResetPoints().
size()
size_t Segments::size () const inline
Referenced by ViewerOpenGLViewport::renderAttributes(), ViewerOpenGLViewport::renderSegments(), Page::runColorModifier(), TreeTableWidget::setSegments(), FilterTreesWidget::setSegments(), TreeTableWidget::slotExport(), FilterTreesWidget::slotItemClicked(), FilterTreesWidget::slotItemSelectionChanged(), ComputeTreeAttributesAction::stepPointsToTrees(), and Editor::updateAfterRead().
unusedId()
size_t Segments::unusedId () const
Friends And Related Symbol Documentation
fromJson
void fromJson (Segments & out, const Json & in) friend
toJson
void toJson (Json & out, const Segments & in) friend
Member Data Documentation
hashTableId_
std::unordered_map<size_t, size_t> Segments::hashTableId_ protected
Referenced by clear(), erase(), push_back(), setDefault(), and unusedId().
segments_
std::vector<Segment> Segments::segments_ protected
Referenced by clear(), erase(), push_back(), and setDefault().
The documentation for this class was generated from the following files:
Segments.hpp
Segments.cpp