3D Forest: ProjectNavigatorItemDescriptor Class Reference
ProjectNavigatorItemDescriptor Class Reference
#include <ProjectNavigatorItemDescriptor.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
ProjectNavigatorItemDescriptor (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void descriptorInputChanged ()
Protected Attributes
RangeSliderWidget * descriptorInput_
Range< float > descriptorRange_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ProjectNavigatorItemDescriptor()
ProjectNavigatorItemDescriptor::ProjectNavigatorItemDescriptor (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemDescriptor::colorSource () const inline virtual
Implements ProjectNavigatorItem.
descriptorInputChanged()
void ProjectNavigatorItemDescriptor::descriptorInputChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ProjectNavigatorItemDescriptor::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemDescriptor::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
isFilterEnabled()
bool ProjectNavigatorItemDescriptor::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setFilterEnabled()
void ProjectNavigatorItemDescriptor::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotRangeIntermediateMaximumValue
void ProjectNavigatorItemDescriptor::slotRangeIntermediateMaximumValue () slot
Referenced by ProjectNavigatorItemDescriptor().
slotRangeIntermediateMinimumValue
void ProjectNavigatorItemDescriptor::slotRangeIntermediateMinimumValue () slot
Referenced by ProjectNavigatorItemDescriptor().
slotUpdate
void ProjectNavigatorItemDescriptor::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemDescriptor().
Member Data Documentation
descriptorInput_
RangeSliderWidget* ProjectNavigatorItemDescriptor::descriptorInput_ protected
Referenced by ProjectNavigatorItemDescriptor(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
descriptorRange_
Range<float> ProjectNavigatorItemDescriptor::descriptorRange_ protected
Referenced by descriptorInputChanged(), isFilterEnabled(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
The documentation for this class was generated from the following files:
ProjectNavigatorItemDescriptor.hpp
ProjectNavigatorItemDescriptor.cpp