3D Forest: ComputeHeightMapModifier Class Reference
ComputeHeightMapModifier Class Reference
#include <ComputeHeightMapModifier.hpp>
Public Types
enum Source { SOURCE_Z_POSITION , SOURCE_ELEVATION }
Public Member Functions
ComputeHeightMapModifier ()
void initialize (MainWindow *mainWindow)
void setSource (Source source)
void setColormap (const QString &name, int colorCount)
void setPreviewEnabled (bool enabled, bool update=true, bool reload=false)
bool previewEnabled ()
void applyModifier (Page *page)
void apply (QWidget *widget)
Protected Member Functions
std::vector< Vector3< double > > createColormap (const QString &name, int colorCount)
Protected Attributes
MainWindow * mainWindow_
Editor * editor_
bool previewEnabled_
Source source_
std::vector< Vector3< double > > colormap_
QMutex mutex_
Detailed Description
This class represents Compute Height Map model.
An instance of this class is shared memory resource between main window GUI thread and editor thread. Most of the code must not be run by multiple threads at once. A mutex is used to protect concurrent read/write access to shared memory.
Member Enumeration Documentation
Source
enum ComputeHeightMapModifier::Source
Compute Height Map Modifier Source.
Enumerator
SOURCE_Z_POSITION
SOURCE_ELEVATION
Constructor & Destructor Documentation
ComputeHeightMapModifier()
ComputeHeightMapModifier::ComputeHeightMapModifier ()
Member Function Documentation
apply()
void ComputeHeightMapModifier::apply (QWidget * widget)
Referenced by ComputeHeightMapWidget::apply().
applyModifier()
void ComputeHeightMapModifier::applyModifier (Page * page)
Referenced by ComputeHeightMapPlugin::applyModifier().
createColormap()
std::vector< Vector3< double > > ComputeHeightMapModifier::createColormap (const QString & name, int colorCount) protected
Referenced by initialize(), and setColormap().
initialize()
void ComputeHeightMapModifier::initialize (MainWindow * mainWindow)
Referenced by ComputeHeightMapPlugin::initialize().
previewEnabled()
bool ComputeHeightMapModifier::previewEnabled ()
Referenced by ComputeHeightMapPlugin::modifierEnabled(), setColormap(), and setSource().
setColormap()
void ComputeHeightMapModifier::setColormap (const QString & name, int colorCount)
Referenced by ComputeHeightMapWidget::colorCountChanged(), and ComputeHeightMapWidget::colormapChanged().
setPreviewEnabled()
void ComputeHeightMapModifier::setPreviewEnabled (bool enabled, bool update = true, bool reload = false)
Referenced by ComputeHeightMapWidget::apply(), ComputeHeightMapWidget::closeModifier(), ComputeHeightMapWidget::previewChanged(), setColormap(), and setSource().
setSource()
void ComputeHeightMapModifier::setSource (Source source)
Referenced by ComputeHeightMapWidget::sourceChanged().
Member Data Documentation
colormap_
std::vector<Vector3<double> > ComputeHeightMapModifier::colormap_ protected
Referenced by applyModifier(), initialize(), and setColormap().
editor_
Editor* ComputeHeightMapModifier::editor_ protected
Referenced by apply(), applyModifier(), initialize(), and setPreviewEnabled().
mainWindow_
MainWindow* ComputeHeightMapModifier::mainWindow_ protected
Referenced by apply(), initialize(), and setPreviewEnabled().
mutex_
QMutex ComputeHeightMapModifier::mutex_ protected
Referenced by applyModifier(), previewEnabled(), setColormap(), setPreviewEnabled(), and setSource().
previewEnabled_
bool ComputeHeightMapModifier::previewEnabled_ protected
Referenced by previewEnabled(), setColormap(), setPreviewEnabled(), and setSource().
source_
Source ComputeHeightMapModifier::source_ protected
Referenced by applyModifier(), and setSource().
The documentation for this class was generated from the following files:
ComputeHeightMapModifier.hpp
ComputeHeightMapModifier.cpp