3D Forest: ProjectNavigatorItemLayers Class Reference
ProjectNavigatorItemLayers Class Reference
#include <ProjectNavigatorItemLayers.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ProjectNavigatorItemLayers (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
void setLayers (const Layers &layers)
Protected Attributes
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Layers layers_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ProjectNavigatorItemLayers::Column protected
Project Navigator Layers Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorItemLayers()
ProjectNavigatorItemLayers::ProjectNavigatorItemLayers (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ProjectNavigatorItemLayers::addTreeItem (size_t index) protected
Referenced by setLayers().
block()
void ProjectNavigatorItemLayers::block () protected
Referenced by setLayers(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemLayers::colorSource () const inline virtual
Implements ProjectNavigatorItem.
dataChanged()
void ProjectNavigatorItemLayers::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ProjectNavigatorItemLayers::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ProjectNavigatorItemLayers::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemLayers::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
identifier()
size_t ProjectNavigatorItemLayers::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
index()
size_t ProjectNavigatorItemLayers::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), and slotDelete().
isFilterEnabled()
bool ProjectNavigatorItemLayers::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setFilterEnabled()
void ProjectNavigatorItemLayers::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
setLayers()
void ProjectNavigatorItemLayers::setLayers (const Layers & layers) protected
Referenced by slotUpdate().
slotAdd
void ProjectNavigatorItemLayers::slotAdd () slot
Referenced by ProjectNavigatorItemLayers().
slotDelete
void ProjectNavigatorItemLayers::slotDelete () slot
Referenced by ProjectNavigatorItemLayers().
slotHide
void ProjectNavigatorItemLayers::slotHide () slot
Referenced by ProjectNavigatorItemLayers().
slotItemChanged
void ProjectNavigatorItemLayers::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorItemLayers::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorItemLayers::slotSelectAll () slot
Referenced by ProjectNavigatorItemLayers().
slotSelectInvert
void ProjectNavigatorItemLayers::slotSelectInvert () slot
Referenced by ProjectNavigatorItemLayers().
slotSelectNone
void ProjectNavigatorItemLayers::slotSelectNone () slot
Referenced by ProjectNavigatorItemLayers(), and slotDelete().
slotShow
void ProjectNavigatorItemLayers::slotShow () slot
Referenced by ProjectNavigatorItemLayers().
slotUpdate
void ProjectNavigatorItemLayers::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemLayers().
unblock()
void ProjectNavigatorItemLayers::unblock () protected
Referenced by setLayers(), and updateTree().
updateTree()
void ProjectNavigatorItemLayers::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ProjectNavigatorItemLayers::addButton_ protected
Referenced by ProjectNavigatorItemLayers().
deleteButton_
QToolButton* ProjectNavigatorItemLayers::deleteButton_ protected
Referenced by ProjectNavigatorItemLayers(), and slotItemSelectionChanged().
filter_
QueryFilterSet ProjectNavigatorItemLayers::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setFilterEnabled(), slotDelete(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ProjectNavigatorItemLayers::hideButton_ protected
Referenced by ProjectNavigatorItemLayers(), and slotItemSelectionChanged().
layers_
Layers ProjectNavigatorItemLayers::layers_ protected
Referenced by addTreeItem(), dataChanged(), index(), setLayers(), and slotDelete().
selectAllButton_
QToolButton* ProjectNavigatorItemLayers::selectAllButton_ protected
Referenced by ProjectNavigatorItemLayers().
selectInvertButton_
QToolButton* ProjectNavigatorItemLayers::selectInvertButton_ protected
Referenced by ProjectNavigatorItemLayers().
selectNoneButton_
QToolButton* ProjectNavigatorItemLayers::selectNoneButton_ protected
Referenced by ProjectNavigatorItemLayers().
showButton_
QToolButton* ProjectNavigatorItemLayers::showButton_ protected
Referenced by ProjectNavigatorItemLayers(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorItemLayers::tree_ protected
Referenced by addTreeItem(), block(), ProjectNavigatorItemLayers(), setLayers(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ProjectNavigatorItemLayers::updatesEnabled_ protected
Referenced by ProjectNavigatorItemLayers(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ProjectNavigatorItemLayers.hpp
ProjectNavigatorItemLayers.cpp