3D Forest: ProgressCounter Class Reference
ProgressCounter Class Reference
#include <ProgressCounter.hpp>
Public Member Functions
ProgressCounter ()
~ProgressCounter ()=default
void setMaximumStep (uint64_t n=npos, uint64_t interleave=1, double timeout=0.25)
uint64_t maximumStep () const
void setValueStep (uint64_t n)
void addValueStep (uint64_t n)
uint64_t valueStep () const
void setMaximumSteps (size_t n)
void setMaximumSteps (const std::vector< double > &percent)
size_t maximumSteps () const
void setValueSteps (size_t n)
size_t valueSteps () const
void startTimer ()
bool timedOut ()
bool end () const
double percent () const
int percentToInt () const
bool initializing () const
Static Public Attributes
static const uint64_t npos = UINT64_MAX
Private Member Functions
double percentStep () const
Private Attributes
size_t maximumSteps_
size_t valueSteps_
std::vector< double > percentSteps_
uint64_t maximumStep_
uint64_t valueStep_
double timeout_
double timeBegin_
double timeNow_
uint64_t interleave_
uint64_t interleaveCounter_
Constructor & Destructor Documentation
ProgressCounter()
ProgressCounter::ProgressCounter ()
~ProgressCounter()
ProgressCounter::~ProgressCounter () default
Member Function Documentation
addValueStep()
void ProgressCounter::addValueStep (uint64_t n) inline
Referenced by ExportFileAction::next(), ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeClassificationAction::stepClassifyGround(), ComputeDescriptorAction::stepCompute(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), ComputeClassificationAction::stepVoxelsToPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
end()
bool ProgressCounter::end () const inline
initializing()
bool ProgressCounter::initializing () const inline
Referenced by ExportFileAction::next().
maximumStep()
uint64_t ProgressCounter::maximumStep () const inline
Referenced by ExportFileAction::next(), ComputeElevationAction::stepComputeElevation(), ComputeSegmentationNNAction::stepCreateSegments(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes(), and ComputeClassificationAction::stepVoxelsToPoints().
maximumSteps()
size_t ProgressCounter::maximumSteps () const inline
Referenced by ComputeElevationAction::stepComputeElevation(), ComputeSegmentationNNAction::stepCreateSegments(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes(), and ComputeClassificationAction::stepVoxelsToPoints().
percent()
double ProgressCounter::percent () const
Referenced by setMaximumSteps().
percentStep()
double ProgressCounter::percentStep () const private
Referenced by percent().
percentToInt()
int ProgressCounter::percentToInt () const inline
setMaximumStep()
void ProgressCounter::setMaximumStep (uint64_t n = npos, uint64_t interleave = 1, double timeout = 0.25)
Referenced by ExportFileAction::determineMaximum(), ExportFileAction::initialize(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), ComputeElevationAction::start(), ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeClassificationAction::stepClassifyGround(), ComputeDescriptorAction::stepCompute(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeElevationAction::stepCreateIndex(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeClassificationAction::stepCreateVoxelIndex(), ComputeSegmentationNNAction::stepCreateVoxelIndex(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
setMaximumSteps() [1/2]
void ProgressCounter::setMaximumSteps (const std::vector< double > & percent)
setMaximumSteps() [2/2]
void ProgressCounter::setMaximumSteps (size_t n)
Referenced by ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), and ComputeElevationAction::start().
setValueStep()
void ProgressCounter::setValueStep (uint64_t n) inline
Referenced by ExportFileAction::next(), ComputeElevationAction::stepComputeElevation(), ComputeSegmentationNNAction::stepCreateSegments(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes(), and ComputeClassificationAction::stepVoxelsToPoints().
setValueSteps()
void ProgressCounter::setValueSteps (size_t n) inline
Referenced by ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), ComputeElevationAction::start(), ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeClassificationAction::stepClassifyGround(), ComputeDescriptorAction::stepCompute(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeElevationAction::stepCreateIndex(), ComputeSegmentationNNAction::stepCreateSegments(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeClassificationAction::stepCreateVoxelIndex(), ComputeSegmentationNNAction::stepCreateVoxelIndex(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes(), ComputeClassificationAction::stepVoxelsToPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
startTimer()
void ProgressCounter::startTimer ()
Referenced by ExportFileAction::determineMaximum(), ExportFileAction::next(), ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeClassificationAction::stepClassifyGround(), ComputeDescriptorAction::stepCompute(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), ComputeClassificationAction::stepVoxelsToPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
timedOut()
bool ProgressCounter::timedOut ()
Referenced by ExportFileAction::determineMaximum(), ExportFileAction::next(), ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeDescriptorAction::stepCompute(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeDescriptorAction::stepNormalize(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), ComputeClassificationAction::stepVoxelsToPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
valueStep()
uint64_t ProgressCounter::valueStep () const inline
Referenced by ComputeTreeAttributesAction::stepCalculateComputeTreeAttributes(), ComputeClassificationAction::stepClassifyGround(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeElevationAction::stepCreateGround(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeTreeAttributesAction::stepPointsToTrees(), ComputeClassificationAction::stepResetPoints(), ComputeDescriptorAction::stepResetPoints(), ComputeElevationAction::stepResetPoints(), ComputeSegmentationNNAction::stepResetPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
valueSteps()
size_t ProgressCounter::valueSteps () const inline
Referenced by ComputeClassificationAction::next(), ComputeDescriptorAction::next(), ComputeElevationAction::next(), ComputeSegmentationNNAction::next(), and ComputeTreeAttributesAction::next().
Member Data Documentation
interleave_
uint64_t ProgressCounter::interleave_ private
Referenced by setMaximumStep(), and timedOut().
interleaveCounter_
uint64_t ProgressCounter::interleaveCounter_ private
Referenced by setMaximumStep(), and timedOut().
maximumStep_
uint64_t ProgressCounter::maximumStep_ private
Referenced by percent(), percentStep(), and setMaximumStep().
maximumSteps_
size_t ProgressCounter::maximumSteps_ private
Referenced by percent(), setMaximumSteps(), and setMaximumSteps().
npos
const uint64_t ProgressCounter::npos = UINT64_MAX static
Referenced by ExportFileAction::initialize(), percentStep(), ComputeTreeAttributesAction::start(), and ProgressDialog::updateLabels().
percentSteps_
std::vector<double> ProgressCounter::percentSteps_ private
Referenced by percent(), setMaximumSteps(), and setMaximumSteps().
timeBegin_
double ProgressCounter::timeBegin_ private
Referenced by setMaximumStep(), startTimer(), and timedOut().
timeNow_
double ProgressCounter::timeNow_ private
Referenced by setMaximumStep(), and timedOut().
timeout_
double ProgressCounter::timeout_ private
Referenced by setMaximumStep(), and timedOut().
valueStep_
uint64_t ProgressCounter::valueStep_ private
Referenced by percent(), percentStep(), and setMaximumStep().
valueSteps_
size_t ProgressCounter::valueSteps_ private
Referenced by percent(), setMaximumSteps(), and setMaximumSteps().
The documentation for this class was generated from the following files:
ProgressCounter.hpp
ProgressCounter.cpp