3D Forest: DescriptorPca Class Reference
DescriptorPca Class Reference
#include <DescriptorPca.hpp>
Public Member Functions
DescriptorPca ()
void clear ()
bool computeDescriptor (Query &query, const Box< double > &cell, double &meanX, double &meanY, double &meanZ, float &descriptor)
bool computeDescriptor (Query &query, double x, double y, double z, double radius, double &meanX, double &meanY, double &meanZ, float &descriptor)
bool computeDescriptor (Eigen::MatrixXd &V, double &meanX, double &meanY, double &meanZ, float &descriptor)
bool computeDistribution (Query &query, double x, double y, double z, double radius, float &descriptor)
Private Attributes
Eigen::MatrixXd xyz
Eigen::Matrix3d product
Eigen::Matrix3d eigenVectors
Eigen::Matrix3d eigenVectorsT
Eigen::Vector3d in
Eigen::Vector3d out
Eigen::Vector3d min
Eigen::Vector3d max
Eigen::SelfAdjointEigenSolver< Eigen::Matrix3d > E
Constructor & Destructor Documentation
DescriptorPca()
DescriptorPca::DescriptorPca ()
Member Function Documentation
clear()
void DescriptorPca::clear ()
Referenced by DescriptorAction::clear(), and DescriptorPca().
computeDescriptor() [1/3]
bool DescriptorPca::computeDescriptor (Eigen::MatrixXd & V, double & meanX, double & meanY, double & meanZ, float & descriptor)
computeDescriptor() [2/3]
bool DescriptorPca::computeDescriptor (Query & query, const Box< double > & cell, double & meanX, double & meanY, double & meanZ, float & descriptor)
Referenced by computeDescriptor(), and DescriptorAction::stepComputeDescriptor().
computeDescriptor() [3/3]
bool DescriptorPca::computeDescriptor (Query & query, double x, double y, double z, double radius, double & meanX, double & meanY, double & meanZ, float & descriptor)
computeDistribution()
bool DescriptorPca::computeDistribution (Query & query, double x, double y, double z, double radius, float & descriptor)
Referenced by DescriptorAction::stepComputeDescriptor().
Member Data Documentation
E
Eigen::SelfAdjointEigenSolver<Eigen::Matrix3d> DescriptorPca::E private
Referenced by computeDescriptor().
eigenVectors
Eigen::Matrix3d DescriptorPca::eigenVectors private
Referenced by computeDescriptor().
eigenVectorsT
Eigen::Matrix3d DescriptorPca::eigenVectorsT private
Referenced by computeDescriptor().
in
Eigen::Vector3d DescriptorPca::in private
Referenced by computeDescriptor().
max
Eigen::Vector3d DescriptorPca::max private
Referenced by computeDescriptor().
min
Eigen::Vector3d DescriptorPca::min private
Referenced by computeDescriptor().
out
Eigen::Vector3d DescriptorPca::out private
Referenced by computeDescriptor().
product
Eigen::Matrix3d DescriptorPca::product private
Referenced by computeDescriptor().
xyz
Eigen::MatrixXd DescriptorPca::xyz private
Referenced by clear(), and computeDescriptor().
The documentation for this class was generated from the following files:
DescriptorPca.hpp
DescriptorPca.cpp