3D Forest: FilterTreesWidget Class Reference
FilterTreesWidget Class Reference
#include <FilterTreesWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemClicked (QTreeWidgetItem *item, int column)
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
FilterTreesWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void setSegments (const Segments &segments, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
QSplitter * splitter_
FilterTreesTreeWidget * treeWidget_
Segments segments_
QueryFilterSet filter_
bool updatesEnabled_
Member Enumeration Documentation
Column
enum FilterTreesWidget::Column protected
Filter Trees Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
FilterTreesWidget()
FilterTreesWidget::FilterTreesWidget (MainWindow * mainWindow)
Member Function Documentation
addTreeItem()
void FilterTreesWidget::addTreeItem (size_t index) protected
Referenced by setSegments().
block()
void FilterTreesWidget::block () protected
Referenced by setSegments(), and updateTree().
dataChanged()
void FilterTreesWidget::dataChanged () protected
Referenced by slotDelete(), slotItemClicked(), and slotItemSelectionChanged().
filterChanged()
void FilterTreesWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemClicked(), and slotShow().
identifier()
size_t FilterTreesWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemClicked(), and updateTree().
index()
size_t FilterTreesWidget::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), slotDelete(), slotHide(), slotItemClicked(), and slotShow().
setFilterEnabled()
void FilterTreesWidget::setFilterEnabled (bool b)
Referenced by FilterTreesWindow::closeEvent(), and FilterTreesWindow::showEvent().
setSegments()
void FilterTreesWidget::setSegments (const Segments & segments, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
sizeHint()
QSize FilterTreesWidget::sizeHint () const inline override
slotAdd
void FilterTreesWidget::slotAdd () slot
Referenced by FilterTreesWidget().
slotDelete
void FilterTreesWidget::slotDelete () slot
Referenced by FilterTreesWidget().
slotHide
void FilterTreesWidget::slotHide () slot
Referenced by FilterTreesWidget().
slotItemChanged
void FilterTreesWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemClicked
void FilterTreesWidget::slotItemClicked (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void FilterTreesWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void FilterTreesWidget::slotSelectAll () slot
Referenced by FilterTreesWidget().
slotSelectInvert
void FilterTreesWidget::slotSelectInvert () slot
Referenced by FilterTreesWidget().
slotSelectNone
void FilterTreesWidget::slotSelectNone () slot
Referenced by FilterTreesWidget(), and slotDelete().
slotShow
void FilterTreesWidget::slotShow () slot
Referenced by FilterTreesWidget().
slotUpdate
void FilterTreesWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterTreesWidget().
unblock()
void FilterTreesWidget::unblock () protected
Referenced by setSegments(), and updateTree().
updateTree()
void FilterTreesWidget::updateTree () protected
Member Data Documentation
addButton_
QToolButton* FilterTreesWidget::addButton_ protected
Referenced by FilterTreesWidget().
deleteButton_
QToolButton* FilterTreesWidget::deleteButton_ protected
Referenced by FilterTreesWidget(), and slotItemSelectionChanged().
filter_
QueryFilterSet FilterTreesWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), setFilterEnabled(), setSegments(), slotDelete(), slotHide(), slotItemClicked(), slotShow(), and updateTree().
hideButton_
QToolButton* FilterTreesWidget::hideButton_ protected
Referenced by FilterTreesWidget(), and slotItemSelectionChanged().
mainWindow_
MainWindow* FilterTreesWidget::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), FilterTreesWidget(), and slotUpdate().
segments_
Segments FilterTreesWidget::segments_ protected
Referenced by addTreeItem(), dataChanged(), index(), setSegments(), slotDelete(), slotItemClicked(), and slotItemSelectionChanged().
selectAllButton_
QToolButton* FilterTreesWidget::selectAllButton_ protected
Referenced by FilterTreesWidget().
selectInvertButton_
QToolButton* FilterTreesWidget::selectInvertButton_ protected
Referenced by FilterTreesWidget().
selectNoneButton_
QToolButton* FilterTreesWidget::selectNoneButton_ protected
Referenced by FilterTreesWidget().
showButton_
QToolButton* FilterTreesWidget::showButton_ protected
Referenced by FilterTreesWidget(), and slotItemSelectionChanged().
splitter_
QSplitter* FilterTreesWidget::splitter_ protected
Referenced by FilterTreesWidget().
tree_
QTreeWidget* FilterTreesWidget::tree_ protected
Referenced by addTreeItem(), block(), FilterTreesWidget(), setSegments(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
treeWidget_
FilterTreesTreeWidget* FilterTreesWidget::treeWidget_ protected
Referenced by FilterTreesWidget(), setSegments(), and slotItemClicked().
updatesEnabled_
bool FilterTreesWidget::updatesEnabled_ protected
Referenced by FilterTreesWidget(), slotHide(), slotItemClicked(), slotItemSelectionChanged(), and slotShow().
The documentation for this class was generated from the following files:
FilterTreesWidget.hpp
FilterTreesWidget.cpp