3D Forest: HeightMapModifier Class Reference
HeightMapModifier Class Reference
#include <HeightMapModifier.hpp>
Public Types
enum Source { SOURCE_Z_POSITION , SOURCE_ELEVATION }
Public Member Functions
HeightMapModifier ()
void initialize (MainWindow *mainWindow)
void setSource (Source source)
void setColormap (const QString &name, int colorCount)
void setPreviewEnabled (bool enabled, bool update=true, bool reload=false)
bool isPreviewEnabled ()
void applyModifier (Page *page)
void apply (QWidget *widget)
Protected Member Functions
std::vector< Vector3< double > > createColormap (const QString &name, int colorCount)
Protected Attributes
MainWindow * mainWindow_
Editor * editor_
bool previewEnabled_
Source source_
std::vector< Vector3< double > > colormap_
QMutex mutex_
Detailed Description
This class represents Height Map model.
An instance of this class is shared memory resource between main window GUI thread and editor thread. Most of the code must not be run by multiple threads at once. A mutex is used to protect concurrent read/write access to shared memory.
Member Enumeration Documentation
Source
enum HeightMapModifier::Source
Height Map Modifier Source.
Enumerator
SOURCE_Z_POSITION
SOURCE_ELEVATION
Constructor & Destructor Documentation
HeightMapModifier()
HeightMapModifier::HeightMapModifier ()
Member Function Documentation
apply()
void HeightMapModifier::apply (QWidget * widget)
Referenced by HeightMapWidget::apply().
applyModifier()
void HeightMapModifier::applyModifier (Page * page)
Referenced by HeightMapPlugin::applyModifier().
createColormap()
std::vector< Vector3< double > > HeightMapModifier::createColormap (const QString & name, int colorCount) protected
Referenced by initialize(), and setColormap().
initialize()
void HeightMapModifier::initialize (MainWindow * mainWindow)
Referenced by HeightMapPlugin::initialize().
isPreviewEnabled()
bool HeightMapModifier::isPreviewEnabled ()
Referenced by HeightMapPlugin::isModifierEnabled().
setColormap()
void HeightMapModifier::setColormap (const QString & name, int colorCount)
Referenced by HeightMapWidget::colorCountChanged(), and HeightMapWidget::colormapChanged().
setPreviewEnabled()
void HeightMapModifier::setPreviewEnabled (bool enabled, bool update = true, bool reload = false)
Referenced by HeightMapWidget::apply(), HeightMapWidget::closeModifier(), HeightMapWidget::previewChanged(), setColormap(), and setSource().
setSource()
void HeightMapModifier::setSource (Source source)
Referenced by HeightMapWidget::sourceChanged().
Member Data Documentation
colormap_
std::vector<Vector3<double> > HeightMapModifier::colormap_ protected
Referenced by applyModifier(), initialize(), and setColormap().
editor_
Editor* HeightMapModifier::editor_ protected
Referenced by apply(), applyModifier(), initialize(), and setPreviewEnabled().
mainWindow_
MainWindow* HeightMapModifier::mainWindow_ protected
Referenced by apply(), initialize(), and setPreviewEnabled().
mutex_
QMutex HeightMapModifier::mutex_ protected
Referenced by applyModifier(), isPreviewEnabled(), setColormap(), setPreviewEnabled(), and setSource().
previewEnabled_
bool HeightMapModifier::previewEnabled_ protected
Referenced by isPreviewEnabled(), setColormap(), setPreviewEnabled(), and setSource().
source_
Source HeightMapModifier::source_ protected
Referenced by applyModifier(), and setSource().
The documentation for this class was generated from the following files:
HeightMapModifier.hpp
HeightMapModifier.cpp