3D Forest: SliderWidget Class Reference
SliderWidget Class Reference
#include <SliderWidget.hpp>
Inherits QWidget.
Signals
void signalIntermediateValue (int v)
void signalFinalValue ()
Public Member Functions
SliderWidget ()
int value () const
int minimum () const
int maximum () const
void setValue (int value)
void setMinimum (int min)
void setMaximum (int max)
void blockSignals (bool block)
Static Public Member Functions
static void create (SliderWidget *&outputWidget, const QObject *receiver, const char *memberIntermediateValue, const char *memberFinalValue, const QString &text, const QString &toolTip, const QString &unitsList, int step, int min, int max, int value)
Protected Slots
void slotIntermediateValue (int v)
void slotFinalValue ()
Protected Attributes
QSlider * slider_
QSpinBox * spinBox_
Constructor & Destructor Documentation
SliderWidget()
SliderWidget::SliderWidget ()
Referenced by create().
Member Function Documentation
blockSignals()
void SliderWidget::blockSignals (bool block)
create()
void SliderWidget::create (SliderWidget *& outputWidget, const QObject * receiver, const char * memberIntermediateValue, const char * memberFinalValue, const QString & text, const QString & toolTip, const QString & unitsList, int step, int min, int max, int value) static
Referenced by ClassificationWidget::ClassificationWidget(), DescriptorWidget::DescriptorWidget(), ElevationWidget::ElevationWidget(), and SegmentationWidget::SegmentationWidget().
maximum()
int SliderWidget::maximum () const
minimum()
int SliderWidget::minimum () const
setMaximum()
void SliderWidget::setMaximum (int max)
setMinimum()
void SliderWidget::setMinimum (int min)
setValue()
void SliderWidget::setValue (int value)
signalFinalValue
void SliderWidget::signalFinalValue () signal
Referenced by create(), and slotFinalValue().
signalIntermediateValue
void SliderWidget::signalIntermediateValue (int v) signal
Referenced by create(), and slotIntermediateValue().
slotFinalValue
void SliderWidget::slotFinalValue () protected slot
Referenced by create().
slotIntermediateValue
void SliderWidget::slotIntermediateValue (int v) protected slot
Referenced by create().
value()
int SliderWidget::value () const
Referenced by create(), setValue(), ClassificationWidget::slotApply(), DescriptorWidget::slotApply(), ElevationWidget::slotApply(), and SegmentationWidget::slotApply().
Member Data Documentation
slider_
QSlider* SliderWidget::slider_ protected
Referenced by blockSignals(), create(), maximum(), minimum(), setMaximum(), setMinimum(), setValue(), slotIntermediateValue(), and value().
spinBox_
QSpinBox* SliderWidget::spinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMinimum(), setValue(), and slotIntermediateValue().
The documentation for this class was generated from the following files:
SliderWidget.hpp
SliderWidget.cpp