3D Forest: ImportFilePlugin Class Reference
ImportFilePlugin Class Reference
#include <ImportFilePlugin.hpp>
Inherits QObject.
Public Slots
void slotImportFile ()
Public Member Functions
ImportFilePlugin ()
void initialize (MainWindow *mainWindow)
Static Public Member Functions
static void import (MainWindow *mainWindow)
Protected Attributes
MainWindow * mainWindow_
QAction * importFileAction_
Constructor & Destructor Documentation
ImportFilePlugin()
ImportFilePlugin::ImportFilePlugin ()
Member Function Documentation
import()
void ImportFilePlugin::import (MainWindow * mainWindow) static
Referenced by ExplorerFilesWidget::slotAdd(), and slotImportFile().
initialize()
void ImportFilePlugin::initialize (MainWindow * mainWindow)
Referenced by MainWindow::MainWindow().
slotImportFile
void ImportFilePlugin::slotImportFile () slot
Referenced by initialize().
Member Data Documentation
importFileAction_
QAction* ImportFilePlugin::importFileAction_ protected
Referenced by initialize().
mainWindow_
MainWindow* ImportFilePlugin::mainWindow_ protected
Referenced by initialize(), and slotImportFile().
The documentation for this class was generated from the following files:
ImportFilePlugin.hpp
ImportFilePlugin.cpp