3D Forest: ViewerOpenGLViewport Class Reference
ViewerOpenGLViewport Class Reference
#include <ViewerOpenGLViewport.hpp>
Inherits QOpenGLWidget, and QOpenGLFunctions.
Public Member Functions
ViewerOpenGLViewport (QWidget *parent=nullptr)
~ViewerOpenGLViewport ()
void setViewports (ViewerViewports *viewer, size_t viewportId)
size_t viewportId () const
void setSelected (bool selected)
bool selected () const
void updateScene (Editor *editor)
void resetScene (Editor *editor, bool resetView)
Camera camera () const
void setViewOrthographic ()
void setViewPerspective ()
void setViewTop ()
void setViewFront ()
void setViewRight ()
void setView3d ()
void setViewResetDistance ()
void setViewResetCenter ()
Protected Member Functions
void paintEvent (QPaintEvent *event) override
void resizeEvent (QResizeEvent *event) override
void showEvent (QShowEvent *event) override
void hideEvent (QHideEvent *event) override
void initializeGL () override
void paintGL () override
void resizeGL (int w, int h) override
void mouseReleaseEvent (QMouseEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void wheelEvent (QWheelEvent *event) override
void setViewDefault ()
void clearScreen ()
void renderScene ()
void renderFirstFrame ()
void renderLastFrame ()
void renderSegments ()
void renderAttributes ()
void renderGuides ()
void renderSceneSettingsEnable ()
void renderSceneSettingsDisable ()
void cameraChanged ()
void setFocus ()
void setViewDirection (const QVector3D &dir, const QVector3D &up)
Protected Attributes
ViewerViewports * windowViewports_
size_t viewportId_
bool selected_
bool resized_
Editor * editor_
ViewerAabb aabb_
ViewerCamera camera_
Constructor & Destructor Documentation
ViewerOpenGLViewport()
ViewerOpenGLViewport::ViewerOpenGLViewport (QWidget * parent = nullptr) explicit
~ViewerOpenGLViewport()
ViewerOpenGLViewport::~ViewerOpenGLViewport ()
Member Function Documentation
camera()
Camera ViewerOpenGLViewport::camera () const
cameraChanged()
void ViewerOpenGLViewport::cameraChanged () protected
Referenced by mouseMoveEvent(), and wheelEvent().
clearScreen()
void ViewerOpenGLViewport::clearScreen () protected
Referenced by renderFirstFrame().
hideEvent()
void ViewerOpenGLViewport::hideEvent (QHideEvent * event) override protected
initializeGL()
void ViewerOpenGLViewport::initializeGL () override protected
mouseMoveEvent()
void ViewerOpenGLViewport::mouseMoveEvent (QMouseEvent * event) override protected
mousePressEvent()
void ViewerOpenGLViewport::mousePressEvent (QMouseEvent * event) override protected
mouseReleaseEvent()
void ViewerOpenGLViewport::mouseReleaseEvent (QMouseEvent * event) override protected
paintEvent()
void ViewerOpenGLViewport::paintEvent (QPaintEvent * event) override protected
paintGL()
void ViewerOpenGLViewport::paintGL () override protected
renderAttributes()
void ViewerOpenGLViewport::renderAttributes () protected
Referenced by renderFirstFrame().
renderFirstFrame()
void ViewerOpenGLViewport::renderFirstFrame () protected
Referenced by renderScene().
renderGuides()
void ViewerOpenGLViewport::renderGuides () protected
Referenced by renderFirstFrame().
renderLastFrame()
void ViewerOpenGLViewport::renderLastFrame () protected
Referenced by renderScene().
renderScene()
void ViewerOpenGLViewport::renderScene () protected
Referenced by paintGL().
renderSceneSettingsDisable()
void ViewerOpenGLViewport::renderSceneSettingsDisable () protected
Referenced by renderScene().
renderSceneSettingsEnable()
void ViewerOpenGLViewport::renderSceneSettingsEnable () protected
Referenced by renderScene().
renderSegments()
void ViewerOpenGLViewport::renderSegments () protected
Referenced by renderFirstFrame().
resetScene()
void ViewerOpenGLViewport::resetScene (Editor * editor, bool resetView)
resizeEvent()
void ViewerOpenGLViewport::resizeEvent (QResizeEvent * event) override protected
resizeGL()
void ViewerOpenGLViewport::resizeGL (int w, int h) override protected
selected()
bool ViewerOpenGLViewport::selected () const
Referenced by setFocus(), and setSelected().
setFocus()
void ViewerOpenGLViewport::setFocus () protected
Referenced by mousePressEvent(), and wheelEvent().
setSelected()
void ViewerOpenGLViewport::setSelected (bool selected)
Referenced by ViewerViewports::createViewport().
setView3d()
void ViewerOpenGLViewport::setView3d ()
Referenced by ViewerViewports::setView3d().
setViewDefault()
void ViewerOpenGLViewport::setViewDefault () protected
Referenced by ViewerOpenGLViewport().
setViewDirection()
void ViewerOpenGLViewport::setViewDirection (const QVector3D & dir, const QVector3D & up) protected
Referenced by setView3d(), setViewFront(), setViewRight(), and setViewTop().
setViewFront()
void ViewerOpenGLViewport::setViewFront ()
Referenced by ViewerViewports::setViewFront().
setViewOrthographic()
void ViewerOpenGLViewport::setViewOrthographic ()
Referenced by ViewerViewports::setViewOrthographic().
setViewPerspective()
void ViewerOpenGLViewport::setViewPerspective ()
Referenced by ViewerViewports::setViewPerspective().
setViewports()
void ViewerOpenGLViewport::setViewports (ViewerViewports * viewer, size_t viewportId)
Referenced by ViewerViewports::createViewport().
setViewResetCenter()
void ViewerOpenGLViewport::setViewResetCenter ()
Referenced by resetScene(), and ViewerViewports::setViewResetCenter().
setViewResetDistance()
void ViewerOpenGLViewport::setViewResetDistance ()
Referenced by resetScene(), and ViewerViewports::setViewResetDistance().
setViewRight()
void ViewerOpenGLViewport::setViewRight ()
Referenced by ViewerViewports::setViewRight().
setViewTop()
void ViewerOpenGLViewport::setViewTop ()
Referenced by ViewerViewports::setViewTop().
showEvent()
void ViewerOpenGLViewport::showEvent (QShowEvent * event) override protected
updateScene()
void ViewerOpenGLViewport::updateScene (Editor * editor)
viewportId()
size_t ViewerOpenGLViewport::viewportId () const
Referenced by ViewerViewports::selectViewport(), and setViewports().
wheelEvent()
void ViewerOpenGLViewport::wheelEvent (QWheelEvent * event) override protected
Member Data Documentation
aabb_
ViewerAabb ViewerOpenGLViewport::aabb_ protected
Referenced by renderFirstFrame(), renderSceneSettingsEnable(), resetScene(), setViewResetCenter(), and setViewResetDistance().
camera_
ViewerCamera ViewerOpenGLViewport::camera_ protected
Referenced by camera(), mouseMoveEvent(), mousePressEvent(), paintGL(), renderFirstFrame(), renderGuides(), renderSceneSettingsEnable(), resizeGL(), setViewDefault(), setViewDirection(), setViewOrthographic(), setViewPerspective(), setViewports(), setViewResetCenter(), setViewResetDistance(), and wheelEvent().
editor_
Editor* ViewerOpenGLViewport::editor_ protected
Referenced by renderAttributes(), renderFirstFrame(), renderScene(), renderSceneSettingsDisable(), renderSceneSettingsEnable(), renderSegments(), resetScene(), and updateScene().
resized_
bool ViewerOpenGLViewport::resized_ protected
Referenced by renderScene(), and resizeEvent().
selected_
bool ViewerOpenGLViewport::selected_ protected
Referenced by selected(), and setSelected().
viewportId_
size_t ViewerOpenGLViewport::viewportId_ protected
Referenced by cameraChanged(), renderFirstFrame(), renderScene(), resetScene(), setView3d(), setViewDefault(), setViewDirection(), setViewFront(), setViewports(), setViewResetCenter(), setViewResetDistance(), setViewRight(), setViewTop(), updateScene(), and viewportId().
windowViewports_
ViewerViewports* ViewerOpenGLViewport::windowViewports_ protected
Referenced by cameraChanged(), setFocus(), and setViewports().
The documentation for this class was generated from the following files:
ViewerOpenGLViewport.hpp
ViewerOpenGLViewport.cpp