3D Forest: FilterIntensityWidget Class Reference
FilterIntensityWidget Class Reference
#include <FilterIntensityWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
FilterIntensityWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Member Functions
void setIntensity (const Range< double > &intensityRange)
void filterChanged ()
Protected Attributes
MainWindow * mainWindow_
DoubleRangeSliderWidget * intensityInput_
Range< double > intensityRange_
Constructor & Destructor Documentation
FilterIntensityWidget()
FilterIntensityWidget::FilterIntensityWidget (MainWindow * mainWindow)
Member Function Documentation
filterChanged()
void FilterIntensityWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
setFilterEnabled()
void FilterIntensityWidget::setFilterEnabled (bool b)
Referenced by FilterIntensityWindow::closeEvent(), and FilterIntensityWindow::showEvent().
setIntensity()
void FilterIntensityWidget::setIntensity (const Range< double > & intensityRange) protected
Referenced by slotUpdate().
sizeHint()
QSize FilterIntensityWidget::sizeHint () const inline override
slotRangeIntermediateMaximumValue
void FilterIntensityWidget::slotRangeIntermediateMaximumValue () slot
Referenced by FilterIntensityWidget().
slotRangeIntermediateMinimumValue
void FilterIntensityWidget::slotRangeIntermediateMinimumValue () slot
Referenced by FilterIntensityWidget().
slotUpdate
void FilterIntensityWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterIntensityWidget().
Member Data Documentation
intensityInput_
DoubleRangeSliderWidget* FilterIntensityWidget::intensityInput_ protected
Referenced by FilterIntensityWidget(), setIntensity(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
intensityRange_
Range<double> FilterIntensityWidget::intensityRange_ protected
Referenced by filterChanged(), setFilterEnabled(), setIntensity(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
mainWindow_
MainWindow* FilterIntensityWidget::mainWindow_ protected
Referenced by filterChanged(), FilterIntensityWidget(), and slotUpdate().
The documentation for this class was generated from the following files:
FilterIntensityWidget.hpp
FilterIntensityWidget.cpp