3D Forest: FilterFilesWidget Class Reference
FilterFilesWidget Class Reference
#include <FilterFilesWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
FilterFilesWidget (MainWindow *mainWindow)
void setFilterEnabled (bool b)
QSize sizeHint () const override
Protected Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_DATE_CREATED ,
COLUMN_LAST
}
Protected Member Functions
void setDatasets (const Datasets &datasets, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Datasets datasets_
QueryFilterSet filter_
bool updatesEnabled_
Member Enumeration Documentation
Column
enum FilterFilesWidget::Column protected
Filter Files Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_DATE_CREATED
COLUMN_LAST
Constructor & Destructor Documentation
FilterFilesWidget()
FilterFilesWidget::FilterFilesWidget (MainWindow * mainWindow)
Member Function Documentation
addTreeItem()
void FilterFilesWidget::addTreeItem (size_t index) protected
Referenced by setDatasets().
block()
void FilterFilesWidget::block () protected
Referenced by setDatasets(), and updateTree().
dataChanged()
void FilterFilesWidget::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void FilterFilesWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
identifier()
size_t FilterFilesWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
index()
size_t FilterFilesWidget::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), slotDelete(), slotHide(), and slotShow().
setDatasets()
void FilterFilesWidget::setDatasets (const Datasets & datasets, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
setFilterEnabled()
void FilterFilesWidget::setFilterEnabled (bool b)
Referenced by FilterFilesWindow::closeEvent(), and FilterFilesWindow::showEvent().
sizeHint()
QSize FilterFilesWidget::sizeHint () const inline override
slotAdd
void FilterFilesWidget::slotAdd () slot
Referenced by FilterFilesWidget().
slotDelete
void FilterFilesWidget::slotDelete () slot
Referenced by FilterFilesWidget().
slotHide
void FilterFilesWidget::slotHide () slot
Referenced by FilterFilesWidget().
slotItemChanged
void FilterFilesWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void FilterFilesWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void FilterFilesWidget::slotSelectAll () slot
Referenced by FilterFilesWidget().
slotSelectInvert
void FilterFilesWidget::slotSelectInvert () slot
Referenced by FilterFilesWidget().
slotSelectNone
void FilterFilesWidget::slotSelectNone () slot
Referenced by FilterFilesWidget(), and slotDelete().
slotShow
void FilterFilesWidget::slotShow () slot
Referenced by FilterFilesWidget().
slotUpdate
void FilterFilesWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by FilterFilesWidget().
unblock()
void FilterFilesWidget::unblock () protected
Referenced by setDatasets(), and updateTree().
updateTree()
void FilterFilesWidget::updateTree () protected
Member Data Documentation
addButton_
QToolButton* FilterFilesWidget::addButton_ protected
Referenced by FilterFilesWidget().
datasets_
Datasets FilterFilesWidget::datasets_ protected
Referenced by addTreeItem(), dataChanged(), index(), setDatasets(), and slotDelete().
deleteButton_
QToolButton* FilterFilesWidget::deleteButton_ protected
Referenced by FilterFilesWidget(), and slotItemSelectionChanged().
filter_
QueryFilterSet FilterFilesWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), setDatasets(), setFilterEnabled(), slotDelete(), slotHide(), slotItemChanged(), slotShow(), and updateTree().
hideButton_
QToolButton* FilterFilesWidget::hideButton_ protected
Referenced by FilterFilesWidget(), and slotItemSelectionChanged().
mainWindow_
MainWindow* FilterFilesWidget::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), FilterFilesWidget(), slotAdd(), and slotUpdate().
selectAllButton_
QToolButton* FilterFilesWidget::selectAllButton_ protected
Referenced by FilterFilesWidget().
selectInvertButton_
QToolButton* FilterFilesWidget::selectInvertButton_ protected
Referenced by FilterFilesWidget().
selectNoneButton_
QToolButton* FilterFilesWidget::selectNoneButton_ protected
Referenced by FilterFilesWidget().
showButton_
QToolButton* FilterFilesWidget::showButton_ protected
Referenced by FilterFilesWidget(), and slotItemSelectionChanged().
tree_
QTreeWidget* FilterFilesWidget::tree_ protected
Referenced by addTreeItem(), block(), FilterFilesWidget(), setDatasets(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool FilterFilesWidget::updatesEnabled_ protected
Referenced by FilterFilesWidget(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
FilterFilesWidget.hpp
FilterFilesWidget.cpp