3D Forest: Datasets Class Reference
Datasets Class Reference
#include <Datasets.hpp>
Public Member Functions
Datasets ()
void clear ()
size_t size () const
const std::unordered_set< size_t > & idList () const
const Dataset & at (size_t i) const
const Dataset & key (size_t id) const
Dataset & key (size_t id)
void erase (size_t i)
size_t id (size_t i) const
size_t index (size_t id)
size_t unusedId () const
const std::string & label (size_t i) const
void setLabel (size_t i, const std::string &label)
const Vector3< double > & color (size_t i) const
void setColor (size_t i, const Vector3< double > &color)
const std::string & fileName (size_t i) const
const std::string & dateCreated (size_t i) const
const Vector3< double > & translation (size_t i) const
void setTranslation (size_t i, const Vector3< double > &translation)
const Vector3< double > & scaling (size_t i) const
const Vector3< double > & scalingFile (size_t i) const
const Box< double > & boundary () const
Box< double > boundary (const QueryFilterSet &datasetFilter) const
void updateBoundary ()
Dataset::Range range ()
uint64_t nPoints () const
uint64_t nPoints (const QueryFilterSet &datasetFilter) const
void selectPages (const QueryFilterSet &datasetFilter, const Box< double > &box, std::vector< IndexFile::Selection > &selected) const
void read (const std::string &path, const std::string &projectPath, const SettingsImport &settings, const Box< double > &projectBoundary, QueryFilterSet &filter)
Protected Attributes
std::vector< Dataset > datasets_
std::unordered_set< size_t > datasetsIds_
std::unordered_map< size_t, size_t > hashTable_
Box< double > boundary_
Friends
void fromJson (Datasets &out, const Json &in, const std::string &projectPath, QueryFilterSet &filter)
void toJson (Json &out, const Datasets &in)
Constructor & Destructor Documentation
Datasets()
Datasets::Datasets ()
Member Function Documentation
at()
const Dataset & Datasets::at (size_t i) const inline
Referenced by Editor::updateAfterRead().
boundary() [1/2]
const Box< double > & Datasets::boundary () const inline
Referenced by Editor::openDataset(), ViewerOpenGLViewport::resetScene(), and Editor::updateAfterSet().
boundary() [2/2]
Box< double > Datasets::boundary (const QueryFilterSet & datasetFilter) const
clear()
void Datasets::clear ()
Referenced by Editor::close(), and Datasets().
color()
const Vector3< double > & Datasets::color (size_t i) const inline
Referenced by FilterFilesWidget::addTreeItem(), and setColor().
dateCreated()
const std::string & Datasets::dateCreated (size_t i) const inline
Referenced by FilterFilesWidget::addTreeItem().
erase()
void Datasets::erase (size_t i)
Referenced by FilterFilesWidget::slotDelete().
fileName()
const std::string & Datasets::fileName (size_t i) const inline
id()
size_t Datasets::id (size_t i) const inline
Referenced by FilterFilesWidget::addTreeItem(), erase(), and read().
idList()
const std::unordered_set< size_t > & Datasets::idList () const inline
Referenced by Query::applyCamera().
index()
size_t Datasets::index (size_t id) inline
Referenced by FilterFilesWidget::index().
key() [1/2]
Dataset & Datasets::key (size_t id) inline
key() [2/2]
const Dataset & Datasets::key (size_t id) const inline
Referenced by Query::applyCamera(), erase(), PageData::readPage(), Page::runColorModifier(), PageData::transform(), and PageData::writePage().
label()
const std::string & Datasets::label (size_t i) const inline
Referenced by FilterFilesWidget::addTreeItem(), and setLabel().
nPoints() [1/2]
uint64_t Datasets::nPoints () const
Referenced by Query::setGrid(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), and ComputeElevationAction::start().
nPoints() [2/2]
uint64_t Datasets::nPoints (const QueryFilterSet & datasetFilter) const
range()
Dataset::Range Datasets::range ()
Referenced by range(), and Editor::updateAfterSet().
read()
void Datasets::read (const std::string & path, const std::string & projectPath, const SettingsImport & settings, const Box< double > & projectBoundary, QueryFilterSet & filter)
Referenced by Editor::openDataset().
scaling()
const Vector3< double > & Datasets::scaling (size_t i) const inline
scalingFile()
const Vector3< double > & Datasets::scalingFile (size_t i) const inline
selectPages()
void Datasets::selectPages (const QueryFilterSet & datasetFilter, const Box< double > & box, std::vector< IndexFile::Selection > & selected) const
Referenced by Query::exec().
setColor()
void Datasets::setColor (size_t i, const Vector3< double > & color)
setLabel()
void Datasets::setLabel (size_t i, const std::string & label)
setTranslation()
void Datasets::setTranslation (size_t i, const Vector3< double > & translation)
size()
size_t Datasets::size () const inline
Referenced by Editor::setDatasets(), FilterFilesWidget::setDatasets(), and Editor::updateAfterRead().
translation()
const Vector3< double > & Datasets::translation (size_t i) const inline
Referenced by setTranslation().
unusedId()
size_t Datasets::unusedId () const
Referenced by read().
updateBoundary()
void Datasets::updateBoundary ()
Referenced by read().
Friends And Related Symbol Documentation
fromJson
void fromJson (Datasets & out, const Json & in, const std::string & projectPath, QueryFilterSet & filter) friend
toJson
void toJson (Json & out, const Datasets & in) friend
Member Data Documentation
boundary_
Box<double> Datasets::boundary_ protected
Referenced by clear(), and updateBoundary().
datasets_
std::vector<Dataset> Datasets::datasets_ protected
Referenced by boundary(), clear(), erase(), nPoints(), nPoints(), range(), read(), selectPages(), setColor(), setLabel(), setTranslation(), and updateBoundary().
datasetsIds_
std::unordered_set<size_t> Datasets::datasetsIds_ protected
Referenced by clear(), erase(), and read().
hashTable_
std::unordered_map<size_t, size_t> Datasets::hashTable_ protected
Referenced by clear(), erase(), read(), and unusedId().
The documentation for this class was generated from the following files:
Datasets.hpp
Datasets.cpp