3D Forest: Time Class Reference
Time Class Reference
#include <Time.hpp>
Static Public Member Functions
static double EXPORT_CORE realTime ()
static uint64_t EXPORT_CORE realTime64 ()
static void EXPORT_CORE msleep (long milliseconds)
static std::string EXPORT_CORE strftime (const char *format="%Y-%m-%d %H:%M:%S")
Member Function Documentation
msleep()
void Time::msleep (long milliseconds) static
Makes the calling thread sleep until milliseconds have elapsed.
Referenced by RenderThread::next(), and File::tmpname().
realTime()
double Time::realTime () static
Get the number of seconds since the Epoch.
Referenced by ProgressDialog::initializeLabels(), RenderThread::next(), ViewerOpenGLViewport::renderScene(), ProgressCounter::startTimer(), ProgressCounter::timedOut(), and ProgressDialog::updateLabels().
realTime64()
uint64_t Time::realTime64 () static
Get the number of seconds since the Epoch.
Referenced by File::tmpname().
strftime()
std::string Time::strftime (const char * format = "%Y-%m-%d %H:%M:%S") static
Format current local time to string.
Referenced by LogThread::println().
The documentation for this class was generated from the following files:
Time.hpp
Time.cpp