3D Forest: QueryFilterSet Class Reference
QueryFilterSet Class Reference
#include <QueryFilterSet.hpp>
Public Member Functions
QueryFilterSet ()
QueryFilterSet (const std::unordered_set< size_t > &list, bool enabled=true)
~QueryFilterSet ()
void clear ()
void setFilterEnabled (bool enabled)
bool isFilterEnabled () const
bool contains (size_t value) const
const std::unordered_set< size_t > & filter () const
void setFilter (const std::unordered_set< size_t > &list)
void setValues (const std::unordered_set< size_t > &list)
void none ()
void all ()
void invert ()
void erase (size_t id)
void setFilter (size_t id, bool enabled)
bool hasFilter (size_t id) const
Private Attributes
std::unordered_set< size_t > filter_
std::unordered_set< size_t > values_
bool enabled_
Constructor & Destructor Documentation
QueryFilterSet() [1/2]
QueryFilterSet::QueryFilterSet ()
QueryFilterSet() [2/2]
QueryFilterSet::QueryFilterSet (const std::unordered_set< size_t > & list, bool enabled = true)
~QueryFilterSet()
QueryFilterSet::~QueryFilterSet ()
Member Function Documentation
all()
void QueryFilterSet::all ()
clear()
void QueryFilterSet::clear ()
Referenced by Editor::close(), and SegmentationAction::stepResetPoints().
contains()
bool QueryFilterSet::contains (size_t value) const inline
Referenced by Datasets::boundary(), Datasets::nPoints(), and Datasets::selectPages().
erase()
void QueryFilterSet::erase (size_t id)
Referenced by ExplorerFilesWidget::slotDelete(), and ExplorerLayersWidget::slotDelete().
filter()
const std::unordered_set< size_t > & QueryFilterSet::filter () const inline
Referenced by Query::applyCamera(), QueryWhere::classificationsToArray(), and Page::queryWhereLayer().
hasFilter()
bool QueryFilterSet::hasFilter (size_t id) const inline
Referenced by ExplorerClassificationsWidget::addTreeItem(), ExplorerFilesWidget::addTreeItem(), ExplorerLayersWidget::addTreeItem(), ExplorerClassificationsWidget::updateTree(), ExplorerFilesWidget::updateTree(), and ExplorerLayersWidget::updateTree().
invert()
void QueryFilterSet::invert ()
isFilterEnabled()
bool QueryFilterSet::isFilterEnabled () const inline
Referenced by ExplorerClassificationsWidget::dataChanged(), ExplorerFilesWidget::dataChanged(), ExplorerLayersWidget::dataChanged(), ExplorerClassificationsWidget::filterChanged(), ExplorerFilesWidget::filterChanged(), ExplorerLayersWidget::filterChanged(), ExplorerClassificationsWidget::isFilterEnabled(), ExplorerFilesWidget::isFilterEnabled(), ExplorerLayersWidget::isFilterEnabled(), Page::queryWhereClassification(), and Page::queryWhereLayer().
none()
void QueryFilterSet::none ()
setFilter() [1/2]
void QueryFilterSet::setFilter (const std::unordered_set< size_t > & list)
Referenced by Editor::close(), Datasets::read(), QueryWhere::setClassification(), QueryWhere::setDataset(), QueryWhere::setLayer(), ExplorerClassificationsWidget::slotItemChanged(), ExplorerFilesWidget::slotItemChanged(), ExplorerLayersWidget::slotItemChanged(), SegmentationAction::stepCreateLayers(), and SegmentationAction::stepResetPoints().
setFilter() [2/2]
void QueryFilterSet::setFilter (size_t id, bool enabled)
setFilterEnabled()
void QueryFilterSet::setFilterEnabled (bool enabled) inline
Referenced by Editor::close(), ExplorerClassificationsWidget::setFilterEnabled(), ExplorerFilesWidget::setFilterEnabled(), ExplorerLayersWidget::setFilterEnabled(), SegmentationAction::stepCreateLayers(), and SegmentationAction::stepResetPoints().
setValues()
void QueryFilterSet::setValues (const std::unordered_set< size_t > & list)
Member Data Documentation
enabled_
bool QueryFilterSet::enabled_ private
Referenced by clear().
filter_
std::unordered_set<size_t> QueryFilterSet::filter_ private
Referenced by all(), clear(), erase(), invert(), none(), setFilter(), and setValues().
values_
std::unordered_set<size_t> QueryFilterSet::values_ private
Referenced by all(), clear(), erase(), invert(), setFilter(), and setValues().
The documentation for this class was generated from the following files:
QueryFilterSet.hpp
QueryFilterSet.cpp