3D Forest: DoubleRangeSliderWidget Class Reference
DoubleRangeSliderWidget Class Reference
#include <DoubleRangeSliderWidget.hpp>
Inherits QWidget.
Signals
void signalIntermediateMinimumValue ()
void signalIntermediateMaximumValue ()
Public Member Functions
DoubleRangeSliderWidget ()
void setMinimum (double min)
void setMaximum (double max)
void setMinimumValue (double value)
double minimumValue ()
void setMaximumValue (double value)
double maximumValue ()
void blockSignals (bool block)
Static Public Member Functions
static void create (DoubleRangeSliderWidget *&outputWidget, const QObject *receiver, const char *memberIntermediateMinimumValue, const char *memberIntermediateMaximumValue, const QString &text, const QString &toolTip, const QString &unitsList, double step, double min, double max, double minValue, double maxValue)
Protected Slots
void slotIntermediateMinimumValue (double v)
void slotIntermediateMaximumValue (double v)
Protected Attributes
ctkDoubleRangeSlider * slider_
QDoubleSpinBox * minSpinBox_
QDoubleSpinBox * maxSpinBox_
double minimumValue_
double maximumValue_
Constructor & Destructor Documentation
DoubleRangeSliderWidget()
DoubleRangeSliderWidget::DoubleRangeSliderWidget ()
Referenced by create().
Member Function Documentation
blockSignals()
void DoubleRangeSliderWidget::blockSignals (bool block)
Referenced by FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), FilterIntensityWidget::setIntensity(), and FilterAreaBoxWidget::setRegion().
create()
void DoubleRangeSliderWidget::create (DoubleRangeSliderWidget *& outputWidget, const QObject * receiver, const char * memberIntermediateMinimumValue, const char * memberIntermediateMaximumValue, const QString & text, const QString & toolTip, const QString & unitsList, double step, double min, double max, double minValue, double maxValue) static
Referenced by ComputeSegmentationNNWidget::ComputeSegmentationNNWidget(), FilterAreaBoxWidget::FilterAreaBoxWidget(), FilterDescriptorWidget::FilterDescriptorWidget(), FilterElevationWidget::FilterElevationWidget(), and FilterIntensityWidget::FilterIntensityWidget().
maximumValue()
double DoubleRangeSliderWidget::maximumValue ()
Referenced by ComputeSegmentationNNWidget::slotApply(), FilterAreaBoxWidget::slotRangeIntermediateMaximumValue(), FilterDescriptorWidget::slotRangeIntermediateMaximumValue(), FilterElevationWidget::slotRangeIntermediateMaximumValue(), and FilterIntensityWidget::slotRangeIntermediateMaximumValue().
minimumValue()
double DoubleRangeSliderWidget::minimumValue ()
Referenced by ComputeSegmentationNNWidget::slotApply(), FilterAreaBoxWidget::slotRangeIntermediateMinimumValue(), FilterDescriptorWidget::slotRangeIntermediateMinimumValue(), FilterElevationWidget::slotRangeIntermediateMinimumValue(), and FilterIntensityWidget::slotRangeIntermediateMinimumValue().
setMaximum()
void DoubleRangeSliderWidget::setMaximum (double max)
Referenced by FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), FilterIntensityWidget::setIntensity(), and FilterAreaBoxWidget::setRegion().
setMaximumValue()
void DoubleRangeSliderWidget::setMaximumValue (double value)
Referenced by FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), FilterIntensityWidget::setIntensity(), and FilterAreaBoxWidget::setRegion().
setMinimum()
void DoubleRangeSliderWidget::setMinimum (double min)
Referenced by FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), FilterIntensityWidget::setIntensity(), and FilterAreaBoxWidget::setRegion().
setMinimumValue()
void DoubleRangeSliderWidget::setMinimumValue (double value)
Referenced by FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), FilterIntensityWidget::setIntensity(), and FilterAreaBoxWidget::setRegion().
signalIntermediateMaximumValue
void DoubleRangeSliderWidget::signalIntermediateMaximumValue () signal
Referenced by create(), and slotIntermediateMaximumValue().
signalIntermediateMinimumValue
void DoubleRangeSliderWidget::signalIntermediateMinimumValue () signal
Referenced by create(), and slotIntermediateMinimumValue().
slotIntermediateMaximumValue
void DoubleRangeSliderWidget::slotIntermediateMaximumValue (double v) protected slot
Referenced by create().
slotIntermediateMinimumValue
void DoubleRangeSliderWidget::slotIntermediateMinimumValue (double v) protected slot
Referenced by create().
Member Data Documentation
maximumValue_
double DoubleRangeSliderWidget::maximumValue_ protected
Referenced by create(), maximumValue(), setMaximum(), setMaximumValue(), and slotIntermediateMaximumValue().
maxSpinBox_
QDoubleSpinBox* DoubleRangeSliderWidget::maxSpinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMaximumValue(), setMinimum(), and slotIntermediateMaximumValue().
minimumValue_
double DoubleRangeSliderWidget::minimumValue_ protected
Referenced by create(), minimumValue(), setMinimum(), setMinimumValue(), and slotIntermediateMinimumValue().
minSpinBox_
QDoubleSpinBox* DoubleRangeSliderWidget::minSpinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMinimum(), setMinimumValue(), and slotIntermediateMinimumValue().
slider_
ctkDoubleRangeSlider* DoubleRangeSliderWidget::slider_ protected
Referenced by blockSignals(), create(), setMaximum(), setMaximumValue(), setMinimum(), setMinimumValue(), slotIntermediateMaximumValue(), and slotIntermediateMinimumValue().
The documentation for this class was generated from the following files:
DoubleRangeSliderWidget.hpp
DoubleRangeSliderWidget.cpp