3D Forest: Range< T > Class Template Reference
Range< T > Class Template Reference
#include <Range.hpp>
Inherits std::array< T, 4 >.
Public Member Functions
Range ()
Range (T min, T max)
Range (T min, T minValue, T maxValue, T max)
~Range ()
void setEnabled (bool enabled)
bool enabled () const
bool empty () const
bool full () const
void setMinimum (T v)
void setMaximum (T v)
T minimum () const
T maximum () const
void setMinimumValue (T v)
void setMaximumValue (T v)
T minimumValue () const
T maximumValue () const
void clear ()
void set (T min, T max)
void set (T min, T minValue, T maxValue, T max)
bool contains (T v) const
Protected Attributes
bool enabled_
Friends
template<class U >
void fromJson (Range< U > &out, const Json &in)
template<class U >
void toJson (Json &out, const Range< U > &in)
template<class U >
std::string toString (const Range< U > &in)
template<class U >
std::ostream & operator<< (std::ostream &out, const Range< U > &in)
Constructor & Destructor Documentation
Range() [1/3]
template<class T > Range< T >::Range () inline
Range() [2/3]
template<class T > Range< T >::Range (T min, T max) inline
Range() [3/3]
template<class T > Range< T >::Range (T min, T minValue, T maxValue, T max) inline
~Range()
template<class T > Range< T >::~Range () inline
Member Function Documentation
clear()
template<class T > void Range< T >::clear () inline
Referenced by QueryWhere::clear(), and Editor::close().
contains()
template<class T > bool Range< T >::contains (T v) const inline
empty()
template<class T > bool Range< T >::empty () const inline
enabled()
template<class T > bool Range< T >::enabled () const inline
Referenced by Page::queryWhereDescriptor(), Page::queryWhereElevation(), Page::queryWhereIntensity(), and Range< T >::setEnabled().
full()
template<class T > bool Range< T >::full () const inline
Referenced by Page::queryWhereDescriptor(), Page::queryWhereElevation(), and Page::queryWhereIntensity().
maximum()
template<class T > T Range< T >::maximum () const inline
Referenced by ComputeHeightMapModifier::applyModifier(), FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), and FilterIntensityWidget::setIntensity().
maximumValue()
template<class T > T Range< T >::maximumValue () const inline
Referenced by FilterAreaBoxWidget::filterChanged(), Page::queryWhereDescriptor(), Page::queryWhereElevation(), and Page::queryWhereIntensity().
minimum()
template<class T > T Range< T >::minimum () const inline
Referenced by ComputeHeightMapModifier::applyModifier(), FilterDescriptorWidget::setDescriptor(), FilterElevationWidget::setElevation(), and FilterIntensityWidget::setIntensity().
minimumValue()
template<class T > T Range< T >::minimumValue () const inline
Referenced by FilterAreaBoxWidget::filterChanged(), Page::queryWhereDescriptor(), Page::queryWhereElevation(), and Page::queryWhereIntensity().
set() [1/2]
template<class T > void Range< T >::set (T min, T max) inline
Referenced by Editor::close(), ComputeElevationAction::stepComputeElevation(), and Editor::updateAfterSet().
set() [2/2]
template<class T > void Range< T >::set (T min, T minValue, T maxValue, T max) inline
setEnabled()
template<class T > void Range< T >::setEnabled (bool enabled) inline
Referenced by FilterDescriptorWidget::setFilterEnabled(), FilterElevationWidget::setFilterEnabled(), and FilterIntensityWidget::setFilterEnabled().
setMaximum()
template<class T > void Range< T >::setMaximum (T v) inline
Referenced by FilterAreaBoxWidget::setRegion().
setMaximumValue()
template<class T > void Range< T >::setMaximumValue (T v) inline
Referenced by FilterAreaBoxWidget::setRegion(), FilterAreaBoxWidget::slotRangeIntermediateMaximumValue(), FilterDescriptorWidget::slotRangeIntermediateMaximumValue(), FilterElevationWidget::slotRangeIntermediateMaximumValue(), and FilterIntensityWidget::slotRangeIntermediateMaximumValue().
setMinimum()
template<class T > void Range< T >::setMinimum (T v) inline
Referenced by FilterAreaBoxWidget::setRegion().
setMinimumValue()
template<class T > void Range< T >::setMinimumValue (T v) inline
Referenced by FilterAreaBoxWidget::setRegion(), FilterAreaBoxWidget::slotRangeIntermediateMinimumValue(), FilterDescriptorWidget::slotRangeIntermediateMinimumValue(), FilterElevationWidget::slotRangeIntermediateMinimumValue(), and FilterIntensityWidget::slotRangeIntermediateMinimumValue().
Friends And Related Symbol Documentation
fromJson
template<class T > template<class U > void fromJson (Range< U > & out, const Json & in) friend
operator<<
template<class T > template<class U > std::ostream & operator<< (std::ostream & out, const Range< U > & in) friend
toJson
template<class T > template<class U > void toJson (Json & out, const Range< U > & in) friend
toString
template<class T > template<class U > std::string toString (const Range< U > & in) friend
Member Data Documentation
enabled_
template<class T > bool Range< T >::enabled_ protected
Referenced by Range< T >::enabled(), Range< T >::Range(), Range< T >::Range(), and Range< T >::setEnabled().
The documentation for this class was generated from the following file:
Range.hpp