3D Forest: SegmentationElements Class Reference
SegmentationElements Class Reference
#include <SegmentationElements.hpp>
Public Member Functions
SegmentationElements ()
void clear ()
uint32_t computeBase (Voxels &voxels, size_t voxelIndex, double minimumHeight, double radius)
size_t size () const
const SegmentationElement & operator[] (size_t index) const
Static Public Attributes
static const uint32_t npos = UINT32_MAX
Private Attributes
std::vector< std::shared_ptr< SegmentationElement > > elements_
std::shared_ptr< SegmentationElement > newElement_
Constructor & Destructor Documentation
SegmentationElements()
SegmentationElements::SegmentationElements ()
Member Function Documentation
clear()
void SegmentationElements::clear ()
Referenced by SegmentationThread::computeInitializeElements(), and SegmentationElements().
computeBase()
uint32_t SegmentationElements::computeBase (Voxels & voxels, size_t voxelIndex, double minimumHeight, double radius)
Referenced by SegmentationThread::computeCreateElements().
operator[]()
const SegmentationElement & SegmentationElements::operator[] (size_t index) const inline
size()
size_t SegmentationElements::size () const inline
Referenced by SegmentationThread::computeCreateLayers().
Member Data Documentation
elements_
std::vector<std::shared_ptr<SegmentationElement> > SegmentationElements::elements_ private
Referenced by clear(), computeBase(), operator[](), and size().
newElement_
std::shared_ptr<SegmentationElement> SegmentationElements::newElement_ private
Referenced by computeBase().
npos
const uint32_t SegmentationElements::npos = UINT32_MAX static
Referenced by computeBase(), and SegmentationThread::computeCreateElements().
The documentation for this class was generated from the following files:
SegmentationElements.hpp
SegmentationElements.cpp