3D Forest: ExplorerDescriptorWidget Class Reference
ExplorerDescriptorWidget Class Reference
#include <ExplorerDescriptorWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
ExplorerDescriptorWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void setDescriptor (const Range< double > &descriptorRange)
void filterChanged ()
Protected Attributes
DoubleRangeSliderWidget * descriptorInput_
Range< double > descriptorRange_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ExplorerDescriptorWidget()
ExplorerDescriptorWidget::ExplorerDescriptorWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ExplorerDescriptorWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
filterChanged()
void ExplorerDescriptorWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ExplorerDescriptorWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerDescriptorWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
isFilterEnabled()
bool ExplorerDescriptorWidget::isFilterEnabled () const virtual
Reimplemented from ExplorerWidgetInterface.
setDescriptor()
void ExplorerDescriptorWidget::setDescriptor (const Range< double > & descriptorRange) protected
Referenced by slotUpdate().
setFilterEnabled()
void ExplorerDescriptorWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
slotRangeIntermediateMaximumValue
void ExplorerDescriptorWidget::slotRangeIntermediateMaximumValue () slot
Referenced by ExplorerDescriptorWidget().
slotRangeIntermediateMinimumValue
void ExplorerDescriptorWidget::slotRangeIntermediateMinimumValue () slot
Referenced by ExplorerDescriptorWidget().
slotUpdate
void ExplorerDescriptorWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerDescriptorWidget().
Member Data Documentation
descriptorInput_
DoubleRangeSliderWidget* ExplorerDescriptorWidget::descriptorInput_ protected
Referenced by ExplorerDescriptorWidget(), setDescriptor(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
descriptorRange_
Range<double> ExplorerDescriptorWidget::descriptorRange_ protected
Referenced by filterChanged(), isFilterEnabled(), setDescriptor(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
The documentation for this class was generated from the following files:
ExplorerDescriptorWidget.hpp
ExplorerDescriptorWidget.cpp