3D Forest: MessageLogWindow Class Reference
MessageLogWindow Class Reference
#include <MessageLogWindow.hpp>
Inherits QDockWidget, and LogThreadCallbackInterface.
Public Slots
void slotPrintln (const LogMessage &message)
Signals
void signalPrintln (const LogMessage &message)
Public Member Functions
MessageLogWindow (MainWindow *mainWindow)
virtual ~MessageLogWindow ()
virtual void println (const LogMessage &message)
virtual void flush ()
Public Member Functions inherited from LogThreadCallbackInterface
virtual ~LogThreadCallbackInterface ()=default
Protected Attributes
MainWindow * mainWindow_
QTextEdit * textEdit_
File file_
size_t threadId_ {0}
Constructor & Destructor Documentation
MessageLogWindow()
MessageLogWindow::MessageLogWindow (MainWindow * mainWindow)
~MessageLogWindow()
MessageLogWindow::~MessageLogWindow () virtual
Member Function Documentation
flush()
void MessageLogWindow::flush () virtual
Implements LogThreadCallbackInterface.
println()
void MessageLogWindow::println (const LogMessage & message) virtual
Implements LogThreadCallbackInterface.
signalPrintln
void MessageLogWindow::signalPrintln (const LogMessage & message) signal
Referenced by MessageLogWindow(), and println().
slotPrintln
void MessageLogWindow::slotPrintln (const LogMessage & message) slot
Referenced by MessageLogWindow().
Member Data Documentation
file_
File MessageLogWindow::file_ protected
Referenced by MessageLogWindow(), and slotPrintln().
mainWindow_
MainWindow* MessageLogWindow::mainWindow_ protected
Referenced by MessageLogWindow().
textEdit_
QTextEdit* MessageLogWindow::textEdit_ protected
Referenced by MessageLogWindow(), and slotPrintln().
threadId_
size_t MessageLogWindow::threadId_ {0} protected
Referenced by slotPrintln().
The documentation for this class was generated from the following files:
MessageLogWindow.hpp
MessageLogWindow.cpp