3D Forest: Sphere< T > Class Template Reference
Sphere< T > Class Template Reference
#include <Sphere.hpp>
Public Member Functions
Sphere ()
~Sphere ()
template<class B >
Sphere (B x, B y, B z, B radius)
void set (T x, T y, T z, T radius)
void clear ()
bool empty () const
const Box< T > & box () const
bool isInside (T x, T y, T z) const
Protected Member Functions
void validate ()
Protected Attributes
T x_
T y_
T z_
T radius_
Box< T > box_
Constructor & Destructor Documentation
Sphere() [1/2]
template<class T > Sphere< T >::Sphere inline
~Sphere()
template<class T > Sphere< T >::~Sphere inline
Sphere() [2/2]
template<class T > template<class B > Sphere< T >::Sphere (B x, B y, B z, B radius) inline
Member Function Documentation
box()
template<class T > const Box< T > & Sphere< T >::box () const inline
Referenced by Query::exec(), and Page::selectSphere().
clear()
template<class T > void Sphere< T >::clear inline
empty()
template<class T > bool Sphere< T >::empty () const inline
Referenced by Query::exec(), Page::select(), and Page::selectSphere().
isInside()
template<class T > bool Sphere< T >::isInside (T x, T y, T z) const inline
Referenced by Page::selectSphere().
set()
template<class T > void Sphere< T >::set (T x, T y, T z, T radius) inline
Referenced by Query::selectSphere().
validate()
template<class T > void Sphere< T >::validate inline protected
Member Data Documentation
box_
template<class T > Box<T> Sphere< T >::box_ protected
Referenced by Sphere< T >::box(), and Sphere< T >::empty().
radius_
template<class T > T Sphere< T >::radius_ protected
x_
template<class T > T Sphere< T >::x_ protected
y_
template<class T > T Sphere< T >::y_ protected
z_
template<class T > T Sphere< T >::z_ protected
The documentation for this class was generated from the following file:
Sphere.hpp