3D Forest: ViewerViewports Class Reference
ViewerViewports Class Reference
#include <ViewerViewports.hpp>
Inherits QWidget.
Public Types
enum ViewLayout { VIEW_LAYOUT_SINGLE , VIEW_LAYOUT_TWO_COLUMNS , VIEW_LAYOUT_GRID , VIEW_LAYOUT_THREE_ROWS_RIGHT }
Signals
void cameraChanged (size_t viewportId)
Public Member Functions
ViewerViewports (QWidget *parent=nullptr)
~ViewerViewports ()
void setLayout (ViewLayout viewLayout)
void setViewOrthographic ()
void setViewPerspective ()
void setViewTop ()
void setViewFront ()
void setViewRight ()
void setView3d ()
void setViewResetDistance ()
void setViewResetCenter ()
void selectViewport (ViewerOpenGLViewport *viewport)
size_t selectedViewportId () const
std::vector< Camera > camera (size_t viewportId) const
std::vector< Camera > camera () const
void updateScene (Editor *editor)
void resetScene (Editor *editor, bool resetView)
void resetViewport (Editor *editor, size_t viewportId, bool resetView)
Protected Member Functions
void paintEvent (QPaintEvent *event) override
void resizeEvent (QResizeEvent *event) override
void showEvent (QShowEvent *event) override
void hideEvent (QHideEvent *event) override
void initializeViewports ()
ViewerOpenGLViewport * createViewport (size_t viewportId)
ViewerOpenGLViewport * selectedViewport ()
const ViewerOpenGLViewport * selectedViewport () const
Protected Attributes
std::vector< ViewerOpenGLViewport * > viewports_
Member Enumeration Documentation
ViewLayout
enum ViewerViewports::ViewLayout
Enumerator
VIEW_LAYOUT_SINGLE
VIEW_LAYOUT_TWO_COLUMNS
VIEW_LAYOUT_GRID
VIEW_LAYOUT_THREE_ROWS_RIGHT
Constructor & Destructor Documentation
ViewerViewports()
ViewerViewports::ViewerViewports (QWidget * parent = nullptr) explicit
~ViewerViewports()
ViewerViewports::~ViewerViewports ()
Member Function Documentation
camera() [1/2]
std::vector< Camera > ViewerViewports::camera () const
camera() [2/2]
std::vector< Camera > ViewerViewports::camera (size_t viewportId) const
Referenced by ViewerPlugin::camera(), and ViewerPlugin::camera().
cameraChanged
void ViewerViewports::cameraChanged (size_t viewportId) signal
Referenced by ViewerOpenGLViewport::cameraChanged().
createViewport()
ViewerOpenGLViewport * ViewerViewports::createViewport (size_t viewportId) protected
Referenced by setLayout().
hideEvent()
void ViewerViewports::hideEvent (QHideEvent * event) override protected
initializeViewports()
void ViewerViewports::initializeViewports () protected
Referenced by ViewerViewports().
paintEvent()
void ViewerViewports::paintEvent (QPaintEvent * event) override protected
resetScene()
void ViewerViewports::resetScene (Editor * editor, bool resetView)
Referenced by ViewerPlugin::resetScene().
resetViewport()
void ViewerViewports::resetViewport (Editor * editor, size_t viewportId, bool resetView)
Referenced by ViewerPlugin::slotViewLayout().
resizeEvent()
void ViewerViewports::resizeEvent (QResizeEvent * event) override protected
selectedViewport() [1/2]
ViewerOpenGLViewport * ViewerViewports::selectedViewport () protected
Referenced by setView3d(), setViewFront(), setViewOrthographic(), setViewPerspective(), setViewResetCenter(), setViewResetDistance(), setViewRight(), and setViewTop().
selectedViewport() [2/2]
const ViewerOpenGLViewport * ViewerViewports::selectedViewport () const protected
selectedViewportId()
size_t ViewerViewports::selectedViewportId () const
selectViewport()
void ViewerViewports::selectViewport (ViewerOpenGLViewport * viewport)
Referenced by ViewerOpenGLViewport::setFocus().
setLayout()
void ViewerViewports::setLayout (ViewLayout viewLayout)
Referenced by initializeViewports(), and ViewerPlugin::slotViewLayout().
setView3d()
void ViewerViewports::setView3d ()
Referenced by ViewerPlugin::slotView3d().
setViewFront()
void ViewerViewports::setViewFront ()
Referenced by ViewerPlugin::slotViewFront().
setViewOrthographic()
void ViewerViewports::setViewOrthographic ()
Referenced by ViewerPlugin::slotViewOrthographic().
setViewPerspective()
void ViewerViewports::setViewPerspective ()
Referenced by ViewerPlugin::slotViewPerspective().
setViewResetCenter()
void ViewerViewports::setViewResetCenter ()
Referenced by ViewerPlugin::slotViewResetCenter().
setViewResetDistance()
void ViewerViewports::setViewResetDistance ()
Referenced by ViewerPlugin::slotViewResetDistance().
setViewRight()
void ViewerViewports::setViewRight ()
Referenced by ViewerPlugin::slotViewRight().
setViewTop()
void ViewerViewports::setViewTop ()
Referenced by ViewerPlugin::slotViewTop().
showEvent()
void ViewerViewports::showEvent (QShowEvent * event) override protected
updateScene()
void ViewerViewports::updateScene (Editor * editor)
Referenced by ViewerPlugin::updateScene().
Member Data Documentation
viewports_
std::vector<ViewerOpenGLViewport *> ViewerViewports::viewports_ protected
Referenced by camera(), camera(), resetScene(), resetViewport(), selectedViewport(), selectedViewport(), selectedViewportId(), selectViewport(), setLayout(), and updateScene().
The documentation for this class was generated from the following files:
ViewerViewports.hpp
ViewerViewports.cpp