3D Forest: Editor Class Reference
Editor Class Reference
#include <Editor.hpp>
Public Types
enum Type {
TYPE_CLASSIFICATION , TYPE_CLIP_FILTER , TYPE_DATA_SET , TYPE_DESCRIPTOR ,
TYPE_ELEVATION , TYPE_INTENSITY , TYPE_SEGMENT , TYPE_PROJECT_NAME ,
TYPE_SETTINGS
}
Public Member Functions
Editor ()
~Editor ()
void open (const std::string &path, const SettingsImport &settings=SettingsImport())
void saveProject (const std::string &path)
const std::string & projectPath () const
const std::string & projectName () const
bool unsavedChanges () const
void close ()
void applyFilters ()
const Datasets & datasets () const
Datasets & datasets ()
void setDatasets (const Datasets &datasets)
const QueryFilterSet & datasetsFilter () const
void setDatasetsFilter (const QueryFilterSet &filter)
const Region & clipFilter () const
void setClipFilter (const Region &clipFilter)
void resetClipFilter ()
Box< double > clipBoundary () const
const Box< double > & boundary () const
const Range< double > & elevationFilter () const
void setElevationFilter (const Range< double > &elevationFilter)
const Range< double > & descriptorFilter () const
void setDescriptorFilter (const Range< double > &descriptorFilter)
const Range< double > & intensityFilter () const
void setIntensityFilter (const Range< double > &intensityFilter)
const Classifications & classifications () const
void setClassifications (const Classifications &classifications)
const QueryFilterSet & classificationsFilter () const
void setClassificationsFilter (const QueryFilterSet &filter)
const Segments & segments () const
void setSegments (const Segments &segments)
const QueryFilterSet & segmentsFilter () const
void setSegmentsFilter (const QueryFilterSet &filter)
const Settings & settings () const
void setSettingsView (const SettingsView &settingsView)
void setSettingsUnits (const SettingsUnits &settingsUnits)
void addModifier (ModifierInterface *modifier)
void runModifiers (Page *page)
void viewportsResize (size_t n)
Viewports & viewports ()
const Viewports & viewports () const
std::shared_ptr< PageData > readPage (size_t dataset, size_t index)
void erasePage (size_t dataset, size_t index)
Public Attributes
std::mutex mutex_
Protected Member Functions
void openProject (const std::string &path)
void openDataset (const std::string &path, const SettingsImport &settings=SettingsImport())
void setProjectPath (const std::string &projectPath)
void updateAfterSet ()
void updateAfterRead ()
Protected Attributes
std::string projectPath_
std::string projectName_
bool unsavedChanges_
Datasets datasets_
Dataset::Range datasetsRange_
Segments segments_
Settings settings_
Classifications classifications_
Region clipFilter_
Range< double > elevationFilter_
Range< double > descriptorFilter_
Range< double > intensityFilter_
QueryFilterSet classificationsFilter_
QueryFilterSet datasetsFilter_
QueryFilterSet segmentsFilter_
std::vector< ModifierInterface * > modifiers_
Viewports viewports_
PageManager pageManager_
Member Enumeration Documentation
Type
enum Editor::Type
Editor Data Type.
Enumerator
TYPE_CLASSIFICATION
TYPE_CLIP_FILTER
TYPE_DATA_SET
TYPE_DESCRIPTOR
TYPE_ELEVATION
TYPE_INTENSITY
TYPE_SEGMENT
TYPE_PROJECT_NAME
TYPE_SETTINGS
Constructor & Destructor Documentation
Editor()
Editor::Editor ()
~Editor()
Editor::~Editor ()
Member Function Documentation
addModifier()
void Editor::addModifier (ModifierInterface * modifier)
Referenced by MainWindow::loadPlugin().
applyFilters()
void Editor::applyFilters ()
Referenced by updateAfterRead(), and MainWindow::updateData().
boundary()
const Box< double > & Editor::boundary () const inline
Referenced by Query::setGrid(), and ComputeElevationAction::start().
classifications()
const Classifications & Editor::classifications () const inline
Referenced by setClassifications(), and FilterClassificationWidget::slotUpdate().
classificationsFilter()
const QueryFilterSet & Editor::classificationsFilter () const inline
Referenced by FilterClassificationWidget::slotUpdate().
clipBoundary()
Box< double > Editor::clipBoundary () const
Referenced by ComputeHeightMapModifier::apply(), Query::applyCamera(), ComputeHeightMapModifier::applyModifier(), Query::exec(), and Query::setGrid().
clipFilter()
const Region & Editor::clipFilter () const inline
Referenced by Query::applyCamera(), ViewerOpenGLViewport::renderFirstFrame(), setClipFilter(), and FilterAreaBoxWidget::slotUpdate().
close()
void Editor::close ()
Referenced by ProjectFilePlugin::closeProject(), Editor(), and openProject().
datasets() [1/2]
Datasets & Editor::datasets () inline
datasets() [2/2]
const Datasets & Editor::datasets () const inline
Referenced by Query::applyCamera(), Query::exec(), PageData::readPage(), ViewerOpenGLViewport::resetScene(), Page::runColorModifier(), setDatasets(), Query::setGrid(), FilterFilesWidget::slotUpdate(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeElevationAction::start(), PageData::transform(), and PageData::writePage().
datasetsFilter()
const QueryFilterSet & Editor::datasetsFilter () const inline
Referenced by FilterFilesWidget::slotUpdate().
descriptorFilter()
const Range< double > & Editor::descriptorFilter () const inline
Referenced by setDescriptorFilter(), and FilterDescriptorWidget::slotUpdate().
elevationFilter()
const Range< double > & Editor::elevationFilter () const inline
Referenced by ComputeHeightMapModifier::applyModifier(), setElevationFilter(), and FilterElevationWidget::slotUpdate().
erasePage()
void Editor::erasePage (size_t dataset, size_t index)
Referenced by Page::~Page().
intensityFilter()
const Range< double > & Editor::intensityFilter () const inline
Referenced by setIntensityFilter(), and FilterIntensityWidget::slotUpdate().
open()
void Editor::open (const std::string & path, const SettingsImport & settings = SettingsImport())
Referenced by ProjectFilePlugin::openProject().
openDataset()
void Editor::openDataset (const std::string & path, const SettingsImport & settings = SettingsImport()) protected
Referenced by open().
openProject()
void Editor::openProject (const std::string & path) protected
Referenced by open().
projectName()
const std::string & Editor::projectName () const inline
projectPath()
const std::string & Editor::projectPath () const inline
Referenced by MainWindow::MainWindow(), openDataset(), ProjectFilePlugin::saveProject(), setProjectPath(), and MainWindow::updateNewProject().
readPage()
std::shared_ptr< PageData > Editor::readPage (size_t dataset, size_t index)
Referenced by Page::readPage().
resetClipFilter()
void Editor::resetClipFilter ()
runModifiers()
void Editor::runModifiers (Page * page)
Referenced by Page::runModifiers().
saveProject()
void Editor::saveProject (const std::string & path)
Referenced by ProjectFilePlugin::saveProject().
segments()
const Segments & Editor::segments () const inline
Referenced by Page::queryWhereSegment(), ViewerOpenGLViewport::renderAttributes(), ViewerOpenGLViewport::renderSegments(), Page::runColorModifier(), setSegments(), FilterTreesWidget::slotUpdate(), TreeTableWidget::slotUpdate(), ComputeTreeAttributesAction::stepPointsToTrees(), and ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes().
segmentsFilter()
const QueryFilterSet & Editor::segmentsFilter () const inline
Referenced by ViewerOpenGLViewport::renderAttributes(), ViewerOpenGLViewport::renderSegments(), and FilterTreesWidget::slotUpdate().
setClassifications()
void Editor::setClassifications (const Classifications & classifications)
Referenced by FilterClassificationWidget::dataChanged().
setClassificationsFilter()
void Editor::setClassificationsFilter (const QueryFilterSet & filter)
Referenced by FilterClassificationWidget::dataChanged(), and FilterClassificationWidget::filterChanged().
setClipFilter()
void Editor::setClipFilter (const Region & clipFilter)
Referenced by FilterAreaBoxWidget::filterChanged(), resetClipFilter(), and FilterAreaBoxWidget::setFilterEnabled().
setDatasets()
void Editor::setDatasets (const Datasets & datasets)
Referenced by FilterFilesWidget::dataChanged().
setDatasetsFilter()
void Editor::setDatasetsFilter (const QueryFilterSet & filter)
Referenced by FilterFilesWidget::dataChanged(), and FilterFilesWidget::filterChanged().
setDescriptorFilter()
void Editor::setDescriptorFilter (const Range< double > & descriptorFilter)
Referenced by FilterDescriptorWidget::filterChanged().
setElevationFilter()
void Editor::setElevationFilter (const Range< double > & elevationFilter)
Referenced by FilterElevationWidget::filterChanged(), ComputeElevationAction::stepComputeElevation(), ComputeClassificationAction::stepResetPoints(), and ComputeElevationAction::stepResetPoints().
setIntensityFilter()
void Editor::setIntensityFilter (const Range< double > & intensityFilter)
Referenced by FilterIntensityWidget::filterChanged().
setProjectPath()
void Editor::setProjectPath (const std::string & projectPath) protected
Referenced by close(), openDataset(), and openProject().
setSegments()
void Editor::setSegments (const Segments & segments)
Referenced by FilterTreesWidget::dataChanged(), ComputeSegmentationNNAction::stepCreateSegments(), ComputeSegmentationNNAction::stepResetPoints(), and ComputeTreeAttributesAction::stepUpdateComputeTreeAttributes().
setSegmentsFilter()
void Editor::setSegmentsFilter (const QueryFilterSet & filter)
Referenced by FilterTreesWidget::dataChanged(), FilterTreesWidget::filterChanged(), ComputeSegmentationNNAction::stepCreateSegments(), and ComputeSegmentationNNAction::stepResetPoints().
setSettingsUnits()
void Editor::setSettingsUnits (const SettingsUnits & settingsUnits)
Referenced by SettingsUnitsWidget::dataChanged(), and updateAfterRead().
setSettingsView()
void Editor::setSettingsView (const SettingsView & settingsView)
Referenced by SettingsViewWidget::dataChanged().
settings()
const Settings & Editor::settings () const inline
Referenced by open(), openDataset(), TreeTableExportDialog::properties(), ViewerOpenGLViewport::renderAttributes(), ViewerOpenGLViewport::renderFirstFrame(), ViewerOpenGLViewport::renderSceneSettingsDisable(), ViewerOpenGLViewport::renderSceneSettingsEnable(), Page::runColorModifier(), FilterElevationWidget::setElevation(), FilterAreaBoxWidget::setRegion(), TreeTableWidget::setRow(), FilterTreesTreeWidget::setSegment(), FilterAreaBoxWidget::slotRangeIntermediateMaximumValue(), FilterElevationWidget::slotRangeIntermediateMaximumValue(), FilterAreaBoxWidget::slotRangeIntermediateMinimumValue(), FilterElevationWidget::slotRangeIntermediateMinimumValue(), SettingsUnitsWidget::slotUpdate(), SettingsViewWidget::slotUpdate(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), and ComputeElevationAction::start().
unsavedChanges()
bool Editor::unsavedChanges () const inline
Referenced by ProjectFilePlugin::closeProject().
updateAfterRead()
void Editor::updateAfterRead () protected
Referenced by openDataset(), and openProject().
updateAfterSet()
void Editor::updateAfterSet () protected
Referenced by setDatasets(), and updateAfterRead().
viewports() [1/2]
Viewports & Editor::viewports () inline
Referenced by ExportFileAction::initialize(), RenderThread::next(), ViewerOpenGLViewport::renderScene(), ComputeHeightMapModifier::setPreviewEnabled(), EditPlugin::slotResetElevation(), ComputeClassificationAction::stepCountPoints(), ComputeDescriptorAction::stepCountPoints(), ComputeElevationAction::stepCountPoints(), ComputeSegmentationNNAction::stepCountPoints(), MainWindow::update(), MainWindow::updateData(), MainWindow::updateFilter(), MainWindow::updateModifiers(), and MainWindow::updateRender().
viewports() [2/2]
const Viewports & Editor::viewports () const inline
viewportsResize()
void Editor::viewportsResize (size_t n)
Referenced by Editor(), and ViewerPlugin::slotViewLayout().
Member Data Documentation
classifications_
Classifications Editor::classifications_ protected
Referenced by close(), and setClassifications().
classificationsFilter_
QueryFilterSet Editor::classificationsFilter_ protected
Referenced by applyFilters(), close(), and setClassificationsFilter().
clipFilter_
Region Editor::clipFilter_ protected
Referenced by applyFilters(), clipBoundary(), close(), resetClipFilter(), setClipFilter(), updateAfterRead(), and updateAfterSet().
datasets_
Datasets Editor::datasets_ protected
Referenced by close(), openDataset(), openProject(), saveProject(), setDatasets(), updateAfterRead(), and updateAfterSet().
datasetsFilter_
QueryFilterSet Editor::datasetsFilter_ protected
Referenced by applyFilters(), close(), openDataset(), openProject(), and setDatasetsFilter().
datasetsRange_
Dataset::Range Editor::datasetsRange_ protected
Referenced by updateAfterSet().
descriptorFilter_
Range<double> Editor::descriptorFilter_ protected
Referenced by applyFilters(), close(), setDescriptorFilter(), and updateAfterRead().
elevationFilter_
Range<double> Editor::elevationFilter_ protected
Referenced by applyFilters(), close(), setElevationFilter(), updateAfterRead(), and updateAfterSet().
intensityFilter_
Range<double> Editor::intensityFilter_ protected
Referenced by applyFilters(), close(), setIntensityFilter(), and updateAfterRead().
modifiers_
std::vector<ModifierInterface *> Editor::modifiers_ protected
Referenced by addModifier(), and runModifiers().
mutex_
std::mutex Editor::mutex_
Referenced by ComputeHeightMapModifier::apply(), RenderThread::next(), ViewerOpenGLViewport::renderScene(), ComputeHeightMapModifier::setPreviewEnabled(), MainWindow::slotRender(), and MainWindow::updateNewProject().
pageManager_
PageManager Editor::pageManager_ protected
Referenced by erasePage(), and readPage().
projectName_
std::string Editor::projectName_ protected
Referenced by close(), openProject(), and saveProject().
projectPath_
std::string Editor::projectPath_ protected
Referenced by openDataset(), openProject(), and setProjectPath().
segments_
Segments Editor::segments_ protected
Referenced by close(), openProject(), saveProject(), setSegments(), and updateAfterRead().
segmentsFilter_
QueryFilterSet Editor::segmentsFilter_ protected
Referenced by applyFilters(), close(), setSegmentsFilter(), and updateAfterRead().
settings_
Settings Editor::settings_ protected
Referenced by openProject(), saveProject(), setSettingsUnits(), setSettingsView(), and updateAfterRead().
unsavedChanges_
bool Editor::unsavedChanges_ protected
Referenced by close(), openDataset(), saveProject(), setClassifications(), setDatasets(), setSegments(), setSettingsUnits(), and setSettingsView().
viewports_
Viewports Editor::viewports_ protected
Referenced by applyFilters(), close(), setClassificationsFilter(), setClipFilter(), setDatasetsFilter(), setDescriptorFilter(), setElevationFilter(), setIntensityFilter(), setSegmentsFilter(), and viewportsResize().
The documentation for this class was generated from the following files:
Editor.hpp
Editor.cpp