3D Forest: ComputeTreeAttributesLeastSquaredRegression Class Reference
ComputeTreeAttributesLeastSquaredRegression Class Reference
#include <ComputeTreeAttributesLeastSquaredRegression.hpp>
Classes
class FittingCircle
Static Public Member Functions
static void taubinFit (FittingCircle &circle, const std::vector< double > &points, const ComputeTreeAttributesParameters &parameters)
static void geometricCircle (FittingCircle &circle, const std::vector< double > &points, const ComputeTreeAttributesParameters &parameters)
static double sigma (FittingCircle &circle, const std::vector< double > &points)
Member Function Documentation
geometricCircle()
void ComputeTreeAttributesLeastSquaredRegression::geometricCircle (FittingCircle & circle, const std::vector< double > & points, const ComputeTreeAttributesParameters & parameters) static
Referenced by ComputeTreeAttributesAction::calculateDbh().
sigma()
double ComputeTreeAttributesLeastSquaredRegression::sigma (FittingCircle & circle, const std::vector< double > & points) static
Referenced by geometricCircle().
taubinFit()
void ComputeTreeAttributesLeastSquaredRegression::taubinFit (FittingCircle & circle, const std::vector< double > & points, const ComputeTreeAttributesParameters & parameters) static
Referenced by ComputeTreeAttributesAction::calculateDbh().
The documentation for this class was generated from the following files:
ComputeTreeAttributesLeastSquaredRegression.hpp
ComputeTreeAttributesLeastSquaredRegression.cpp