3D Forest: ProjectNavigatorClassifications Class Reference
ProjectNavigatorClassifications Class Reference
#include <ProjectNavigatorClassifications.hpp>
Inherits QWidget.
Public Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Public Slots
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
void slotUpdate ()
Public Member Functions
ProjectNavigatorClassifications (MainWindow *mainWindow)
Protected Member Functions
void dataChanged ()
void filterChanged ()
void updateTree ()
void block ()
void unblock ()
void addItem (size_t i)
void setClassifications (const Classifications &classifications)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Classifications classifications_
Member Enumeration Documentation
Column
enum ProjectNavigatorClassifications::Column
Project Navigator Classifications Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorClassifications()
ProjectNavigatorClassifications::ProjectNavigatorClassifications (MainWindow * mainWindow)
Member Function Documentation
addItem()
void ProjectNavigatorClassifications::addItem (size_t i) protected
Referenced by setClassifications().
block()
void ProjectNavigatorClassifications::block () protected
Referenced by setClassifications(), and updateTree().
dataChanged()
void ProjectNavigatorClassifications::dataChanged () protected
filterChanged()
void ProjectNavigatorClassifications::filterChanged () protected
Referenced by slotHide(), slotItemChanged(), and slotShow().
setClassifications()
void ProjectNavigatorClassifications::setClassifications (const Classifications & classifications) protected
Referenced by slotUpdate().
slotHide
void ProjectNavigatorClassifications::slotHide () slot
Referenced by ProjectNavigatorClassifications().
slotItemChanged
void ProjectNavigatorClassifications::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorClassifications::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorClassifications::slotSelectAll () slot
Referenced by ProjectNavigatorClassifications().
slotSelectInvert
void ProjectNavigatorClassifications::slotSelectInvert () slot
Referenced by ProjectNavigatorClassifications().
slotSelectNone
void ProjectNavigatorClassifications::slotSelectNone () slot
Referenced by ProjectNavigatorClassifications().
slotShow
void ProjectNavigatorClassifications::slotShow () slot
Referenced by ProjectNavigatorClassifications().
slotUpdate
void ProjectNavigatorClassifications::slotUpdate () slot
Referenced by ProjectNavigatorClassifications().
unblock()
void ProjectNavigatorClassifications::unblock () protected
Referenced by setClassifications(), and updateTree().
updateTree()
void ProjectNavigatorClassifications::updateTree () protected
Member Data Documentation
classifications_
Classifications ProjectNavigatorClassifications::classifications_ protected
Referenced by addItem(), dataChanged(), filterChanged(), setClassifications(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ProjectNavigatorClassifications::hideButton_ protected
Referenced by ProjectNavigatorClassifications(), and slotItemSelectionChanged().
mainWindow_
MainWindow* ProjectNavigatorClassifications::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), ProjectNavigatorClassifications(), and slotUpdate().
selectAllButton_
QToolButton* ProjectNavigatorClassifications::selectAllButton_ protected
Referenced by ProjectNavigatorClassifications().
selectInvertButton_
QToolButton* ProjectNavigatorClassifications::selectInvertButton_ protected
Referenced by ProjectNavigatorClassifications().
selectNoneButton_
QToolButton* ProjectNavigatorClassifications::selectNoneButton_ protected
Referenced by ProjectNavigatorClassifications().
showButton_
QToolButton* ProjectNavigatorClassifications::showButton_ protected
Referenced by ProjectNavigatorClassifications(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorClassifications::tree_ protected
Referenced by addItem(), block(), ProjectNavigatorClassifications(), setClassifications(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
The documentation for this class was generated from the following files:
ProjectNavigatorClassifications.hpp
ProjectNavigatorClassifications.cpp