3D Forest: LasFile::Format Class Reference
LasFile::Format Class Reference
#include <LasFile.hpp>
Public Member Functions
Format ()
Format (uint32_t flags)
void set (uint32_t flags)
bool has (uint32_t attr) const
uint8_t las () const
Private Attributes
uint32_t flags_
Constructor & Destructor Documentation
Format() [1/2]
LasFile::Format::Format () inline
Format() [2/2]
LasFile::Format::Format (uint32_t flags) inline
Member Function Documentation
has()
bool LasFile::Format::has (uint32_t attr) const inline
Referenced by ExportFileFormatCsv::create(), las(), and ExportFileFormatCsv::write().
las()
uint8_t LasFile::Format::las () const
Referenced by ExportFileFormatLas::write().
set()
void LasFile::Format::set (uint32_t flags) inline
Referenced by ExportFileProperties::clear().
Member Data Documentation
flags_
uint32_t LasFile::Format::flags_ private
The documentation for this class was generated from the following files:
LasFile.hpp
LasFile.cpp