3D Forest: SettingsUnits Class Reference
SettingsUnits Class Reference
#include <SettingsUnits.hpp>
Public Member Functions
SettingsUnits ()
void setLasFileScaling (const Vector3< double > &scaling)
const Vector3< double > & pointsPerMeter () const
bool apply (const SettingsUnits &newSettings)
Public Attributes
Vector3< double > pointsPerMeterLas
Vector3< double > pointsPerMeterUser
bool userDefined
Constructor & Destructor Documentation
SettingsUnits()
SettingsUnits::SettingsUnits ()
Member Function Documentation
apply()
bool SettingsUnits::apply (const SettingsUnits & newSettings)
Referenced by Settings::units().
pointsPerMeter()
const Vector3< double > & SettingsUnits::pointsPerMeter () const
Referenced by TreeTableExportDialog::properties(), FilterElevationWidget::setElevation(), FilterAreaBoxWidget::setRegion(), TreeTableWidget::setRow(), FilterTreesTreeWidget::setSegment(), FilterAreaBoxWidget::slotRangeIntermediateMaximumValue(), FilterElevationWidget::slotRangeIntermediateMaximumValue(), FilterAreaBoxWidget::slotRangeIntermediateMinimumValue(), FilterElevationWidget::slotRangeIntermediateMinimumValue(), ComputeClassificationAction::start(), ComputeDescriptorAction::start(), ComputeSegmentationNNAction::start(), ComputeTreeAttributesAction::start(), and ComputeElevationAction::start().
setLasFileScaling()
void SettingsUnits::setLasFileScaling (const Vector3< double > & scaling)
Referenced by Editor::updateAfterRead().
Member Data Documentation
pointsPerMeterLas
Vector3<double> SettingsUnits::pointsPerMeterLas
Referenced by apply(), pointsPerMeter(), setLasFileScaling(), SettingsUnitsWidget::setUnitsSettings(), and SettingsUnitsWidget::slotIntermediateLas().
pointsPerMeterUser
Vector3<double> SettingsUnits::pointsPerMeterUser
Referenced by apply(), pointsPerMeter(), SettingsUnitsWidget::setUnitsSettings(), and SettingsUnitsWidget::slotIntermediateUser().
userDefined
bool SettingsUnits::userDefined
Referenced by apply(), pointsPerMeter(), SettingsUnitsWidget::SettingsUnitsWidget(), SettingsUnitsWidget::setUnitsSettings(), and SettingsUnitsWidget::slotUserDefined().
The documentation for this class was generated from the following files:
SettingsUnits.hpp
SettingsUnits.cpp