3D Forest: ProjectNavigatorItemFiles Class Reference
ProjectNavigatorItemFiles Class Reference
#include <ProjectNavigatorItemFiles.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ProjectNavigatorItemFiles (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_DATE_CREATED ,
COLUMN_LAST
}
Protected Member Functions
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
void setDatasets (const Datasets &datasets)
Protected Attributes
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Datasets datasets_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ProjectNavigatorItemFiles::Column protected
Project Navigator Files Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_DATE_CREATED
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorItemFiles()
ProjectNavigatorItemFiles::ProjectNavigatorItemFiles (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ProjectNavigatorItemFiles::addTreeItem (size_t index) protected
Referenced by setDatasets().
block()
void ProjectNavigatorItemFiles::block () protected
Referenced by setDatasets(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemFiles::colorSource () const inline virtual
Implements ProjectNavigatorItem.
dataChanged()
void ProjectNavigatorItemFiles::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ProjectNavigatorItemFiles::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ProjectNavigatorItemFiles::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemFiles::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
identifier()
size_t ProjectNavigatorItemFiles::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
index()
size_t ProjectNavigatorItemFiles::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), and slotDelete().
isFilterEnabled()
bool ProjectNavigatorItemFiles::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setDatasets()
void ProjectNavigatorItemFiles::setDatasets (const Datasets & datasets) protected
Referenced by slotUpdate().
setFilterEnabled()
void ProjectNavigatorItemFiles::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotAdd
void ProjectNavigatorItemFiles::slotAdd () slot
Referenced by ProjectNavigatorItemFiles().
slotDelete
void ProjectNavigatorItemFiles::slotDelete () slot
Referenced by ProjectNavigatorItemFiles().
slotHide
void ProjectNavigatorItemFiles::slotHide () slot
Referenced by ProjectNavigatorItemFiles().
slotItemChanged
void ProjectNavigatorItemFiles::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorItemFiles::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorItemFiles::slotSelectAll () slot
Referenced by ProjectNavigatorItemFiles().
slotSelectInvert
void ProjectNavigatorItemFiles::slotSelectInvert () slot
Referenced by ProjectNavigatorItemFiles().
slotSelectNone
void ProjectNavigatorItemFiles::slotSelectNone () slot
Referenced by ProjectNavigatorItemFiles(), and slotDelete().
slotShow
void ProjectNavigatorItemFiles::slotShow () slot
Referenced by ProjectNavigatorItemFiles().
slotUpdate
void ProjectNavigatorItemFiles::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemFiles().
unblock()
void ProjectNavigatorItemFiles::unblock () protected
Referenced by setDatasets(), and updateTree().
updateTree()
void ProjectNavigatorItemFiles::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ProjectNavigatorItemFiles::addButton_ protected
Referenced by ProjectNavigatorItemFiles().
datasets_
Datasets ProjectNavigatorItemFiles::datasets_ protected
Referenced by addTreeItem(), dataChanged(), index(), setDatasets(), and slotDelete().
deleteButton_
QToolButton* ProjectNavigatorItemFiles::deleteButton_ protected
Referenced by ProjectNavigatorItemFiles(), and slotItemSelectionChanged().
filter_
QueryFilterSet ProjectNavigatorItemFiles::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setFilterEnabled(), slotDelete(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ProjectNavigatorItemFiles::hideButton_ protected
Referenced by ProjectNavigatorItemFiles(), and slotItemSelectionChanged().
selectAllButton_
QToolButton* ProjectNavigatorItemFiles::selectAllButton_ protected
Referenced by ProjectNavigatorItemFiles().
selectInvertButton_
QToolButton* ProjectNavigatorItemFiles::selectInvertButton_ protected
Referenced by ProjectNavigatorItemFiles().
selectNoneButton_
QToolButton* ProjectNavigatorItemFiles::selectNoneButton_ protected
Referenced by ProjectNavigatorItemFiles().
showButton_
QToolButton* ProjectNavigatorItemFiles::showButton_ protected
Referenced by ProjectNavigatorItemFiles(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorItemFiles::tree_ protected
Referenced by addTreeItem(), block(), ProjectNavigatorItemFiles(), setDatasets(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ProjectNavigatorItemFiles::updatesEnabled_ protected
Referenced by ProjectNavigatorItemFiles(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ProjectNavigatorItemFiles.hpp
ProjectNavigatorItemFiles.cpp