3D Forest: ProjectNavigatorFiles Class Reference
ProjectNavigatorFiles Class Reference
#include <ProjectNavigatorFiles.hpp>
Inherits QWidget.
Public Types
enum Column {
COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_DATE_CREATED ,
COLUMN_LAST
}
Public Slots
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
void slotUpdate ()
Public Member Functions
ProjectNavigatorFiles (MainWindow *mainWindow)
Protected Member Functions
void dataChanged ()
void filterChanged ()
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addItem (size_t i)
void setDatasets (const Datasets &datasets)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Datasets datasets_
Member Enumeration Documentation
Column
enum ProjectNavigatorFiles::Column
Project Navigator Files Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_DATE_CREATED
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorFiles()
ProjectNavigatorFiles::ProjectNavigatorFiles (MainWindow * mainWindow)
Member Function Documentation
addItem()
void ProjectNavigatorFiles::addItem (size_t i) protected
Referenced by setDatasets().
block()
void ProjectNavigatorFiles::block () protected
Referenced by setDatasets(), and updateTree().
dataChanged()
void ProjectNavigatorFiles::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ProjectNavigatorFiles::filterChanged () protected
Referenced by slotHide(), slotItemChanged(), and slotShow().
index()
size_t ProjectNavigatorFiles::index (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
setDatasets()
void ProjectNavigatorFiles::setDatasets (const Datasets & datasets) protected
Referenced by slotUpdate().
slotAdd
void ProjectNavigatorFiles::slotAdd () slot
Referenced by ProjectNavigatorFiles().
slotDelete
void ProjectNavigatorFiles::slotDelete () slot
Referenced by ProjectNavigatorFiles().
slotHide
void ProjectNavigatorFiles::slotHide () slot
Referenced by ProjectNavigatorFiles().
slotItemChanged
void ProjectNavigatorFiles::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorFiles::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorFiles::slotSelectAll () slot
Referenced by ProjectNavigatorFiles().
slotSelectInvert
void ProjectNavigatorFiles::slotSelectInvert () slot
Referenced by ProjectNavigatorFiles().
slotSelectNone
void ProjectNavigatorFiles::slotSelectNone () slot
Referenced by ProjectNavigatorFiles(), and slotDelete().
slotShow
void ProjectNavigatorFiles::slotShow () slot
Referenced by ProjectNavigatorFiles().
slotUpdate
void ProjectNavigatorFiles::slotUpdate () slot
Referenced by ProjectNavigatorFiles().
unblock()
void ProjectNavigatorFiles::unblock () protected
Referenced by setDatasets(), and updateTree().
updateTree()
void ProjectNavigatorFiles::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ProjectNavigatorFiles::addButton_ protected
Referenced by ProjectNavigatorFiles().
datasets_
Datasets ProjectNavigatorFiles::datasets_ protected
Referenced by addItem(), dataChanged(), filterChanged(), index(), setDatasets(), slotDelete(), slotItemChanged(), and updateTree().
deleteButton_
QToolButton* ProjectNavigatorFiles::deleteButton_ protected
Referenced by ProjectNavigatorFiles(), and slotItemSelectionChanged().
hideButton_
QToolButton* ProjectNavigatorFiles::hideButton_ protected
Referenced by ProjectNavigatorFiles(), and slotItemSelectionChanged().
mainWindow_
MainWindow* ProjectNavigatorFiles::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), ProjectNavigatorFiles(), slotAdd(), and slotUpdate().
selectAllButton_
QToolButton* ProjectNavigatorFiles::selectAllButton_ protected
Referenced by ProjectNavigatorFiles().
selectInvertButton_
QToolButton* ProjectNavigatorFiles::selectInvertButton_ protected
Referenced by ProjectNavigatorFiles().
selectNoneButton_
QToolButton* ProjectNavigatorFiles::selectNoneButton_ protected
Referenced by ProjectNavigatorFiles().
showButton_
QToolButton* ProjectNavigatorFiles::showButton_ protected
Referenced by ProjectNavigatorFiles(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorFiles::tree_ protected
Referenced by addItem(), block(), ProjectNavigatorFiles(), setDatasets(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
The documentation for this class was generated from the following files:
ProjectNavigatorFiles.hpp
ProjectNavigatorFiles.cpp