3D Forest: Viewports Class Reference
Viewports Class Reference
#include <Viewports.hpp>
Public Member Functions
Viewports ()
~Viewports ()
size_t size () const
void resize (Editor *editor, size_t n)
void clearContent ()
QueryWhere & where ()
const QueryWhere & where () const
void applyWhereToAll ()
void applyCamera (size_t viewport, const Camera &camera)
void setState (Page::State state)
bool nextState ()
size_t pageSize (size_t viewport) const
Page & page (size_t viewport, size_t index)
Protected Attributes
std::vector< std::shared_ptr< Query > > viewports_
size_t activeViewport_
Constructor & Destructor Documentation
Viewports()
Viewports::Viewports ()
~Viewports()
Viewports::~Viewports ()
Member Function Documentation
applyCamera()
void Viewports::applyCamera (size_t viewport, const Camera & camera)
Referenced by RenderThread::compute().
applyWhereToAll()
void Viewports::applyWhereToAll ()
Referenced by Editor::setClassificationsFilter(), Editor::setClipFilter(), Editor::setDatasetsFilter(), Editor::setDensityRange(), Editor::setDescriptorRange(), Editor::setElevationRange(), Editor::setLayersFilter(), and Editor::updateAfterRead().
clearContent()
void Viewports::clearContent ()
Referenced by Editor::close(), and MainWindow::updateData().
nextState()
bool Viewports::nextState ()
Referenced by RenderThread::compute().
page()
Page & Viewports::page (size_t viewport, size_t index) inline
Referenced by ViewerOpenGLViewport::renderScene().
pageSize()
size_t Viewports::pageSize (size_t viewport) const inline
Referenced by ViewerOpenGLViewport::renderScene().
resize()
void Viewports::resize (Editor * editor, size_t n)
Referenced by Editor::viewportsResize().
setState()
void Viewports::setState (Page::State state)
Referenced by HeightMapModifier::setPreviewEnabled(), ClassificationWindow::slotApply(), MainWindow::update(), MainWindow::updateFilter(), MainWindow::updateModifiers(), and MainWindow::updateRender().
size()
size_t Viewports::size () const inline
Referenced by Editor::setClassificationsFilter(), Editor::setClipFilter(), Editor::setDatasetsFilter(), Editor::setDensityRange(), Editor::setDescriptorRange(), Editor::setElevationRange(), Editor::setLayersFilter(), and Editor::updateAfterRead().
where() [1/2]
QueryWhere & Viewports::where () inline
Referenced by applyWhereToAll(), DensityAction::initialize(), DescriptorAction::initialize(), ExportFileAction::initialize(), Editor::setClassificationsFilter(), Editor::setClipFilter(), Editor::setDatasetsFilter(), Editor::setDensityRange(), Editor::setDescriptorRange(), Editor::setElevationRange(), Editor::setLayersFilter(), and Editor::updateAfterRead().
where() [2/2]
const QueryWhere & Viewports::where () const inline
Member Data Documentation
activeViewport_
size_t Viewports::activeViewport_ protected
Referenced by applyWhereToAll().
viewports_
std::vector<std::shared_ptr<Query> > Viewports::viewports_ protected
Referenced by applyCamera(), applyWhereToAll(), clearContent(), nextState(), resize(), and setState().
The documentation for this class was generated from the following files:
Viewports.hpp
Viewports.cpp