3D Forest: ProjectNavigatorTree Class Reference
ProjectNavigatorTree Class Reference
#include <ProjectNavigatorTree.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotItemChanged (QTreeWidgetItem *item, int column)
void slotItemClicked (QTreeWidgetItem *item, int column)
Public Member Functions
ProjectNavigatorTree (MainWindow *mainWindow)
void addItem (ProjectNavigatorItem *widget)
Private Types
enum Column {
COLUMN_COLOR , COLUMN_FILTER , COLUMN_LABEL , COLUMN_ID ,
COLUMN_LAST
}
Private Member Functions
size_t index (const QTreeWidgetItem *item)
void block ()
void unblock ()
void setTabVisible (size_t index)
void applySettingsIn (const SettingsView &settings)
void applySettingsOut ()
Private Attributes
MainWindow * mainWindow_
QTreeWidget * treeWidget_
QVBoxLayout * tabLayout_
std::vector< ProjectNavigatorItem * > tabList_
SettingsView settings_
Member Enumeration Documentation
Column
enum ProjectNavigatorTree::Column private
Project Navigator Tree Column.
Enumerator
COLUMN_COLOR
COLUMN_FILTER
COLUMN_LABEL
COLUMN_ID
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorTree()
ProjectNavigatorTree::ProjectNavigatorTree (MainWindow * mainWindow)
Member Function Documentation
addItem()
void ProjectNavigatorTree::addItem (ProjectNavigatorItem * widget)
Referenced by ProjectNavigatorWindow::ProjectNavigatorWindow().
applySettingsIn()
void ProjectNavigatorTree::applySettingsIn (const SettingsView & settings) private
Referenced by slotUpdate().
applySettingsOut()
void ProjectNavigatorTree::applySettingsOut () private
Referenced by slotItemChanged().
block()
void ProjectNavigatorTree::block () private
Referenced by addItem(), and applySettingsIn().
index()
size_t ProjectNavigatorTree::index (const QTreeWidgetItem * item) private
Referenced by applySettingsIn(), setTabVisible(), slotItemChanged(), and slotItemClicked().
setTabVisible()
void ProjectNavigatorTree::setTabVisible (size_t index) private
Referenced by slotItemClicked().
slotItemChanged
void ProjectNavigatorTree::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemClicked
void ProjectNavigatorTree::slotItemClicked (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotUpdate
void ProjectNavigatorTree::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorTree().
unblock()
void ProjectNavigatorTree::unblock () private
Referenced by addItem(), and applySettingsIn().
Member Data Documentation
mainWindow_
MainWindow* ProjectNavigatorTree::mainWindow_ private
Referenced by applySettingsOut(), ProjectNavigatorTree(), and slotUpdate().
settings_
SettingsView ProjectNavigatorTree::settings_ private
Referenced by applySettingsIn(), applySettingsOut(), and slotItemChanged().
tabLayout_
QVBoxLayout* ProjectNavigatorTree::tabLayout_ private
Referenced by addItem(), and ProjectNavigatorTree().
tabList_
std::vector<ProjectNavigatorItem *> ProjectNavigatorTree::tabList_ private
Referenced by addItem(), applySettingsIn(), setTabVisible(), and slotItemChanged().
treeWidget_
QTreeWidget* ProjectNavigatorTree::treeWidget_ private
Referenced by addItem(), applySettingsIn(), block(), ProjectNavigatorTree(), and unblock().
The documentation for this class was generated from the following files:
ProjectNavigatorTree.hpp
ProjectNavigatorTree.cpp