3D Forest: LoggerWindow Class Reference
LoggerWindow Class Reference
#include <LoggerWindow.hpp>
Inherits QDockWidget, and LogThreadCallbackInterface.
Public Slots
void slotPrintln (const QString &time, int type, const QString &text, const QString &module, const QString &function)
Signals
void signalPrintln (const QString &time, int type, const QString &text, const QString &module, const QString &function)
Public Member Functions
LoggerWindow (MainWindow *mainWindow)
virtual ~LoggerWindow ()
virtual void println (const LogMessage &message)
virtual void flush ()
Public Member Functions inherited from LogThreadCallbackInterface
virtual ~LogThreadCallbackInterface ()=default
virtual void println (const LogMessage &message)=0
virtual void flush ()=0
Static Public Member Functions
static void EXPORT_GUI install ()
Protected Attributes
MainWindow * mainWindow_
QTextEdit * textEdit_
Constructor & Destructor Documentation
LoggerWindow()
LoggerWindow::LoggerWindow (MainWindow * mainWindow)
~LoggerWindow()
LoggerWindow::~LoggerWindow () virtual
Member Function Documentation
flush()
void LoggerWindow::flush () virtual
Implements LogThreadCallbackInterface.
install()
void LoggerWindow::install () static
println()
void LoggerWindow::println (const LogMessage & message) virtual
Implements LogThreadCallbackInterface.
signalPrintln
void LoggerWindow::signalPrintln (const QString & time, int type, const QString & text, const QString & module, const QString & function) signal
Referenced by LoggerWindow(), and println().
slotPrintln
void LoggerWindow::slotPrintln (const QString & time, int type, const QString & text, const QString & module, const QString & function) slot
Referenced by LoggerWindow().
Member Data Documentation
mainWindow_
MainWindow* LoggerWindow::mainWindow_ protected
Referenced by LoggerWindow().
textEdit_
QTextEdit* LoggerWindow::textEdit_ protected
Referenced by LoggerWindow(), and slotPrintln().
The documentation for this class was generated from the following files:
LoggerWindow.hpp
LoggerWindow.cpp