3D Forest: SettingsPlugin Class Reference
SettingsPlugin Class Reference
#include <SettingsPlugin.hpp>
Inherits QObject.
Public Slots
void slotPlugin ()
Public Member Functions
SettingsPlugin ()
void initialize (MainWindow *mainWindow)
Protected Attributes
MainWindow * mainWindow_
SettingsWindow * settingsWindow_
Constructor & Destructor Documentation
SettingsPlugin()
SettingsPlugin::SettingsPlugin ()
Member Function Documentation
initialize()
void SettingsPlugin::initialize (MainWindow * mainWindow)
Referenced by MainWindow::MainWindow().
slotPlugin
void SettingsPlugin::slotPlugin () slot
Referenced by initialize(), and MainWindow::MainWindow().
Member Data Documentation
mainWindow_
MainWindow* SettingsPlugin::mainWindow_ protected
Referenced by initialize(), and slotPlugin().
settingsWindow_
SettingsWindow* SettingsPlugin::settingsWindow_ protected
Referenced by slotPlugin().
The documentation for this class was generated from the following files:
SettingsPlugin.hpp
SettingsPlugin.cpp