3D Forest: Classifications Class Reference
Classifications Class Reference
#include <Classifications.hpp>
Public Member Functions
Classifications ()
void clear ()
bool isEnabled () const
void setEnabled (bool b)
size_t size () const
bool isEnabled (size_t i) const
void setEnabled (size_t i, bool b)
std::unordered_set< size_t > enabledList () const
const std::string & label (size_t i) const
void setEnabledAll (bool b)
void setInvertAll ()
void read (const Json &in)
Json & write (Json &out) const
Protected Attributes
std::vector< Class > classes_
bool enabled_
Constructor & Destructor Documentation
Classifications()
Classifications::Classifications ()
Member Function Documentation
clear()
void Classifications::clear ()
Referenced by Classifications(), Editor::close(), and read().
enabledList()
std::unordered_set< size_t > Classifications::enabledList () const inline
Referenced by Editor::setClassifications().
isEnabled() [1/2]
bool Classifications::isEnabled () const inline
Referenced by ProjectNavigatorClassifications::addItem(), and ProjectNavigatorClassifications::updateTree().
isEnabled() [2/2]
bool Classifications::isEnabled (size_t i) const inline
label()
const std::string & Classifications::label (size_t i) const inline
Referenced by ProjectNavigatorClassifications::addItem().
read()
void Classifications::read (const Json & in)
Referenced by Editor::openProject().
setEnabled() [1/2]
void Classifications::setEnabled (bool b)
Referenced by ProjectNavigatorClassifications::slotItemChanged().
setEnabled() [2/2]
void Classifications::setEnabled (size_t i, bool b) inline
setEnabledAll()
void Classifications::setEnabledAll (bool b)
setInvertAll()
void Classifications::setInvertAll ()
size()
size_t Classifications::size () const inline
Referenced by ProjectNavigatorClassifications::setClassifications().
write()
Json & Classifications::write (Json & out) const
Referenced by Editor::save().
Member Data Documentation
classes_
std::vector<Class> Classifications::classes_ protected
Referenced by clear(), enabledList(), read(), setEnabledAll(), setInvertAll(), and write().
enabled_
bool Classifications::enabled_ protected
Referenced by read(), setEnabled(), and write().
The documentation for this class was generated from the following files:
Classifications.hpp
Classifications.cpp