3D Forest: ProjectNavigatorLayers Class Reference
ProjectNavigatorLayers Class Reference
#include <ProjectNavigatorLayers.hpp>
Inherits QWidget.
Public Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Public Slots
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
void slotUpdate ()
Public Member Functions
ProjectNavigatorLayers (MainWindow *mainWindow)
Protected Member Functions
void dataChanged ()
void filterChanged ()
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addItem (size_t i)
void setLayers (const Layers &layers)
Protected Attributes
MainWindow * mainWindow_
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Layers layers_
Member Enumeration Documentation
Column
enum ProjectNavigatorLayers::Column
Project Navigator Layers Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorLayers()
ProjectNavigatorLayers::ProjectNavigatorLayers (MainWindow * mainWindow)
Member Function Documentation
addItem()
void ProjectNavigatorLayers::addItem (size_t i) protected
Referenced by setLayers().
block()
void ProjectNavigatorLayers::block () protected
Referenced by setLayers(), and updateTree().
dataChanged()
void ProjectNavigatorLayers::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ProjectNavigatorLayers::filterChanged () protected
Referenced by slotHide(), slotItemChanged(), and slotShow().
index()
size_t ProjectNavigatorLayers::index (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
setLayers()
void ProjectNavigatorLayers::setLayers (const Layers & layers) protected
Referenced by slotUpdate().
slotAdd
void ProjectNavigatorLayers::slotAdd () slot
Referenced by ProjectNavigatorLayers().
slotDelete
void ProjectNavigatorLayers::slotDelete () slot
Referenced by ProjectNavigatorLayers().
slotHide
void ProjectNavigatorLayers::slotHide () slot
Referenced by ProjectNavigatorLayers().
slotItemChanged
void ProjectNavigatorLayers::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorLayers::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorLayers::slotSelectAll () slot
Referenced by ProjectNavigatorLayers().
slotSelectInvert
void ProjectNavigatorLayers::slotSelectInvert () slot
Referenced by ProjectNavigatorLayers().
slotSelectNone
void ProjectNavigatorLayers::slotSelectNone () slot
Referenced by ProjectNavigatorLayers(), and slotDelete().
slotShow
void ProjectNavigatorLayers::slotShow () slot
Referenced by ProjectNavigatorLayers().
slotUpdate
void ProjectNavigatorLayers::slotUpdate () slot
Referenced by ProjectNavigatorLayers().
unblock()
void ProjectNavigatorLayers::unblock () protected
Referenced by setLayers(), and updateTree().
updateTree()
void ProjectNavigatorLayers::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ProjectNavigatorLayers::addButton_ protected
Referenced by ProjectNavigatorLayers().
deleteButton_
QToolButton* ProjectNavigatorLayers::deleteButton_ protected
Referenced by ProjectNavigatorLayers(), and slotItemSelectionChanged().
hideButton_
QToolButton* ProjectNavigatorLayers::hideButton_ protected
Referenced by ProjectNavigatorLayers(), and slotItemSelectionChanged().
layers_
Layers ProjectNavigatorLayers::layers_ protected
Referenced by addItem(), dataChanged(), filterChanged(), index(), setLayers(), slotDelete(), slotItemChanged(), and updateTree().
mainWindow_
MainWindow* ProjectNavigatorLayers::mainWindow_ protected
Referenced by dataChanged(), filterChanged(), ProjectNavigatorLayers(), and slotUpdate().
selectAllButton_
QToolButton* ProjectNavigatorLayers::selectAllButton_ protected
Referenced by ProjectNavigatorLayers().
selectInvertButton_
QToolButton* ProjectNavigatorLayers::selectInvertButton_ protected
Referenced by ProjectNavigatorLayers().
selectNoneButton_
QToolButton* ProjectNavigatorLayers::selectNoneButton_ protected
Referenced by ProjectNavigatorLayers().
showButton_
QToolButton* ProjectNavigatorLayers::showButton_ protected
Referenced by ProjectNavigatorLayers(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorLayers::tree_ protected
Referenced by addItem(), block(), ProjectNavigatorLayers(), setLayers(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
The documentation for this class was generated from the following files:
ProjectNavigatorLayers.hpp
ProjectNavigatorLayers.cpp