3D Forest: LasFile Class Reference
LasFile Class Reference
#include <LasFile.hpp>
Classes
struct AttributesBuffer
class Format
struct Header
struct Point
Public Types
enum Classification {
CLASS_NEVER_CLASSIFIED , CLASS_UNASSIGNED , CLASS_GROUND , CLASS_LOW_VEGETATION ,
CLASS_MEDIUM_VEGETATION , CLASS_HIGH_VEGETATION , CLASS_BUILDING
}
Public Member Functions
LasFile ()
~LasFile ()
void open (const std::string &path)
void create (const std::string &path)
void close ()
bool open () const
void seekPoint (uint64_t index)
void readPoint (Point &pt)
void writePoint (const Point &pt)
uint64_t size () const
uint64_t offset () const
void seek (uint64_t offset)
void seekHeader ()
void seekVlr ()
void seekPointData ()
void seekExtendedVlr ()
void readHeader ()
void writeHeader ()
void readBuffer (uint8_t *buffer, uint64_t nbyte)
void writeBuffer (const uint8_t *buffer, uint64_t nbyte)
void formatBytesToPoint (Point &pt, const uint8_t *buffer) const
void formatPointToBytes (uint8_t *buffer, const Point &pt) const
void createAttributesBuffer (AttributesBuffer &buffer, uint64_t n, bool setZero=false)
void readAttributesBuffer (AttributesBuffer &buffer, uint64_t n)
void writeAttributesBuffer (const AttributesBuffer &buffer, uint64_t n, uint64_t from=0)
void copyAttributesBuffer (AttributesBuffer &dst, const AttributesBuffer &src, uint64_t n, uint64_t to=0, uint64_t from=0)
const std::vector< RecordFile > & attributeFiles () const
void range (size_t id, uint32_t &min, uint32_t &max)
void transform (double &x, double &y, double &z, const Point &pt) const
void transform (double &x, double &y, double &z, const uint8_t *buffer) const
void transformInvert (double &x, double &y, double &z) const
Static Public Member Functions
static void move (const std::string &outputPath, const std::string &inputPath)
static void remove (const std::string &path)
static void create (const std::string &path, const std::vector< LasFile::Point > &points, const std::array< double, 3 > scale={1, 1, 1}, const std::array< double, 3 > offset={0, 0, 0}, uint8_t version_minor=4)
Public Attributes
Header header
Static Public Attributes
static const uint32_t FORMAT_INVALID = 0
static const uint32_t FORMAT_XYZ = 1U << 1
static const uint32_t FORMAT_INTENSITY = 1U << 2
static const uint32_t FORMAT_CLASSIFICATION = 1U << 3
static const uint32_t FORMAT_RGB = 1U << 4
static const uint32_t FORMAT_SEGMENT = 1U << 5
Protected Member Functions
void readHeader (Header &hdr)
void writeHeader (const Header &hdr)
void openAttributeFiles (const std::string &path, bool truncate)
void openAttributeFile (RecordFile &file, const std::string &path, const std::string &name, RecordFile::Type recordType, bool truncate)
Protected Attributes
File file_
std::vector< RecordFile > attributeFiles_
Member Enumeration Documentation
Classification
enum LasFile::Classification
LAS Classification.
Enumerator
CLASS_NEVER_CLASSIFIED
CLASS_UNASSIGNED
CLASS_GROUND
CLASS_LOW_VEGETATION
CLASS_MEDIUM_VEGETATION
CLASS_HIGH_VEGETATION
CLASS_BUILDING
Constructor & Destructor Documentation
LasFile()
LasFile::LasFile ()
~LasFile()
LasFile::~LasFile ()
Member Function Documentation
attributeFiles()
const std::vector< RecordFile > & LasFile::attributeFiles () const inline
Referenced by IndexFileBuilder::openFiles().
close()
void LasFile::close ()
Referenced by ExportFileFormatLas::close(), create(), IndexFileBuilder::stateCreateAttributes(), IndexFileBuilder::stateEnd(), and IndexFileBuilder::stateMove().
copyAttributesBuffer()
void LasFile::copyAttributesBuffer (AttributesBuffer & dst, const AttributesBuffer & src, uint64_t n, uint64_t to = 0, uint64_t from = 0)
Referenced by IndexFileBuilder::stateCopyPoints(), and IndexFileBuilder::stateNodeInsert().
create() [1/2]
void LasFile::create (const std::string & path)
Referenced by ExportFileFormatLas::create(), create(), and IndexFileBuilder::openFiles().
create() [2/2]
void LasFile::create (const std::string & path, const std::vector< LasFile::Point > & points, const std::array< double, 3 > scale = {1, 1, 1}, const std::array< double, 3 > offset = {0, 0, 0}, uint8_t version_minor = 4) static
createAttributesBuffer()
void LasFile::createAttributesBuffer (AttributesBuffer & buffer, uint64_t n, bool setZero = false)
Referenced by PageData::readPage(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateNodeInsert(), and PageData::writePage().
formatBytesToPoint()
void LasFile::formatBytesToPoint (Point & pt, const uint8_t * buffer) const
Referenced by PageData::readPage(), and readPoint().
formatPointToBytes()
void LasFile::formatPointToBytes (uint8_t * buffer, const Point & pt) const
Referenced by writePoint().
move()
void LasFile::move (const std::string & outputPath, const std::string & inputPath) static
Referenced by IndexFileBuilder::stateEnd().
offset()
uint64_t LasFile::offset () const
Referenced by create(), IndexFileBuilder::openFiles(), seek(), seekPoint(), and LasFile::Header::set().
open() [1/2]
bool LasFile::open () const
open() [2/2]
void LasFile::open (const std::string & path)
Referenced by ExportFileFormatLas::open(), IndexFileBuilder::openFiles(), and IndexFileBuilder::stateCreateAttributes().
openAttributeFile()
void LasFile::openAttributeFile (RecordFile & file, const std::string & path, const std::string & name, RecordFile::Type recordType, bool truncate) protected
Referenced by openAttributeFiles().
openAttributeFiles()
void LasFile::openAttributeFiles (const std::string & path, bool truncate) protected
Referenced by create(), and open().
range()
void LasFile::range (size_t id, uint32_t & min, uint32_t & max)
readAttributesBuffer()
void LasFile::readAttributesBuffer (AttributesBuffer & buffer, uint64_t n)
Referenced by PageData::readPage(), IndexFileBuilder::stateCopyAttributes(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateMainSort(), and IndexFileBuilder::stateNodeInsert().
readBuffer()
void LasFile::readBuffer (uint8_t * buffer, uint64_t nbyte)
Referenced by PageData::readPage(), IndexFileBuilder::stateCopy(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateMainInsert(), IndexFileBuilder::stateMainSort(), and IndexFileBuilder::stateNodeInsert().
readHeader() [1/2]
void LasFile::readHeader ()
Referenced by IndexFileBuilder::openFiles(), readHeader(), and IndexFileBuilder::stateCreateAttributes().
readHeader() [2/2]
void LasFile::readHeader (Header & hdr) protected
readPoint()
void LasFile::readPoint (Point & pt)
remove()
void LasFile::remove (const std::string & path) static
Referenced by IndexFileBuilder::stateEnd().
seek()
void LasFile::seek (uint64_t offset)
seekExtendedVlr()
void LasFile::seekExtendedVlr ()
seekHeader()
void LasFile::seekHeader ()
seekPoint()
void LasFile::seekPoint (uint64_t index)
Referenced by PageData::readPage(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateMainBegin(), IndexFileBuilder::stateMainEnd(), IndexFileBuilder::stateMainSort(), IndexFileBuilder::stateNodeInsert(), and PageData::writePage().
seekPointData()
void LasFile::seekPointData ()
seekVlr()
void LasFile::seekVlr ()
size()
uint64_t LasFile::size () const
Referenced by IndexFileBuilder::openFiles().
transform() [1/2]
void LasFile::transform (double & x, double & y, double & z, const Point & pt) const
transform() [2/2]
void LasFile::transform (double & x, double & y, double & z, const uint8_t * buffer) const
transformInvert()
void LasFile::transformInvert (double & x, double & y, double & z) const
writeAttributesBuffer()
void LasFile::writeAttributesBuffer (const AttributesBuffer & buffer, uint64_t n, uint64_t from = 0)
Referenced by IndexFileBuilder::stateCopyAttributes(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateCreateAttributes(), IndexFileBuilder::stateMainSort(), IndexFileBuilder::stateNodeInsert(), and PageData::writePage().
writeBuffer()
void LasFile::writeBuffer (const uint8_t * buffer, uint64_t nbyte)
Referenced by IndexFileBuilder::stateCopy(), IndexFileBuilder::stateCopyPoints(), IndexFileBuilder::stateMainSort(), IndexFileBuilder::stateNodeInsert(), and PageData::writePage().
writeHeader() [1/2]
void LasFile::writeHeader ()
Referenced by ExportFileFormatLas::create(), create(), IndexFileBuilder::openFiles(), and writeHeader().
writeHeader() [2/2]
void LasFile::writeHeader (const Header & hdr) protected
writePoint()
void LasFile::writePoint (const Point & pt)
Referenced by create(), and ExportFileFormatLas::write().
Member Data Documentation
attributeFiles_
std::vector<RecordFile> LasFile::attributeFiles_ protected
Referenced by close(), createAttributesBuffer(), openAttributeFiles(), range(), readAttributesBuffer(), readPoint(), seekPoint(), writeAttributesBuffer(), and writePoint().
file_
File LasFile::file_ protected
Referenced by close(), create(), offset(), open(), open(), readBuffer(), readHeader(), readPoint(), seek(), seekExtendedVlr(), seekHeader(), seekPoint(), seekPointData(), seekVlr(), size(), writeBuffer(), writeHeader(), and writePoint().
FORMAT_CLASSIFICATION
const uint32_t LasFile::FORMAT_CLASSIFICATION = 1U << 3 static
Referenced by ExportFileFormatCsv::create(), and ExportFileFormatCsv::write().
FORMAT_INTENSITY
const uint32_t LasFile::FORMAT_INTENSITY = 1U << 2 static
Referenced by ExportFileFormatCsv::create(), and ExportFileFormatCsv::write().
FORMAT_INVALID
const uint32_t LasFile::FORMAT_INVALID = 0 static
LAS Attribute.
Referenced by ExportFileProperties::clear().
FORMAT_RGB
const uint32_t LasFile::FORMAT_RGB = 1U << 4 static
Referenced by ExportFileFormatCsv::create(), LasFile::Format::las(), and ExportFileFormatCsv::write().
FORMAT_SEGMENT
const uint32_t LasFile::FORMAT_SEGMENT = 1U << 5 static
Referenced by ExportFileFormatCsv::create(), and ExportFileFormatCsv::write().
FORMAT_XYZ
const uint32_t LasFile::FORMAT_XYZ = 1U << 1 static
header
Header LasFile::header
Referenced by create(), ExportFileFormatLas::create(), create(), formatBytesToPoint(), IndexFileBuilder::formatPoint(), IndexFileBuilder::nextState(), open(), IndexFileBuilder::openFiles(), range(), readHeader(), PageData::readPage(), readPoint(), seekExtendedVlr(), seekPoint(), seekPointData(), seekVlr(), IndexFileBuilder::stateCopyPoints(), transform(), transform(), transformInvert(), writeHeader(), PageData::writePage(), and writePoint().
The documentation for this class was generated from the following files:
LasFile.hpp
LasFile.cpp