3D Forest: ComputeDescriptorPca Class Reference
ComputeDescriptorPca Class Reference
#include <ComputeDescriptorPca.hpp>
Public Member Functions
ComputeDescriptorPca ()
void clear ()
bool computeDescriptor (Query &query, const Box< double > &cell, double &meanX, double &meanY, double &meanZ, double &descriptor)
bool computeDescriptor (Query &query, double x, double y, double z, double radius, double &meanX, double &meanY, double &meanZ, double &descriptor)
bool computeDescriptor (Eigen::MatrixXd &V, double &meanX, double &meanY, double &meanZ, double &descriptor)
bool computeDistribution (Query &query, double x, double y, double z, double radius, double &descriptor)
Private Attributes
Eigen::MatrixXd xyz
Eigen::Matrix3d product
Eigen::Matrix3d eigenVectors
Eigen::Matrix3d eigenVectorsT
Eigen::Vector3d in
Eigen::Vector3d out
Eigen::Vector3d min
Eigen::Vector3d max
Eigen::SelfAdjointEigenSolver< Eigen::Matrix3d > E
Constructor & Destructor Documentation
ComputeDescriptorPca()
ComputeDescriptorPca::ComputeDescriptorPca ()
Member Function Documentation
clear()
void ComputeDescriptorPca::clear ()
Referenced by ComputeDescriptorAction::clear(), and ComputeDescriptorPca().
computeDescriptor() [1/3]
bool ComputeDescriptorPca::computeDescriptor (Eigen::MatrixXd & V, double & meanX, double & meanY, double & meanZ, double & descriptor)
computeDescriptor() [2/3]
bool ComputeDescriptorPca::computeDescriptor (Query & query, const Box< double > & cell, double & meanX, double & meanY, double & meanZ, double & descriptor)
Referenced by computeDescriptor(), computeDescriptor(), and ComputeDescriptorAction::computePoint().
computeDescriptor() [3/3]
bool ComputeDescriptorPca::computeDescriptor (Query & query, double x, double y, double z, double radius, double & meanX, double & meanY, double & meanZ, double & descriptor)
computeDistribution()
bool ComputeDescriptorPca::computeDistribution (Query & query, double x, double y, double z, double radius, double & descriptor)
Member Data Documentation
E
Eigen::SelfAdjointEigenSolver<Eigen::Matrix3d> ComputeDescriptorPca::E private
Referenced by computeDescriptor().
eigenVectors
Eigen::Matrix3d ComputeDescriptorPca::eigenVectors private
Referenced by computeDescriptor().
eigenVectorsT
Eigen::Matrix3d ComputeDescriptorPca::eigenVectorsT private
Referenced by computeDescriptor().
in
Eigen::Vector3d ComputeDescriptorPca::in private
Referenced by computeDescriptor().
max
Eigen::Vector3d ComputeDescriptorPca::max private
Referenced by computeDescriptor().
min
Eigen::Vector3d ComputeDescriptorPca::min private
Referenced by computeDescriptor().
out
Eigen::Vector3d ComputeDescriptorPca::out private
Referenced by computeDescriptor().
product
Eigen::Matrix3d ComputeDescriptorPca::product private
Referenced by computeDescriptor().
xyz
Eigen::MatrixXd ComputeDescriptorPca::xyz private
Referenced by clear(), and computeDescriptor().
The documentation for this class was generated from the following files:
ComputeDescriptorPca.hpp
ComputeDescriptorPca.cpp