3D Forest: Points Class Reference
Points Class Reference
#include <Points.hpp>
Public Member Functions
Points ()
~Points ()
bool empty () const
size_t size () const
Point & operator[] (size_t pos)
const Point & operator[] (size_t pos) const
Point & at (size_t pos)
const Point & at (size_t pos) const
void push_back (const Point &point)
void push_back (Point &&point)
void clear ()
void createIndex ()
void findRadius (double x, double y, double z, double r, std::vector< size_t > &resultIndices)
size_t findNN (double x, double y, double z)
void exportToFile (const std::string &path) const
Private Attributes
VectorFile< Point, Point::IO > points_
unibn::Octree< Point, VectorFile< Point, Point::IO > > octree_
Friends
void toJson (Json &out, const Points &in)
Constructor & Destructor Documentation
Points()
Points::Points ()
~Points()
Points::~Points ()
Member Function Documentation
at() [1/2]
Point & Points::at (size_t pos) inline
at() [2/2]
const Point & Points::at (size_t pos) const inline
clear()
void Points::clear ()
Referenced by ComputeClassificationAction::clear(), ComputeElevationAction::clear(), ComputeSegmentationNNAction::clear(), ComputeClassificationAction::start(), ComputeSegmentationNNAction::start(), and ComputeElevationAction::start().
createIndex()
void Points::createIndex ()
Referenced by ComputeElevationAction::stepCreateIndex(), ComputeClassificationAction::stepCreateVoxelIndex(), and ComputeSegmentationNNAction::stepCreateVoxelIndex().
empty()
bool Points::empty () const inline
exportToFile()
void Points::exportToFile (const std::string & path) const
findNN()
size_t Points::findNN (double x, double y, double z)
Referenced by ComputeElevationAction::stepComputeElevation().
findRadius()
void Points::findRadius (double x, double y, double z, double r, std::vector< size_t > & resultIndices)
Referenced by ComputeSegmentationNNAction::findNearestNeighbor(), ComputeClassificationAction::stepClassifyGround(), and ComputeSegmentationNNAction::stepCreateTrunks().
operator[]() [1/2]
Point & Points::operator[] (size_t pos) inline
operator[]() [2/2]
const Point & Points::operator[] (size_t pos) const inline
push_back() [1/2]
void Points::push_back (const Point & point)
Referenced by ComputeElevationAction::createGroundPoint(), ComputeClassificationAction::createVoxel(), ComputeSegmentationNNAction::createVoxel(), ComputeSegmentationNNAction::stepCreateBranches(), and ComputeSegmentationNNAction::stepCreateTrunks().
push_back() [2/2]
void Points::push_back (Point && point)
size()
size_t Points::size () const inline
Referenced by ComputeClassificationAction::createVoxel(), ComputeSegmentationNNAction::createVoxel(), ComputeClassificationAction::stepClassifyGround(), ComputeElevationAction::stepComputeElevation(), ComputeSegmentationNNAction::stepCreateBranches(), ComputeSegmentationNNAction::stepCreateTrunks(), ComputeClassificationAction::stepCreateVoxelIndex(), ComputeSegmentationNNAction::stepCreateVoxelIndex(), ComputeClassificationAction::stepPointsToVoxels(), ComputeSegmentationNNAction::stepPointsToVoxels(), ComputeClassificationAction::stepVoxelsToPoints(), and ComputeSegmentationNNAction::stepVoxelsToPoints().
Friends And Related Symbol Documentation
toJson
void toJson (Json & out, const Points & in) friend
Referenced by exportToFile().
Member Data Documentation
octree_
unibn::Octree<Point, VectorFile<Point, Point::IO> > Points::octree_ private
Referenced by createIndex(), findNN(), and findRadius().
points_
VectorFile<Point, Point::IO> Points::points_ private
Referenced by clear(), createIndex(), Points(), push_back(), push_back(), and ~Points().
The documentation for this class was generated from the following files:
Points.hpp
Points.cpp