3D Forest: ExplorerClippingWidget Class Reference
ExplorerClippingWidget Class Reference
#include <ExplorerClippingWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRegionChanged (const Region &region)
Public Member Functions
ExplorerClippingWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void filterChanged ()
Protected Attributes
ToolTabWidget * tabWidget_
ExplorerClippingBoxWidget * boxWidget_
ExplorerClippingCylinderWidget * cylinderWidget_
Region region_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ExplorerClippingWidget()
ExplorerClippingWidget::ExplorerClippingWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ExplorerClippingWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
filterChanged()
void ExplorerClippingWidget::filterChanged () protected
Referenced by setFilterEnabled(), and slotRegionChanged().
hasColorSource()
virtual bool ExplorerClippingWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerClippingWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
setFilterEnabled()
void ExplorerClippingWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
slotRegionChanged
void ExplorerClippingWidget::slotRegionChanged (const Region & region) slot
Referenced by ExplorerClippingWidget().
slotUpdate
void ExplorerClippingWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerClippingWidget().
Member Data Documentation
boxWidget_
ExplorerClippingBoxWidget* ExplorerClippingWidget::boxWidget_ protected
Referenced by ExplorerClippingWidget(), and slotUpdate().
cylinderWidget_
ExplorerClippingCylinderWidget* ExplorerClippingWidget::cylinderWidget_ protected
Referenced by ExplorerClippingWidget(), and slotUpdate().
region_
Region ExplorerClippingWidget::region_ protected
Referenced by filterChanged(), slotRegionChanged(), and slotUpdate().
tabWidget_
ToolTabWidget* ExplorerClippingWidget::tabWidget_ protected
Referenced by ExplorerClippingWidget().
The documentation for this class was generated from the following files:
ExplorerClippingWidget.hpp
ExplorerClippingWidget.cpp