3D Forest: LayerList Class Reference
LayerList Class Reference
#include <LayerList.hpp>
Public Member Functions
LayerList ()
void clear ()
void setDefault ()
bool isEnabled () const
void setEnabled (bool b)
size_t size () const
const Layer & at (size_t i) const
void push_back (const Layer &layer)
void erase (size_t i)
size_t id (size_t i) const
size_t index (size_t id) const
size_t unusedId () const
bool isEnabledId (size_t id) const
bool isEnabled (size_t i) const
const std::unordered_set< size_t > & enabledList () const
void setEnabled (size_t i, bool b)
void setEnabledAll (bool b)
void setInvertAll ()
const std::string & label (size_t i) const
void setLabel (size_t i, const std::string &label)
const Vector3< float > & color (size_t i) const
void setColor (size_t i, const Vector3< float > &color)
void read (const Json &in)
Json & write (Json &out) const
Protected Attributes
std::vector< Layer > layers_
std::unordered_map< size_t, size_t > hashTableId_
std::unordered_set< size_t > hashTableEnabledId_
bool enabled_
Constructor & Destructor Documentation
LayerList()
LayerList::LayerList ()
Member Function Documentation
at()
const Layer & LayerList::at (size_t i) const inline
clear()
void LayerList::clear ()
Referenced by read().
color()
const Vector3< float > & LayerList::color (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), and setColor().
enabledList()
const std::unordered_set< size_t > & LayerList::enabledList () const inline
Referenced by Editor::setLayers().
erase()
void LayerList::erase (size_t i)
Referenced by ProjectNavigatorLayers::slotDelete().
id()
size_t LayerList::id (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), erase(), push_back(), read(), and setDefault().
index()
size_t LayerList::index (size_t id) const inline
Referenced by ProjectNavigatorLayers::index().
isEnabled() [1/2]
bool LayerList::isEnabled () const inline
Referenced by ProjectNavigatorLayers::addItem(), read(), and ProjectNavigatorLayers::updateTree().
isEnabled() [2/2]
bool LayerList::isEnabled (size_t i) const inline
isEnabledId()
bool LayerList::isEnabledId (size_t id) const inline
label()
const std::string & LayerList::label (size_t i) const inline
Referenced by ProjectNavigatorLayers::addItem(), and setLabel().
push_back()
void LayerList::push_back (const Layer & layer)
read()
void LayerList::read (const Json & in)
Referenced by Editor::openProject().
setColor()
void LayerList::setColor (size_t i, const Vector3< float > & color)
setDefault()
void LayerList::setDefault ()
Referenced by Editor::close(), LayerList(), and read().
setEnabled() [1/2]
void LayerList::setEnabled (bool b)
Referenced by ProjectNavigatorLayers::slotItemChanged().
setEnabled() [2/2]
void LayerList::setEnabled (size_t i, bool b)
setEnabledAll()
void LayerList::setEnabledAll (bool b)
setInvertAll()
void LayerList::setInvertAll ()
setLabel()
void LayerList::setLabel (size_t i, const std::string & label)
size()
size_t LayerList::size () const inline
Referenced by ProjectNavigatorLayers::setLayers().
unusedId()
size_t LayerList::unusedId () const
write()
Json & LayerList::write (Json & out) const
Referenced by Editor::save().
Member Data Documentation
enabled_
bool LayerList::enabled_ protected
Referenced by isEnabled(), read(), setEnabled(), and write().
hashTableEnabledId_
std::unordered_set<size_t> LayerList::hashTableEnabledId_ protected
Referenced by clear(), enabledList(), erase(), isEnabledId(), push_back(), read(), setDefault(), setEnabled(), setEnabledAll(), and setInvertAll().
hashTableId_
std::unordered_map<size_t, size_t> LayerList::hashTableId_ protected
Referenced by clear(), erase(), index(), push_back(), read(), setDefault(), and unusedId().
layers_
std::vector<Layer> LayerList::layers_ protected
Referenced by at(), clear(), color(), erase(), id(), isEnabled(), label(), push_back(), read(), setColor(), setDefault(), setEnabled(), setEnabledAll(), setInvertAll(), setLabel(), size(), and write().
The documentation for this class was generated from the following files:
LayerList.hpp
LayerList.cpp