3D Forest: ExportFileFormatInterface Class Reference
ExportFileFormatInterface Class Reference abstract
#include <ExportFileFormatInterface.hpp>
Inherited by ExportFileFormatCsv, and ExportFileFormatLas.
Public Member Functions
virtual ~ExportFileFormatInterface ()=default
virtual bool isOpen ()=0
virtual void create (const std::string &path)=0
virtual void write (Query &query)=0
virtual void close ()=0
void setProperties (const ExportFileProperties &prop)
const ExportFileProperties & properties () const
Private Attributes
ExportFileProperties properties_
Constructor & Destructor Documentation
~ExportFileFormatInterface()
virtual ExportFileFormatInterface::~ExportFileFormatInterface () virtual default
Member Function Documentation
close()
virtual void ExportFileFormatInterface::close () pure virtual
Implemented in ExportFileFormatCsv, and ExportFileFormatLas.
create()
virtual void ExportFileFormatInterface::create (const std::string & path) pure virtual
Implemented in ExportFileFormatCsv, and ExportFileFormatLas.
isOpen()
virtual bool ExportFileFormatInterface::isOpen () pure virtual
Implemented in ExportFileFormatCsv, and ExportFileFormatLas.
properties()
const ExportFileProperties & ExportFileFormatInterface::properties () const inline
Referenced by ExportFileFormatCsv::create(), ExportFileFormatLas::create(), ExportFileFormatCsv::write(), and ExportFileFormatLas::write().
setProperties()
void ExportFileFormatInterface::setProperties (const ExportFileProperties & prop) inline
write()
virtual void ExportFileFormatInterface::write (Query & query) pure virtual
Implemented in ExportFileFormatCsv, and ExportFileFormatLas.
Member Data Documentation
properties_
ExportFileProperties ExportFileFormatInterface::properties_ private
Referenced by properties(), and setProperties().
The documentation for this class was generated from the following file:
ExportFileFormatInterface.hpp