3D Forest: DoubleSliderWidget Class Reference
DoubleSliderWidget Class Reference
#include <DoubleSliderWidget.hpp>
Inherits QWidget.
Public Types
enum Layout { LAYOUT_SLIDER_BESIDE_LABEL , LAYOUT_SLIDER_UNDER_LABEL }
Signals
void signalIntermediateValue (double v)
void signalFinalValue ()
Public Member Functions
DoubleSliderWidget ()
double value () const
double minimum () const
double maximum () const
void setValue (double value)
void setMinimum (double min)
void setMaximum (double max)
void blockSignals (bool block)
Static Public Member Functions
static void create (DoubleSliderWidget *&outputWidget, const QObject *receiver, const char *memberIntermediateValue, const char *memberFinalValue, const QString &text, const QString &toolTip, const QString &unitsList, double step, double min, double max, double value, Layout layout=LAYOUT_SLIDER_UNDER_LABEL)
Protected Slots
void slotIntermediateValue (int v)
void slotIntermediateValue (double v)
void slotFinalValue ()
Protected Attributes
QSlider * slider_
QDoubleSpinBox * spinBox_
double minimumValue_
double maximumValue_
Member Enumeration Documentation
Layout
enum DoubleSliderWidget::Layout
Slider layout.
Enumerator
LAYOUT_SLIDER_BESIDE_LABEL
LAYOUT_SLIDER_UNDER_LABEL
Constructor & Destructor Documentation
DoubleSliderWidget()
DoubleSliderWidget::DoubleSliderWidget ()
Referenced by create().
Member Function Documentation
blockSignals()
void DoubleSliderWidget::blockSignals (bool block)
create()
void DoubleSliderWidget::create (DoubleSliderWidget *& outputWidget, const QObject * receiver, const char * memberIntermediateValue, const char * memberFinalValue, const QString & text, const QString & toolTip, const QString & unitsList, double step, double min, double max, double value, Layout layout = LAYOUT_SLIDER_UNDER_LABEL) static
Referenced by ComputeClassificationWidget::ComputeClassificationWidget(), ComputeDescriptorWidget::ComputeDescriptorWidget(), ComputeElevationWidget::ComputeElevationWidget(), ComputeSegmentationNNWidget::ComputeSegmentationNNWidget(), and ComputeTreeAttributesWidget::ComputeTreeAttributesWidget().
maximum()
double DoubleSliderWidget::maximum () const
minimum()
double DoubleSliderWidget::minimum () const
setMaximum()
void DoubleSliderWidget::setMaximum (double max)
setMinimum()
void DoubleSliderWidget::setMinimum (double min)
setValue()
void DoubleSliderWidget::setValue (double value)
signalFinalValue
void DoubleSliderWidget::signalFinalValue () signal
Referenced by create(), and slotFinalValue().
signalIntermediateValue
void DoubleSliderWidget::signalIntermediateValue (double v) signal
Referenced by create(), slotIntermediateValue(), and slotIntermediateValue().
slotFinalValue
void DoubleSliderWidget::slotFinalValue () protected slot
Referenced by create().
slotIntermediateValue [1/2]
void DoubleSliderWidget::slotIntermediateValue (double v) protected slot
slotIntermediateValue [2/2]
void DoubleSliderWidget::slotIntermediateValue (int v) protected slot
Referenced by create().
value()
double DoubleSliderWidget::value () const
Referenced by create(), setValue(), ComputeClassificationWidget::slotApply(), ComputeDescriptorWidget::slotApply(), ComputeElevationWidget::slotApply(), ComputeSegmentationNNWidget::slotApply(), ComputeTreeAttributesWidget::slotApply(), and slotIntermediateValue().
Member Data Documentation
maximumValue_
double DoubleSliderWidget::maximumValue_ protected
Referenced by create(), maximum(), minimum(), setMaximum(), setValue(), slotIntermediateValue(), and slotIntermediateValue().
minimumValue_
double DoubleSliderWidget::minimumValue_ protected
Referenced by create(), setMinimum(), setValue(), slotIntermediateValue(), and slotIntermediateValue().
slider_
QSlider* DoubleSliderWidget::slider_ protected
Referenced by blockSignals(), create(), setMaximum(), setMinimum(), setValue(), slotIntermediateValue(), and slotIntermediateValue().
spinBox_
QDoubleSpinBox* DoubleSliderWidget::spinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMinimum(), setValue(), slotIntermediateValue(), slotIntermediateValue(), and value().
The documentation for this class was generated from the following files:
DoubleSliderWidget.hpp
DoubleSliderWidget.cpp