3D Forest: Cylinder< T > Class Template Reference
Cylinder< T > Class Template Reference
#include <Cylinder.hpp>
Public Member Functions
Cylinder ()
~Cylinder ()
template<class B >
Cylinder (B x, B y, B z, B nx, B ny, B nz, B radius, B length)
void set (T ax, T ay, T az, T bx, T by, T bz, T radius)
void set (T x, T y, T z, T nx, T ny, T nz, T radius, T length)
const Vector3< T > & a () const
const Vector3< T > & b () const
const Vector3< T > & n () const
T radius () const
T length () const
const Box< T > & box () const
void clear ()
bool empty () const
bool isInside (T x, T y, T z) const
Private Member Functions
void validate ()
Private Attributes
Vector3< T > a_
Vector3< T > b_
Vector3< T > n_
T radius_
T length_
Box< T > box_
Constructor & Destructor Documentation
Cylinder() [1/2]
template<class T > Cylinder< T >::Cylinder inline
~Cylinder()
template<class T > Cylinder< T >::~Cylinder inline
Cylinder() [2/2]
template<class T > template<class B > Cylinder< T >::Cylinder (B x, B y, B z, B nx, B ny, B nz, B radius, B length) inline
Member Function Documentation
a()
template<class T > const Vector3< T > & Cylinder< T >::a () const inline
Referenced by ViewerOpenGL::renderClipFilter().
b()
template<class T > const Vector3< T > & Cylinder< T >::b () const inline
Referenced by ViewerOpenGL::renderClipFilter().
box()
template<class T > const Box< T > & Cylinder< T >::box () const inline
Referenced by Query::exec(), and Page::queryWhereCylinder().
clear()
template<class T > void Cylinder< T >::clear inline
empty()
template<class T > bool Cylinder< T >::empty () const inline
Referenced by Page::queryWhereCylinder().
isInside()
template<class T > bool Cylinder< T >::isInside (T x, T y, T z) const inline
Referenced by Page::queryWhereCylinder().
length()
template<class T > T Cylinder< T >::length () const inline
n()
template<class T > const Vector3< T > & Cylinder< T >::n () const inline
radius()
template<class T > T Cylinder< T >::radius () const inline
Referenced by ViewerOpenGL::renderClipFilter().
set() [1/2]
template<class T > void Cylinder< T >::set (T ax, T ay, T az, T bx, T by, T bz, T radius) inline
Referenced by QueryWhere::setCylinder(), and ExplorerClippingCylinderWidget::slotInputChanged().
set() [2/2]
template<class T > void Cylinder< T >::set (T x, T y, T z, T nx, T ny, T nz, T radius, T length) inline
validate()
template<class T > void Cylinder< T >::validate inline private
Referenced by Cylinder< T >::Cylinder().
Member Data Documentation
a_
template<class T > Vector3<T> Cylinder< T >::a_ private
Referenced by Cylinder< T >::a().
b_
template<class T > Vector3<T> Cylinder< T >::b_ private
Referenced by Cylinder< T >::b().
box_
template<class T > Box<T> Cylinder< T >::box_ private
Referenced by Cylinder< T >::box(), and Cylinder< T >::empty().
length_
template<class T > T Cylinder< T >::length_ private
Referenced by Cylinder< T >::length().
n_
template<class T > Vector3<T> Cylinder< T >::n_ private
Referenced by Cylinder< T >::n().
radius_
template<class T > T Cylinder< T >::radius_ private
Referenced by Cylinder< T >::radius().
The documentation for this class was generated from the following file:
Cylinder.hpp