3D Forest: ProjectNavigatorItemClipping Class Reference
ProjectNavigatorItemClipping Class Reference
#include <ProjectNavigatorItemClipping.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
void reset ()
Public Member Functions
ProjectNavigatorItemClipping (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void filterChanged ()
Protected Attributes
RangeSliderWidget * rangeInput_ [3]
QPushButton * resetButton_
Range< double > clipRange_ [3]
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ProjectNavigatorItemClipping()
ProjectNavigatorItemClipping::ProjectNavigatorItemClipping (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemClipping::colorSource () const inline virtual
Implements ProjectNavigatorItem.
filterChanged()
void ProjectNavigatorItemClipping::filterChanged () protected
Referenced by reset(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ProjectNavigatorItemClipping::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemClipping::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
reset
void ProjectNavigatorItemClipping::reset () slot
Referenced by ProjectNavigatorItemClipping().
setFilterEnabled()
void ProjectNavigatorItemClipping::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotRangeIntermediateMaximumValue
void ProjectNavigatorItemClipping::slotRangeIntermediateMaximumValue () slot
Referenced by ProjectNavigatorItemClipping().
slotRangeIntermediateMinimumValue
void ProjectNavigatorItemClipping::slotRangeIntermediateMinimumValue () slot
Referenced by ProjectNavigatorItemClipping().
slotUpdate
void ProjectNavigatorItemClipping::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemClipping().
Member Data Documentation
clipRange_
Range<double> ProjectNavigatorItemClipping::clipRange_[3] protected
Referenced by filterChanged(), reset(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
rangeInput_
RangeSliderWidget* ProjectNavigatorItemClipping::rangeInput_[3] protected
Referenced by ProjectNavigatorItemClipping(), reset(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and slotUpdate().
resetButton_
QPushButton* ProjectNavigatorItemClipping::resetButton_ protected
Referenced by ProjectNavigatorItemClipping().
The documentation for this class was generated from the following files:
ProjectNavigatorItemClipping.hpp
ProjectNavigatorItemClipping.cpp