3D Forest: ProjectFilePlugin Class Reference
ProjectFilePlugin Class Reference
#include <ProjectFilePlugin.hpp>
Inherits QObject, PluginInterface, and ProjectFileInterface.
Public Slots
void slotNewProject ()
void slotOpenProject ()
void slotSaveProject ()
void slotSaveAsProject ()
Public Member Functions
ProjectFilePlugin ()
virtual void initialize (MainWindow *mainWindow)
virtual bool closeProject ()
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()=default
Public Member Functions inherited from ProjectFileInterface
virtual ~ProjectFileInterface ()=default
Private Member Functions
bool openProject (const QString &path)
bool saveProject (const QString &path="")
Private Attributes
MainWindow * mainWindow_
QAction * newProjectAction_
QAction * openProjectAction_
QAction * saveProjectAction_
QAction * saveAsProjectAction_
Constructor & Destructor Documentation
ProjectFilePlugin()
ProjectFilePlugin::ProjectFilePlugin ()
Member Function Documentation
closeProject()
bool ProjectFilePlugin::closeProject () virtual
Implements ProjectFileInterface.
Referenced by openProject(), and slotNewProject().
initialize()
void ProjectFilePlugin::initialize (MainWindow * mainWindow) virtual
Implements PluginInterface.
openProject()
bool ProjectFilePlugin::openProject (const QString & path) private
Referenced by slotOpenProject().
saveProject()
bool ProjectFilePlugin::saveProject (const QString & path = "") private
Referenced by closeProject(), slotSaveAsProject(), and slotSaveProject().
slotNewProject
void ProjectFilePlugin::slotNewProject () slot
Referenced by initialize().
slotOpenProject
void ProjectFilePlugin::slotOpenProject () slot
Referenced by initialize().
slotSaveAsProject
void ProjectFilePlugin::slotSaveAsProject () slot
Referenced by initialize().
slotSaveProject
void ProjectFilePlugin::slotSaveProject () slot
Referenced by initialize().
Member Data Documentation
mainWindow_
MainWindow* ProjectFilePlugin::mainWindow_ private
Referenced by closeProject(), initialize(), openProject(), saveProject(), slotNewProject(), slotOpenProject(), and slotSaveAsProject().
newProjectAction_
QAction* ProjectFilePlugin::newProjectAction_ private
Referenced by initialize().
openProjectAction_
QAction* ProjectFilePlugin::openProjectAction_ private
Referenced by initialize().
saveAsProjectAction_
QAction* ProjectFilePlugin::saveAsProjectAction_ private
Referenced by initialize().
saveProjectAction_
QAction* ProjectFilePlugin::saveProjectAction_ private
Referenced by initialize().
The documentation for this class was generated from the following files:
ProjectFilePlugin.hpp
ProjectFilePlugin.cpp