3D Forest: ViewerAabb Class Reference
ViewerAabb Class Reference
#include <ViewerAabb.hpp>
Public Member Functions
ViewerAabb ()
~ViewerAabb ()
void set (float min_x, float min_y, float min_z, float max_x, float max_y, float max_z)
void set (const QVector3D &min, const QVector3D &max)
void set (const std::vector< float > &xyz)
void set (const Box< float > &box)
void set (const Box< double > &box)
void extend (const ViewerAabb &box)
void invalidate ()
bool valid () const
const QVector3D & min () const
const QVector3D & max () const
const QVector3D & center () const
float radius () const
void range (const QVector3D &eye, const QVector3D &direction, float *min, float *max)
Protected Member Functions
void setValid ()
Protected Attributes
QVector3D min_
QVector3D max_
QVector3D center_
float radius_
bool valid_
Friends
void toJson (Json &out, const ViewerAabb &in)
std::string toString (const ViewerAabb &in)
std::ostream & operator<< (std::ostream &out, const ViewerAabb &in)
Constructor & Destructor Documentation
ViewerAabb()
ViewerAabb::ViewerAabb ()
~ViewerAabb()
ViewerAabb::~ViewerAabb ()
Member Function Documentation
center()
const QVector3D & ViewerAabb::center () const inline
Referenced by range(), and ViewerOpenGLViewport::setViewResetCenter().
extend()
void ViewerAabb::extend (const ViewerAabb & box)
invalidate()
void ViewerAabb::invalidate ()
max()
const QVector3D & ViewerAabb::max () const inline
Referenced by extend(), range(), ViewerOpenGL::renderAabb(), and set().
min()
const QVector3D & ViewerAabb::min () const inline
Referenced by extend(), range(), ViewerOpenGL::renderAabb(), and set().
radius()
float ViewerAabb::radius () const inline
Referenced by ViewerOpenGLViewport::setViewResetDistance().
range()
void ViewerAabb::range (const QVector3D & eye, const QVector3D & direction, float * min, float * max)
Referenced by ViewerOpenGLViewport::renderSceneSettingsEnable().
set() [1/5]
void ViewerAabb::set (const Box< double > & box)
set() [2/5]
void ViewerAabb::set (const Box< float > & box)
set() [3/5]
void ViewerAabb::set (const QVector3D & min, const QVector3D & max)
set() [4/5]
void ViewerAabb::set (const std::vector< float > & xyz)
set() [5/5]
void ViewerAabb::set (float min_x, float min_y, float min_z, float max_x, float max_y, float max_z)
Referenced by extend(), ViewerOpenGL::renderClipFilter(), ViewerOpenGLViewport::renderSegments(), ViewerOpenGLViewport::resetScene(), set(), set(), and set().
setValid()
void ViewerAabb::setValid () protected
Referenced by extend(), set(), and set().
valid()
bool ViewerAabb::valid () const inline
Referenced by extend(), ViewerOpenGLViewport::setViewResetCenter(), and ViewerOpenGLViewport::setViewResetDistance().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const ViewerAabb & in) friend
toJson
void toJson (Json & out, const ViewerAabb & in) friend
toString
std::string toString (const ViewerAabb & in) friend
Member Data Documentation
center_
QVector3D ViewerAabb::center_ protected
Referenced by center(), and setValid().
max_
QVector3D ViewerAabb::max_ protected
Referenced by extend(), max(), range(), set(), set(), and setValid().
min_
QVector3D ViewerAabb::min_ protected
Referenced by extend(), min(), range(), set(), set(), and setValid().
radius_
float ViewerAabb::radius_ protected
Referenced by radius(), and setValid().
valid_
bool ViewerAabb::valid_ protected
Referenced by invalidate(), setValid(), and valid().
The documentation for this class was generated from the following files:
ViewerAabb.hpp
ViewerAabb.cpp