3D Forest: Dataset Class Reference
Dataset Class Reference
#include <Dataset.hpp>
Classes
class Range
Public Member Functions
Dataset ()
size_t id () const
const std::string & label () const
void setLabel (const std::string &label)
const Vector3< double > & color () const
void setColor (const Vector3< double > &color)
const std::string & path () const
const std::string & fileName () const
const std::string & dateCreated () const
const Vector3< double > & translation () const
void setTranslation (const Vector3< double > &translation)
const Vector3< double > & scaling () const
const Vector3< double > & scalingFile () const
const Box< double > & boundary () const
uint64_t nPoints () const
const IndexFile & index () const
const LasFile & las () const
LasFile & las ()
const Dataset::Range & range () const
void read (size_t id, const std::string &path, const std::string &projectPath, const SettingsImport &settings, const Box< double > &projectBoundary)
Protected Member Functions
void setPath (const std::string &path, const std::string &projectPath)
void read ()
void updateBoundary ()
Protected Attributes
size_t id_
std::string label_
Vector3< double > color_
std::string pathUnresolved_
std::string dateCreated_
Vector3< double > translation_
Vector3< double > scaling_
std::string path_
std::string fileName_
uint64_t nPoints_
Vector3< double > translationFile_
Vector3< double > scalingFile_
Box< double > boundaryFile_
Box< double > boundary_
Dataset::Range range_
std::shared_ptr< IndexFile > index_
std::shared_ptr< LasFile > las_
Friends
void fromJson (Dataset &out, const Json &in, const std::string &projectPath)
void toJson (Json &out, const Dataset &in)
Constructor & Destructor Documentation
Dataset()
Dataset::Dataset ()
Member Function Documentation
boundary()
const Box< double > & Dataset::boundary () const inline
Referenced by Page::runColorModifier().
color()
const Vector3< double > & Dataset::color () const inline
Referenced by setColor().
dateCreated()
const std::string & Dataset::dateCreated () const inline
fileName()
const std::string & Dataset::fileName () const inline
id()
size_t Dataset::id () const inline
Referenced by read().
index()
const IndexFile & Dataset::index () const inline
Referenced by Query::applyCamera(), PageData::readPage(), and PageData::writePage().
label()
const std::string & Dataset::label () const inline
Referenced by setLabel().
las() [1/2]
LasFile & Dataset::las () inline
las() [2/2]
const LasFile & Dataset::las () const inline
Referenced by PageData::readPage(), and PageData::writePage().
nPoints()
uint64_t Dataset::nPoints () const inline
path()
const std::string & Dataset::path () const inline
Referenced by read(), PageData::readPage(), and setPath().
range()
const Dataset::Range & Dataset::range () const inline
Referenced by Dataset::Range::extend().
read() [1/2]
void Dataset::read () protected
Referenced by read().
read() [2/2]
void Dataset::read (size_t id, const std::string & path, const std::string & projectPath, const SettingsImport & settings, const Box< double > & projectBoundary)
Referenced by Datasets::read().
scaling()
const Vector3< double > & Dataset::scaling () const inline
scalingFile()
const Vector3< double > & Dataset::scalingFile () const inline
Referenced by Editor::updateAfterRead().
setColor()
void Dataset::setColor (const Vector3< double > & color)
setLabel()
void Dataset::setLabel (const std::string & label)
setPath()
void Dataset::setPath (const std::string & path, const std::string & projectPath) protected
Referenced by read().
setTranslation()
void Dataset::setTranslation (const Vector3< double > & translation)
translation()
const Vector3< double > & Dataset::translation () const inline
Referenced by PageData::readPage(), setTranslation(), and PageData::transform().
updateBoundary()
void Dataset::updateBoundary () protected
Referenced by read(), read(), and setTranslation().
Friends And Related Symbol Documentation
fromJson
void fromJson (Dataset & out, const Json & in, const std::string & projectPath) friend
toJson
void toJson (Json & out, const Dataset & in) friend
Member Data Documentation
boundary_
Box<double> Dataset::boundary_ protected
Referenced by updateBoundary().
boundaryFile_
Box<double> Dataset::boundaryFile_ protected
Referenced by read(), read(), and updateBoundary().
color_
Vector3<double> Dataset::color_ protected
Referenced by read(), and setColor().
dateCreated_
std::string Dataset::dateCreated_ protected
Inconsistent with LAS in shared projects.
Referenced by read().
fileName_
std::string Dataset::fileName_ protected
Referenced by read(), and setPath().
id_
size_t Dataset::id_ protected
Referenced by read().
index_
std::shared_ptr<IndexFile> Dataset::index_ protected
Referenced by read(), and updateBoundary().
label_
std::string Dataset::label_ protected
Inconsistent with LAS in shared projects.
Referenced by read(), and setLabel().
las_
std::shared_ptr<LasFile> Dataset::las_ protected
Referenced by read().
nPoints_
uint64_t Dataset::nPoints_ protected
Referenced by read().
path_
std::string Dataset::path_ protected
Referenced by read(), and setPath().
pathUnresolved_
std::string Dataset::pathUnresolved_ protected
Referenced by read().
range_
Dataset::Range Dataset::range_ protected
Referenced by read().
scaling_
Vector3<double> Dataset::scaling_ protected
Referenced by read().
scalingFile_
Vector3<double> Dataset::scalingFile_ protected
Referenced by read().
translation_
Vector3<double> Dataset::translation_ protected
Referenced by read(), read(), setTranslation(), and updateBoundary().
translationFile_
Vector3<double> Dataset::translationFile_ protected
Referenced by read().
The documentation for this class was generated from the following files:
Dataset.hpp
Dataset.cpp