3D Forest: ExplorerElevationWidget Class Reference
ExplorerElevationWidget Class Reference
#include <ExplorerElevationWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Public Member Functions
ExplorerElevationWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Member Functions
void setElevation (const Range< double > &elevationRange)
void filterChanged ()
Protected Attributes
DoubleRangeSliderWidget * rangeInput_
Range< double > elevationRange_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Constructor & Destructor Documentation
ExplorerElevationWidget()
ExplorerElevationWidget::ExplorerElevationWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
colorSource()
virtual SettingsView::ColorSource ExplorerElevationWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
filterChanged()
void ExplorerElevationWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
hasColorSource()
virtual bool ExplorerElevationWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerElevationWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
isFilterEnabled()
bool ExplorerElevationWidget::isFilterEnabled () const virtual
Reimplemented from ExplorerWidgetInterface.
setElevation()
void ExplorerElevationWidget::setElevation (const Range< double > & elevationRange) protected
Referenced by slotUpdate().
setFilterEnabled()
void ExplorerElevationWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
slotRangeIntermediateMaximumValue
void ExplorerElevationWidget::slotRangeIntermediateMaximumValue () slot
Referenced by ExplorerElevationWidget().
slotRangeIntermediateMinimumValue
void ExplorerElevationWidget::slotRangeIntermediateMinimumValue () slot
Referenced by ExplorerElevationWidget().
slotUpdate
void ExplorerElevationWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerElevationWidget().
Member Data Documentation
elevationRange_
Range<double> ExplorerElevationWidget::elevationRange_ protected
Referenced by filterChanged(), isFilterEnabled(), setElevation(), setFilterEnabled(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
rangeInput_
DoubleRangeSliderWidget* ExplorerElevationWidget::rangeInput_ protected
Referenced by ExplorerElevationWidget(), setElevation(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
The documentation for this class was generated from the following files:
ExplorerElevationWidget.hpp
ExplorerElevationWidget.cpp