3D Forest: Vector3< T > Class Template Reference
Vector3< T > Class Template Reference
#include <Vector3.hpp>
Inherits std::array< T, 3 >.
Public Member Functions
Vector3 ()
Vector3 (T v0, T v1, T v2)
Vector3 (uint32_t v24)
template<class B >
Vector3 (const Vector3< B > &v)
template<class B >
Vector3< T > & operator= (const Vector3< B > &v)
template<class B >
void set (B v0, B v1, B v2)
void clear ()
T length () const
T min () const
T max () const
void normalize ()
Vector3< T > normalized () const
void read (const Json &in)
Json & write (Json &out) const
Vector3< T > crossProduct (const Vector3< T > &v) const
Vector3< T > rotated (const Vector3< T > &axis, double angle) const
Static Public Member Functions
static Vector3< T > crossProduct (const Vector3< T > &a, const Vector3< T > &b)
Friends
Vector3< T > operator+ (const Vector3< T > &a, const Vector3< T > &b)
Vector3< T > operator- (const Vector3< T > &a, const Vector3< T > &b)
Vector3< T > operator* (const Vector3< T > &a, T b)
Vector3< T > operator* (T a, const Vector3< T > &b)
Vector3< T > operator* (const Vector3< T > &a, const Vector3< T > &b)
Vector3< T > operator/ (const Vector3< T > &a, T b)
Vector3< T > operator/ (T a, const Vector3< T > &b)
Vector3< T > operator/ (const Vector3< T > &a, const Vector3< T > &b)
Constructor & Destructor Documentation
Vector3() [1/4]
template<class T > Vector3< T >::Vector3 inline
Vector3() [2/4]
template<class T > Vector3< T >::Vector3 (T v0, T v1, T v2) inline
Vector3() [3/4]
template<class T > Vector3< T >::Vector3 (uint32_t v24) inline
Vector3() [4/4]
template<class T > template<class B > Vector3< T >::Vector3 (const Vector3< B > & v)
Member Function Documentation
clear()
template<class T > void Vector3< T >::clear inline
Referenced by Voxels::clear().
crossProduct() [1/2]
template<class T > static Vector3< T > Vector3< T >::crossProduct (const Vector3< T > & a, const Vector3< T > & b) inline static
crossProduct() [2/2]
template<class T > Vector3< T > Vector3< T >::crossProduct (const Vector3< T > & v) const inline
Referenced by Vector3< T >::crossProduct(), and Matrix4< T >::lookAt().
length()
template<class T > T Vector3< T >::length inline
max()
template<class T > T Vector3< T >::max inline
Referenced by IndexFileBuilder::stateMainBegin().
min()
template<class T > T Vector3< T >::min inline
normalize()
template<class T > void Vector3< T >::normalize inline
Referenced by Matrix4< T >::lookAt(), and Vector3< T >::normalized().
normalized()
template<class T > Vector3< T > Vector3< T >::normalized inline
Referenced by Vector3< T >::rotated().
operator=()
template<class T > template<class B > Vector3< T > & Vector3< T >::operator= (const Vector3< B > & v) inline
read()
template<class T > void Vector3< T >::read (const Json & in) inline
Referenced by Layer::read(), SettingsView::read(), and Dataset::read().
rotated()
template<class T > Vector3< T > Vector3< T >::rotated (const Vector3< T > & axis, double angle) const inline
set()
template<class T > template<class B > void Vector3< T >::set (B v0, B v1, B v2) inline
Referenced by Dataset::read(), and ViewerCamera::toCamera().
write()
template<class T > Json & Vector3< T >::write (Json & out) const inline
Referenced by Dataset::write(), Layer::write(), and SettingsView::write().
Friends And Related Function Documentation
operator* [1/3]
template<class T > Vector3< T > operator* (const Vector3< T > & a, const Vector3< T > & b) friend
operator* [2/3]
template<class T > Vector3< T > operator* (const Vector3< T > & a, T b) friend
operator* [3/3]
template<class T > Vector3< T > operator* (T a, const Vector3< T > & b) friend
operator+
template<class T > Vector3< T > operator+ (const Vector3< T > & a, const Vector3< T > & b) friend
operator-
template<class T > Vector3< T > operator- (const Vector3< T > & a, const Vector3< T > & b) friend
operator/ [1/3]
template<class T > Vector3< T > operator/ (const Vector3< T > & a, const Vector3< T > & b) friend
operator/ [2/3]
template<class T > Vector3< T > operator/ (const Vector3< T > & a, T b) friend
operator/ [3/3]
template<class T > Vector3< T > operator/ (T a, const Vector3< T > & b) friend
The documentation for this class was generated from the following file:
Vector3.hpp