3D Forest: SettingsUnitsWidget Class Reference
SettingsUnitsWidget Class Reference
#include <SettingsUnitsWidget.hpp>
Inherits QWidget.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
Public Member Functions
SettingsUnitsWidget (MainWindow *mainWindow)
QSize sizeHint () const override
Protected Slots
void slotIntermediateLas (double v)
void slotIntermediateUser (double v)
void slotUserDefined (int v)
Private Member Functions
void dataChanged ()
void setUnitsSettings (const SettingsUnits &settings)
void block ()
void unblock ()
Private Attributes
MainWindow * mainWindow_
QDoubleSpinBox * ppmLasSpinBox_
QDoubleSpinBox * ppmUserSpinBox_
QCheckBox * userDefinedCheckBox_
SettingsUnits settings_
Constructor & Destructor Documentation
SettingsUnitsWidget()
SettingsUnitsWidget::SettingsUnitsWidget (MainWindow * mainWindow)
Member Function Documentation
block()
void SettingsUnitsWidget::block () private
Referenced by setUnitsSettings().
dataChanged()
void SettingsUnitsWidget::dataChanged () private
Referenced by slotIntermediateLas(), slotIntermediateUser(), and slotUserDefined().
setUnitsSettings()
void SettingsUnitsWidget::setUnitsSettings (const SettingsUnits & settings) private
Referenced by slotUpdate().
sizeHint()
QSize SettingsUnitsWidget::sizeHint () const inline override
Referenced by SettingsUnitsWindow::SettingsUnitsWindow().
slotIntermediateLas
void SettingsUnitsWidget::slotIntermediateLas (double v) protected slot
Referenced by SettingsUnitsWidget().
slotIntermediateUser
void SettingsUnitsWidget::slotIntermediateUser (double v) protected slot
Referenced by SettingsUnitsWidget().
slotUpdate
void SettingsUnitsWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by SettingsUnitsWidget().
slotUserDefined
void SettingsUnitsWidget::slotUserDefined (int v) protected slot
Referenced by SettingsUnitsWidget().
unblock()
void SettingsUnitsWidget::unblock () private
Referenced by setUnitsSettings().
Member Data Documentation
mainWindow_
MainWindow* SettingsUnitsWidget::mainWindow_ private
Referenced by dataChanged(), SettingsUnitsWidget(), and slotUpdate().
ppmLasSpinBox_
QDoubleSpinBox* SettingsUnitsWidget::ppmLasSpinBox_ private
Referenced by SettingsUnitsWidget(), and setUnitsSettings().
ppmUserSpinBox_
QDoubleSpinBox* SettingsUnitsWidget::ppmUserSpinBox_ private
Referenced by SettingsUnitsWidget(), setUnitsSettings(), and slotUserDefined().
settings_
SettingsUnits SettingsUnitsWidget::settings_ private
Referenced by dataChanged(), SettingsUnitsWidget(), setUnitsSettings(), slotIntermediateLas(), slotIntermediateUser(), and slotUserDefined().
userDefinedCheckBox_
QCheckBox* SettingsUnitsWidget::userDefinedCheckBox_ private
Referenced by SettingsUnitsWidget(), setUnitsSettings(), and slotUserDefined().
The documentation for this class was generated from the following files:
SettingsUnitsWidget.hpp
SettingsUnitsWidget.cpp