3D Forest: ProgressDialog Class Reference
ProgressDialog Class Reference
#include <ProgressDialog.hpp>
Inherits QDialog.
Public Slots
void slotCancel ()
Public Member Functions
ProgressDialog (MainWindow *mainWindow, const char *title)
bool run (ProgressActionInterface *progressAction)
Static Public Member Functions
static bool run (MainWindow *mainWindow, const char *title, ProgressActionInterface *progressAction)
Private Member Functions
void closeEvent (QCloseEvent *event) override
void initializeLabels (ProgressActionInterface *progressAction)
void updateLabels (ProgressActionInterface *progressAction)
Private Attributes
bool canceledFlag_
double etaStartTime_
double etaStartPercent_
QLabel * progressStepsLabel_
QLabel * progressStepLabel_
QLabel * etaLabel_
QProgressBar * progressBar_
QPushButton * cancelButton_
Constructor & Destructor Documentation
ProgressDialog()
ProgressDialog::ProgressDialog (MainWindow * mainWindow, const char * title)
Referenced by run().
Member Function Documentation
closeEvent()
void ProgressDialog::closeEvent (QCloseEvent * event) override private
initializeLabels()
void ProgressDialog::initializeLabels (ProgressActionInterface * progressAction) private
Referenced by run().
run() [1/2]
bool ProgressDialog::run (MainWindow * mainWindow, const char * title, ProgressActionInterface * progressAction) static
run() [2/2]
bool ProgressDialog::run (ProgressActionInterface * progressAction)
Referenced by run(), ClassificationWidget::slotApply(), DescriptorWidget::slotApply(), ElevationWidget::slotApply(), SegmentationWidget::slotApply(), and ExportFilePlugin::slotExportFile().
slotCancel
void ProgressDialog::slotCancel () slot
Referenced by closeEvent(), and ProgressDialog().
updateLabels()
void ProgressDialog::updateLabels (ProgressActionInterface * progressAction) private
Referenced by run().
Member Data Documentation
cancelButton_
QPushButton* ProgressDialog::cancelButton_ private
Referenced by ProgressDialog().
canceledFlag_
bool ProgressDialog::canceledFlag_ private
Referenced by run(), and slotCancel().
etaLabel_
QLabel* ProgressDialog::etaLabel_ private
Referenced by ProgressDialog(), and updateLabels().
etaStartPercent_
double ProgressDialog::etaStartPercent_ private
Referenced by initializeLabels(), and updateLabels().
etaStartTime_
double ProgressDialog::etaStartTime_ private
Referenced by initializeLabels(), and updateLabels().
progressBar_
QProgressBar* ProgressDialog::progressBar_ private
Referenced by ProgressDialog(), and updateLabels().
progressStepLabel_
QLabel* ProgressDialog::progressStepLabel_ private
Referenced by ProgressDialog(), and updateLabels().
progressStepsLabel_
QLabel* ProgressDialog::progressStepsLabel_ private
Referenced by initializeLabels(), ProgressDialog(), and updateLabels().
The documentation for this class was generated from the following files:
ProgressDialog.hpp
ProgressDialog.cpp