3D Forest: ProjectNavigatorItemClassifications Class Reference
ProjectNavigatorItemClassifications Class Reference
#include <ProjectNavigatorItemClassifications.hpp>
Inherits ProjectNavigatorItem.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ProjectNavigatorItemClassifications (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ProjectNavigatorItem
ProjectNavigatorItem (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ProjectNavigatorItem ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
void setClassifications (const Classifications &classifications)
Protected Attributes
QTreeWidget * tree_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Classifications classifications_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ProjectNavigatorItem
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ProjectNavigatorItemClassifications::Column protected
Project Navigator Classifications Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ProjectNavigatorItemClassifications()
ProjectNavigatorItemClassifications::ProjectNavigatorItemClassifications (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ProjectNavigatorItemClassifications::addTreeItem (size_t index) protected
Referenced by setClassifications().
block()
void ProjectNavigatorItemClassifications::block () protected
Referenced by setClassifications(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ProjectNavigatorItemClassifications::colorSource () const inline virtual
Implements ProjectNavigatorItem.
dataChanged()
void ProjectNavigatorItemClassifications::dataChanged () protected
filterChanged()
void ProjectNavigatorItemClassifications::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ProjectNavigatorItemClassifications::hasColorSource () const inline virtual
Implements ProjectNavigatorItem.
hasFilter()
virtual bool ProjectNavigatorItemClassifications::hasFilter () const inline virtual
Implements ProjectNavigatorItem.
identifier()
size_t ProjectNavigatorItemClassifications::identifier (const QTreeWidgetItem * item) protected
Referenced by slotItemChanged().
isFilterEnabled()
bool ProjectNavigatorItemClassifications::isFilterEnabled () const virtual
Reimplemented from ProjectNavigatorItem.
setClassifications()
void ProjectNavigatorItemClassifications::setClassifications (const Classifications & classifications) protected
Referenced by slotUpdate().
setFilterEnabled()
void ProjectNavigatorItemClassifications::setFilterEnabled (bool b) virtual
Reimplemented from ProjectNavigatorItem.
slotHide
void ProjectNavigatorItemClassifications::slotHide () slot
Referenced by ProjectNavigatorItemClassifications().
slotItemChanged
void ProjectNavigatorItemClassifications::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ProjectNavigatorItemClassifications::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ProjectNavigatorItemClassifications::slotSelectAll () slot
Referenced by ProjectNavigatorItemClassifications().
slotSelectInvert
void ProjectNavigatorItemClassifications::slotSelectInvert () slot
Referenced by ProjectNavigatorItemClassifications().
slotSelectNone
void ProjectNavigatorItemClassifications::slotSelectNone () slot
Referenced by ProjectNavigatorItemClassifications().
slotShow
void ProjectNavigatorItemClassifications::slotShow () slot
Referenced by ProjectNavigatorItemClassifications().
slotUpdate
void ProjectNavigatorItemClassifications::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ProjectNavigatorItemClassifications().
unblock()
void ProjectNavigatorItemClassifications::unblock () protected
Referenced by setClassifications(), and updateTree().
updateTree()
void ProjectNavigatorItemClassifications::updateTree () protected
Member Data Documentation
classifications_
Classifications ProjectNavigatorItemClassifications::classifications_ protected
Referenced by addTreeItem(), dataChanged(), and setClassifications().
filter_
QueryFilterSet ProjectNavigatorItemClassifications::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setFilterEnabled(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ProjectNavigatorItemClassifications::hideButton_ protected
Referenced by ProjectNavigatorItemClassifications(), and slotItemSelectionChanged().
selectAllButton_
QToolButton* ProjectNavigatorItemClassifications::selectAllButton_ protected
Referenced by ProjectNavigatorItemClassifications().
selectInvertButton_
QToolButton* ProjectNavigatorItemClassifications::selectInvertButton_ protected
Referenced by ProjectNavigatorItemClassifications().
selectNoneButton_
QToolButton* ProjectNavigatorItemClassifications::selectNoneButton_ protected
Referenced by ProjectNavigatorItemClassifications().
showButton_
QToolButton* ProjectNavigatorItemClassifications::showButton_ protected
Referenced by ProjectNavigatorItemClassifications(), and slotItemSelectionChanged().
tree_
QTreeWidget* ProjectNavigatorItemClassifications::tree_ protected
Referenced by addTreeItem(), block(), ProjectNavigatorItemClassifications(), setClassifications(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ProjectNavigatorItemClassifications::updatesEnabled_ protected
Referenced by ProjectNavigatorItemClassifications(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ProjectNavigatorItemClassifications.hpp
ProjectNavigatorItemClassifications.cpp