3D Forest: RangeSliderWidget Class Reference
RangeSliderWidget Class Reference
#include <RangeSliderWidget.hpp>
Inherits QWidget.
Signals
void signalIntermediateMinimumValue ()
void signalIntermediateMaximumValue ()
Public Member Functions
RangeSliderWidget ()
void setMinimum (int min)
void setMaximum (int max)
void setMinimumValue (int value)
int minimumValue ()
void setMaximumValue (int value)
int maximumValue ()
void blockSignals (bool block)
Static Public Member Functions
static void create (RangeSliderWidget *&outputWidget, const QObject *receiver, const char *memberIntermediateMinimumValue, const char *memberIntermediateMaximumValue, const QString &text, const QString &toolTip, const QString &unitsList, int step, int min, int max, int minValue, int maxValue)
Protected Slots
void slotIntermediateMinimumValue (int v)
void slotIntermediateMaximumValue (int v)
Protected Attributes
ctkRangeSlider * slider_
QSpinBox * minSpinBox_
QSpinBox * maxSpinBox_
int minimumValue_
int maximumValue_
Constructor & Destructor Documentation
RangeSliderWidget()
RangeSliderWidget::RangeSliderWidget ()
Referenced by create().
Member Function Documentation
blockSignals()
void RangeSliderWidget::blockSignals (bool block)
Referenced by ProjectNavigatorItemClipping::reset(), ProjectNavigatorItemClipping::slotUpdate(), ProjectNavigatorItemDensity::slotUpdate(), ProjectNavigatorItemDescriptor::slotUpdate(), and ProjectNavigatorItemElevation::slotUpdate().
create()
void RangeSliderWidget::create (RangeSliderWidget *& outputWidget, const QObject * receiver, const char * memberIntermediateMinimumValue, const char * memberIntermediateMaximumValue, const QString & text, const QString & toolTip, const QString & unitsList, int step, int min, int max, int minValue, int maxValue) static
Referenced by ProjectNavigatorItemClipping::ProjectNavigatorItemClipping(), ProjectNavigatorItemDensity::ProjectNavigatorItemDensity(), ProjectNavigatorItemDescriptor::ProjectNavigatorItemDescriptor(), ProjectNavigatorItemElevation::ProjectNavigatorItemElevation(), and SegmentationWindow::SegmentationWindow().
maximumValue()
int RangeSliderWidget::maximumValue ()
Referenced by SegmentationWindow::resumeThreads(), ProjectNavigatorItemClipping::slotRangeIntermediateMaximumValue(), ProjectNavigatorItemDensity::slotRangeIntermediateMaximumValue(), ProjectNavigatorItemDescriptor::slotRangeIntermediateMaximumValue(), ProjectNavigatorItemElevation::slotRangeIntermediateMaximumValue(), and SegmentationWindow::slotSeedElevationMaximumValue().
minimumValue()
int RangeSliderWidget::minimumValue ()
Referenced by SegmentationWindow::resumeThreads(), ProjectNavigatorItemClipping::slotRangeIntermediateMinimumValue(), ProjectNavigatorItemDensity::slotRangeIntermediateMinimumValue(), ProjectNavigatorItemDescriptor::slotRangeIntermediateMinimumValue(), ProjectNavigatorItemElevation::slotRangeIntermediateMinimumValue(), and SegmentationWindow::slotSeedElevationMinimumValue().
setMaximum()
void RangeSliderWidget::setMaximum (int max)
Referenced by ProjectNavigatorItemClipping::slotUpdate(), ProjectNavigatorItemDensity::slotUpdate(), ProjectNavigatorItemDescriptor::slotUpdate(), and ProjectNavigatorItemElevation::slotUpdate().
setMaximumValue()
void RangeSliderWidget::setMaximumValue (int value)
Referenced by ProjectNavigatorItemClipping::reset(), ProjectNavigatorItemClipping::slotUpdate(), ProjectNavigatorItemDensity::slotUpdate(), ProjectNavigatorItemDescriptor::slotUpdate(), and ProjectNavigatorItemElevation::slotUpdate().
setMinimum()
void RangeSliderWidget::setMinimum (int min)
Referenced by ProjectNavigatorItemClipping::slotUpdate(), ProjectNavigatorItemDensity::slotUpdate(), ProjectNavigatorItemDescriptor::slotUpdate(), and ProjectNavigatorItemElevation::slotUpdate().
setMinimumValue()
void RangeSliderWidget::setMinimumValue (int value)
Referenced by ProjectNavigatorItemClipping::reset(), ProjectNavigatorItemClipping::slotUpdate(), ProjectNavigatorItemDensity::slotUpdate(), ProjectNavigatorItemDescriptor::slotUpdate(), and ProjectNavigatorItemElevation::slotUpdate().
signalIntermediateMaximumValue
void RangeSliderWidget::signalIntermediateMaximumValue () signal
Referenced by create(), and slotIntermediateMaximumValue().
signalIntermediateMinimumValue
void RangeSliderWidget::signalIntermediateMinimumValue () signal
Referenced by create(), and slotIntermediateMinimumValue().
slotIntermediateMaximumValue
void RangeSliderWidget::slotIntermediateMaximumValue (int v) protected slot
Referenced by create().
slotIntermediateMinimumValue
void RangeSliderWidget::slotIntermediateMinimumValue (int v) protected slot
Referenced by create().
Member Data Documentation
maximumValue_
int RangeSliderWidget::maximumValue_ protected
Referenced by create(), maximumValue(), setMaximum(), setMaximumValue(), and slotIntermediateMaximumValue().
maxSpinBox_
QSpinBox* RangeSliderWidget::maxSpinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMaximumValue(), setMinimum(), and slotIntermediateMaximumValue().
minimumValue_
int RangeSliderWidget::minimumValue_ protected
Referenced by create(), minimumValue(), setMinimum(), setMinimumValue(), and slotIntermediateMinimumValue().
minSpinBox_
QSpinBox* RangeSliderWidget::minSpinBox_ protected
Referenced by blockSignals(), create(), setMaximum(), setMinimum(), setMinimumValue(), and slotIntermediateMinimumValue().
slider_
ctkRangeSlider* RangeSliderWidget::slider_ protected
Referenced by blockSignals(), create(), setMaximum(), setMaximumValue(), setMinimum(), setMinimumValue(), slotIntermediateMaximumValue(), and slotIntermediateMinimumValue().
The documentation for this class was generated from the following files:
RangeSliderWidget.hpp
RangeSliderWidget.cpp