3D Forest: ExplorerLayersWidget Class Reference
ExplorerLayersWidget Class Reference
#include <ExplorerLayersWidget.hpp>
Inherits ExplorerWidgetInterface.
Public Slots
void slotUpdate (void *sender, const QSet< Editor::Type > &target)
void slotAdd ()
void slotDelete ()
void slotShow ()
void slotHide ()
void slotSelectAll ()
void slotSelectInvert ()
void slotSelectNone ()
void slotItemSelectionChanged ()
void slotItemChanged (QTreeWidgetItem *item, int column)
Public Member Functions
ExplorerLayersWidget (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual bool hasColorSource () const
virtual SettingsView::ColorSource colorSource () const
virtual bool hasFilter () const
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Public Member Functions inherited from ExplorerWidgetInterface
ExplorerWidgetInterface (MainWindow *mainWindow, const QIcon &icon, const QString &text)
virtual ~ExplorerWidgetInterface ()=default
const QIcon & icon ()
const QString & text ()
virtual bool hasColorSource () const =0
virtual SettingsView::ColorSource colorSource () const =0
virtual bool hasFilter () const =0
virtual bool isFilterEnabled () const
virtual void setFilterEnabled (bool b)
Protected Types
enum Column { COLUMN_CHECKED , COLUMN_ID , COLUMN_LABEL , COLUMN_LAST }
Protected Member Functions
void setLayers (const Layers &layers, const QueryFilterSet &filter)
void dataChanged ()
void filterChanged ()
size_t identifier (const QTreeWidgetItem *item)
size_t index (const QTreeWidgetItem *item)
void updateTree ()
void block ()
void unblock ()
void addTreeItem (size_t index)
Protected Attributes
QTreeWidget * tree_
QToolButton * addButton_
QToolButton * deleteButton_
QToolButton * showButton_
QToolButton * hideButton_
QToolButton * selectAllButton_
QToolButton * selectInvertButton_
QToolButton * selectNoneButton_
Layers layers_
QueryFilterSet filter_
bool updatesEnabled_
Protected Attributes inherited from ExplorerWidgetInterface
MainWindow * mainWindow_
QIcon icon_
QString text_
QLabel * titleIcon_
QLabel * titleText_
QVBoxLayout * mainLayout_
Member Enumeration Documentation
Column
enum ExplorerLayersWidget::Column protected
Explorer Layers Column.
Enumerator
COLUMN_CHECKED
COLUMN_ID
COLUMN_LABEL
COLUMN_LAST
Constructor & Destructor Documentation
ExplorerLayersWidget()
ExplorerLayersWidget::ExplorerLayersWidget (MainWindow * mainWindow, const QIcon & icon, const QString & text)
Member Function Documentation
addTreeItem()
void ExplorerLayersWidget::addTreeItem (size_t index) protected
Referenced by setLayers().
block()
void ExplorerLayersWidget::block () protected
Referenced by setLayers(), and updateTree().
colorSource()
virtual SettingsView::ColorSource ExplorerLayersWidget::colorSource () const inline virtual
Implements ExplorerWidgetInterface.
dataChanged()
void ExplorerLayersWidget::dataChanged () protected
Referenced by slotDelete().
filterChanged()
void ExplorerLayersWidget::filterChanged () protected
Referenced by setFilterEnabled(), slotHide(), slotItemChanged(), and slotShow().
hasColorSource()
virtual bool ExplorerLayersWidget::hasColorSource () const inline virtual
Implements ExplorerWidgetInterface.
hasFilter()
virtual bool ExplorerLayersWidget::hasFilter () const inline virtual
Implements ExplorerWidgetInterface.
identifier()
size_t ExplorerLayersWidget::identifier (const QTreeWidgetItem * item) protected
Referenced by slotDelete(), slotItemChanged(), and updateTree().
index()
size_t ExplorerLayersWidget::index (const QTreeWidgetItem * item) protected
Referenced by addTreeItem(), and slotDelete().
isFilterEnabled()
bool ExplorerLayersWidget::isFilterEnabled () const virtual
Reimplemented from ExplorerWidgetInterface.
setFilterEnabled()
void ExplorerLayersWidget::setFilterEnabled (bool b) virtual
Reimplemented from ExplorerWidgetInterface.
setLayers()
void ExplorerLayersWidget::setLayers (const Layers & layers, const QueryFilterSet & filter) protected
Referenced by slotUpdate().
slotAdd
void ExplorerLayersWidget::slotAdd () slot
Referenced by ExplorerLayersWidget().
slotDelete
void ExplorerLayersWidget::slotDelete () slot
Referenced by ExplorerLayersWidget().
slotHide
void ExplorerLayersWidget::slotHide () slot
Referenced by ExplorerLayersWidget().
slotItemChanged
void ExplorerLayersWidget::slotItemChanged (QTreeWidgetItem * item, int column) slot
Referenced by unblock().
slotItemSelectionChanged
void ExplorerLayersWidget::slotItemSelectionChanged () slot
Referenced by slotSelectAll(), slotSelectInvert(), slotSelectNone(), and unblock().
slotSelectAll
void ExplorerLayersWidget::slotSelectAll () slot
Referenced by ExplorerLayersWidget().
slotSelectInvert
void ExplorerLayersWidget::slotSelectInvert () slot
Referenced by ExplorerLayersWidget().
slotSelectNone
void ExplorerLayersWidget::slotSelectNone () slot
Referenced by ExplorerLayersWidget(), and slotDelete().
slotShow
void ExplorerLayersWidget::slotShow () slot
Referenced by ExplorerLayersWidget().
slotUpdate
void ExplorerLayersWidget::slotUpdate (void * sender, const QSet< Editor::Type > & target) slot
Referenced by ExplorerLayersWidget().
unblock()
void ExplorerLayersWidget::unblock () protected
Referenced by setLayers(), and updateTree().
updateTree()
void ExplorerLayersWidget::updateTree () protected
Member Data Documentation
addButton_
QToolButton* ExplorerLayersWidget::addButton_ protected
Referenced by ExplorerLayersWidget().
deleteButton_
QToolButton* ExplorerLayersWidget::deleteButton_ protected
Referenced by ExplorerLayersWidget(), and slotItemSelectionChanged().
filter_
QueryFilterSet ExplorerLayersWidget::filter_ protected
Referenced by addTreeItem(), dataChanged(), filterChanged(), isFilterEnabled(), setFilterEnabled(), setLayers(), slotDelete(), slotItemChanged(), and updateTree().
hideButton_
QToolButton* ExplorerLayersWidget::hideButton_ protected
Referenced by ExplorerLayersWidget(), and slotItemSelectionChanged().
layers_
Layers ExplorerLayersWidget::layers_ protected
Referenced by addTreeItem(), dataChanged(), index(), setLayers(), and slotDelete().
selectAllButton_
QToolButton* ExplorerLayersWidget::selectAllButton_ protected
Referenced by ExplorerLayersWidget().
selectInvertButton_
QToolButton* ExplorerLayersWidget::selectInvertButton_ protected
Referenced by ExplorerLayersWidget().
selectNoneButton_
QToolButton* ExplorerLayersWidget::selectNoneButton_ protected
Referenced by ExplorerLayersWidget().
showButton_
QToolButton* ExplorerLayersWidget::showButton_ protected
Referenced by ExplorerLayersWidget(), and slotItemSelectionChanged().
tree_
QTreeWidget* ExplorerLayersWidget::tree_ protected
Referenced by addTreeItem(), block(), ExplorerLayersWidget(), setLayers(), slotDelete(), slotHide(), slotItemSelectionChanged(), slotSelectAll(), slotSelectInvert(), slotSelectNone(), slotShow(), unblock(), and updateTree().
updatesEnabled_
bool ExplorerLayersWidget::updatesEnabled_ protected
Referenced by ExplorerLayersWidget(), slotHide(), slotItemChanged(), and slotShow().
The documentation for this class was generated from the following files:
ExplorerLayersWidget.hpp
ExplorerLayersWidget.cpp