3D Forest: ExplorerClippingBoxWidget Class Reference
ExplorerClippingBoxWidget Class Reference
#include <ExplorerClippingBoxWidget.hpp>
Inherits QWidget.
Public Slots
void slotRangeIntermediateMinimumValue ()
void slotRangeIntermediateMaximumValue ()
Signals
void signalRegionChanged (const Region &region)
Public Member Functions
ExplorerClippingBoxWidget (MainWindow *mainWindow)
void setRegion (const Region &region)
Protected Member Functions
void updateRegion ()
Protected Attributes
DoubleRangeSliderWidget * rangeInput_ [3]
Range< double > clipRange_ [3]
Constructor & Destructor Documentation
ExplorerClippingBoxWidget()
ExplorerClippingBoxWidget::ExplorerClippingBoxWidget (MainWindow * mainWindow)
Member Function Documentation
setRegion()
void ExplorerClippingBoxWidget::setRegion (const Region & region)
Referenced by ExplorerClippingWidget::slotUpdate().
signalRegionChanged
void ExplorerClippingBoxWidget::signalRegionChanged (const Region & region) signal
Referenced by updateRegion().
slotRangeIntermediateMaximumValue
void ExplorerClippingBoxWidget::slotRangeIntermediateMaximumValue () slot
Referenced by ExplorerClippingBoxWidget().
slotRangeIntermediateMinimumValue
void ExplorerClippingBoxWidget::slotRangeIntermediateMinimumValue () slot
Referenced by ExplorerClippingBoxWidget().
updateRegion()
void ExplorerClippingBoxWidget::updateRegion () protected
Referenced by slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
Member Data Documentation
clipRange_
Range<double> ExplorerClippingBoxWidget::clipRange_[3] protected
Referenced by setRegion(), slotRangeIntermediateMaximumValue(), slotRangeIntermediateMinimumValue(), and updateRegion().
rangeInput_
DoubleRangeSliderWidget* ExplorerClippingBoxWidget::rangeInput_[3] protected
Referenced by ExplorerClippingBoxWidget(), setRegion(), slotRangeIntermediateMaximumValue(), and slotRangeIntermediateMinimumValue().
The documentation for this class was generated from the following files:
ExplorerClippingBoxWidget.hpp
ExplorerClippingBoxWidget.cpp