3D Forest: ViewerPlugin Class Reference
ViewerPlugin Class Reference
#include <ViewerPlugin.hpp>
Inherits QObject, PluginInterface, and ViewerInterface.
Public Slots
void slotViewOrthographic ()
void slotViewPerspective ()
void slotViewTop ()
void slotViewFront ()
void slotViewRight ()
void slotView3d ()
void slotViewResetDistance ()
void slotViewResetCenter ()
void slotViewLayoutSingle ()
void slotViewLayoutTwoColumns ()
void slotViewLayoutGrid ()
void slotViewLayoutThreeRowsRight ()
void slotViewLayout (ViewerViewports::ViewLayout layout)
Public Member Functions
ViewerPlugin ()
virtual void initialize (MainWindow *mainWindow)
virtual std::vector< Camera > camera (size_t viewportId) const
virtual std::vector< Camera > camera () const
virtual void updateScene (Editor *editor)
virtual void resetScene (Editor *editor, bool resetView)
Public Member Functions inherited from PluginInterface
virtual ~PluginInterface ()=default
Public Member Functions inherited from ViewerInterface
virtual ~ViewerInterface ()=default
Private Member Functions
void updateViewer ()
Private Attributes
MainWindow * mainWindow_
QAction * viewOrthographicAction_
QAction * viewPerspectiveAction_
QAction * viewTopAction_
QAction * viewFrontAction_
QAction * viewRightAction_
QAction * view3dAction_
QAction * viewResetDistanceAction_
QAction * viewResetCenterAction_
QAction * viewLayoutSingleAction_
QAction * viewLayoutTwoColumnsAction_
QAction * viewLayoutGridAction_
QAction * viewLayoutThreeRowsRightAction_
ViewerViewports * viewports_
Constructor & Destructor Documentation
ViewerPlugin()
ViewerPlugin::ViewerPlugin ()
Member Function Documentation
camera() [1/2]
std::vector< Camera > ViewerPlugin::camera () const virtual
Implements ViewerInterface.
camera() [2/2]
std::vector< Camera > ViewerPlugin::camera (size_t viewportId) const virtual
Implements ViewerInterface.
initialize()
void ViewerPlugin::initialize (MainWindow * mainWindow) virtual
Implements PluginInterface.
resetScene()
void ViewerPlugin::resetScene (Editor * editor, bool resetView) virtual
Implements ViewerInterface.
slotView3d
void ViewerPlugin::slotView3d () slot
Referenced by initialize().
slotViewFront
void ViewerPlugin::slotViewFront () slot
Referenced by initialize().
slotViewLayout
void ViewerPlugin::slotViewLayout (ViewerViewports::ViewLayout layout) slot
Referenced by slotViewLayoutGrid(), slotViewLayoutSingle(), slotViewLayoutThreeRowsRight(), and slotViewLayoutTwoColumns().
slotViewLayoutGrid
void ViewerPlugin::slotViewLayoutGrid () slot
Referenced by initialize().
slotViewLayoutSingle
void ViewerPlugin::slotViewLayoutSingle () slot
Referenced by initialize().
slotViewLayoutThreeRowsRight
void ViewerPlugin::slotViewLayoutThreeRowsRight () slot
Referenced by initialize().
slotViewLayoutTwoColumns
void ViewerPlugin::slotViewLayoutTwoColumns () slot
Referenced by initialize().
slotViewOrthographic
void ViewerPlugin::slotViewOrthographic () slot
Referenced by initialize().
slotViewPerspective
void ViewerPlugin::slotViewPerspective () slot
Referenced by initialize().
slotViewResetCenter
void ViewerPlugin::slotViewResetCenter () slot
Referenced by initialize().
slotViewResetDistance
void ViewerPlugin::slotViewResetDistance () slot
Referenced by initialize().
slotViewRight
void ViewerPlugin::slotViewRight () slot
Referenced by initialize().
slotViewTop
void ViewerPlugin::slotViewTop () slot
Referenced by initialize().
updateScene()
void ViewerPlugin::updateScene (Editor * editor) virtual
Implements ViewerInterface.
updateViewer()
void ViewerPlugin::updateViewer () private
Referenced by slotView3d(), slotViewFront(), slotViewLayout(), slotViewOrthographic(), slotViewPerspective(), slotViewResetCenter(), slotViewResetDistance(), slotViewRight(), and slotViewTop().
Member Data Documentation
mainWindow_
MainWindow* ViewerPlugin::mainWindow_ private
Referenced by initialize(), slotViewLayout(), and updateViewer().
view3dAction_
QAction* ViewerPlugin::view3dAction_ private
Referenced by initialize().
viewFrontAction_
QAction* ViewerPlugin::viewFrontAction_ private
Referenced by initialize().
viewLayoutGridAction_
QAction* ViewerPlugin::viewLayoutGridAction_ private
Referenced by initialize().
viewLayoutSingleAction_
QAction* ViewerPlugin::viewLayoutSingleAction_ private
Referenced by initialize().
viewLayoutThreeRowsRightAction_
QAction* ViewerPlugin::viewLayoutThreeRowsRightAction_ private
Referenced by initialize().
viewLayoutTwoColumnsAction_
QAction* ViewerPlugin::viewLayoutTwoColumnsAction_ private
Referenced by initialize().
viewOrthographicAction_
QAction* ViewerPlugin::viewOrthographicAction_ private
Referenced by initialize().
viewPerspectiveAction_
QAction* ViewerPlugin::viewPerspectiveAction_ private
Referenced by initialize().
viewports_
ViewerViewports* ViewerPlugin::viewports_ private
Referenced by camera(), camera(), initialize(), resetScene(), slotView3d(), slotViewFront(), slotViewLayout(), slotViewOrthographic(), slotViewPerspective(), slotViewResetCenter(), slotViewResetDistance(), slotViewRight(), slotViewTop(), and updateScene().
viewResetCenterAction_
QAction* ViewerPlugin::viewResetCenterAction_ private
Referenced by initialize().
viewResetDistanceAction_
QAction* ViewerPlugin::viewResetDistanceAction_ private
Referenced by initialize().
viewRightAction_
QAction* ViewerPlugin::viewRightAction_ private
Referenced by initialize().
viewTopAction_
QAction* ViewerPlugin::viewTopAction_ private
Referenced by initialize().
The documentation for this class was generated from the following files:
ViewerPlugin.hpp
ViewerPlugin.cpp