3D Forest: ViewerInterface Class Reference
ViewerInterface Class Reference abstract
#include <ViewerInterface.hpp>
Inherited by ViewerPlugin.
Public Member Functions
virtual ~ViewerInterface ()=default
virtual std::vector< Camera > camera (size_t viewportId) const =0
virtual std::vector< Camera > camera () const =0
virtual void updateScene (Editor *editor)=0
virtual void resetScene (Editor *editor, bool resetView)=0
Constructor & Destructor Documentation
~ViewerInterface()
virtual ViewerInterface::~ViewerInterface () virtual default
Member Function Documentation
camera() [1/2]
virtual std::vector< Camera > ViewerInterface::camera () const pure virtual
Implemented in ViewerPlugin.
camera() [2/2]
virtual std::vector< Camera > ViewerInterface::camera (size_t viewportId) const pure virtual
Implemented in ViewerPlugin.
Referenced by MainWindow::slotRenderViewport(), and MainWindow::slotRenderViewports().
resetScene()
virtual void ViewerInterface::resetScene (Editor * editor, bool resetView) pure virtual
Implemented in ViewerPlugin.
Referenced by MainWindow::MainWindow(), MainWindow::update(), MainWindow::updateData(), MainWindow::updateFilter(), and MainWindow::updateNewProject().
updateScene()
virtual void ViewerInterface::updateScene (Editor * editor) pure virtual
Implemented in ViewerPlugin.
Referenced by MainWindow::slotRender().
The documentation for this class was generated from the following file:
ViewerInterface.hpp