3D Forest: ColorPalette Class Reference
ColorPalette Class Reference
#include <ColorPalette.hpp>
Static Public Member Functions
static std::vector< Vector3< double > > blueCyanYellowRed (size_t nColors)
static std::vector< Vector3< double > > blueCyanGreenYellowRed (size_t nColors)
static std::vector< Vector3< double > > gray (size_t nColors)
Static Public Attributes
static const std::vector< Vector3< double > > Classification
static const std::vector< Vector3< double > > BlackRed16
static const std::vector< Vector3< double > > BlackGreen16
static const std::vector< Vector3< double > > RedBlack16
static const std::vector< Vector3< double > > RedGreen16
static const std::vector< Vector3< double > > RedYellow16
static const std::vector< Vector3< double > > BlueYellow16
static const std::vector< Vector3< double > > BlueCyanYellowRed16
static const std::vector< Vector3< double > > BlueCyanYellowRed256
static const std::vector< Vector3< double > > BlueCyanGreenYellowRed16
static const std::vector< Vector3< double > > WindowsXp32
static const std::vector< Vector3< double > > MPN65
Member Function Documentation
blueCyanGreenYellowRed()
std::vector< Vector3< double > > ColorPalette::blueCyanGreenYellowRed (size_t nColors) static
Referenced by ComputeHeightMapModifier::createColormap().
blueCyanYellowRed()
std::vector< Vector3< double > > ColorPalette::blueCyanYellowRed (size_t nColors) static
Referenced by ComputeHeightMapModifier::createColormap().
gray()
std::vector< Vector3< double > > ColorPalette::gray (size_t nColors) static
Referenced by ComputeHeightMapModifier::createColormap().
Member Data Documentation
BlackGreen16
const std::vector< Vector3< double > > ColorPalette::BlackGreen16 static
Initial value:
= {
    {0.0, 0x0 * (1.0 / 15), 0.0},
    {0.0, 0x1 * (1.0 / 15), 0.0},
    {0.0, 0x2 * (1.0 / 15), 0.0},
    {0.0, 0x3 * (1.0 / 15), 0.0},
    {0.0, 0x4 * (1.0 / 15), 0.0},
    {0.0, 0x5 * (1.0 / 15), 0.0},
    {0.0, 0x6 * (1.0 / 15), 0.0},
    {0.0, 0x7 * (1.0 / 15), 0.0},
    {0.0, 0x8 * (1.0 / 15), 0.0},
    {0.0, 0x9 * (1.0 / 15), 0.0},
    {0.0, 0xa * (1.0 / 15), 0.0},
    {0.0, 0xb * (1.0 / 15), 0.0},
    {0.0, 0xc * (1.0 / 15), 0.0},
    {0.0, 0xd * (1.0 / 15), 0.0},
    {0.0, 0xe * (1.0 / 15), 0.0},
    {0.0, 0xf * (1.0 / 15), 0.0},
}
BlackRed16
const std::vector< Vector3< double > > ColorPalette::BlackRed16 static
Initial value:
= {
    {0x0 * (1.0 / 15), 0.0, 0.0},
    {0x1 * (1.0 / 15), 0.0, 0.0},
    {0x2 * (1.0 / 15), 0.0, 0.0},
    {0x3 * (1.0 / 15), 0.0, 0.0},
    {0x4 * (1.0 / 15), 0.0, 0.0},
    {0x5 * (1.0 / 15), 0.0, 0.0},
    {0x6 * (1.0 / 15), 0.0, 0.0},
    {0x7 * (1.0 / 15), 0.0, 0.0},
    {0x8 * (1.0 / 15), 0.0, 0.0},
    {0x9 * (1.0 / 15), 0.0, 0.0},
    {0xa * (1.0 / 15), 0.0, 0.0},
    {0xb * (1.0 / 15), 0.0, 0.0},
    {0xc * (1.0 / 15), 0.0, 0.0},
    {0xd * (1.0 / 15), 0.0, 0.0},
    {0xe * (1.0 / 15), 0.0, 0.0},
    {0xf * (1.0 / 15), 0.0, 0.0},
}
BlueCyanGreenYellowRed16
const std::vector< Vector3< double > > ColorPalette::BlueCyanGreenYellowRed16 static
Initial value:
= {
    {0.000000, 0.000000, 1.000000},
    {0.000000, 0.333333, 1.000000},
    {0.000000, 0.666667, 1.000000},
    {0.000000, 1.000000, 1.000000},
    {0.000000, 1.000000, 0.666667},
    {0.000000, 1.000000, 0.333333},
    {0.000000, 1.000000, 0.000000},
    {0.333333, 1.000000, 0.000000},
    {0.666667, 1.000000, 0.000000},
    {1.000000, 1.000000, 0.000000},
    {1.000000, 0.833333, 0.000000},
    {1.000000, 0.666667, 0.000000},
    {1.000000, 0.500000, 0.000000},
    {1.000000, 0.333333, 0.000000},
    {1.000000, 0.166667, 0.000000},
    {1.000000, 0.000000, 0.000000},
}
Referenced by Page::runColorModifier().
BlueCyanYellowRed16
const std::vector< Vector3< double > > ColorPalette::BlueCyanYellowRed16 static
Initial value:
= {
    {0.000000, 0.000000, 0.500000},
    {0.000000, 0.000000, 0.750000},
    {0.000000, 0.000000, 1.000000},
    {0.000000, 0.250000, 1.000000},
    {0.000000, 0.500000, 1.000000},
    {0.000000, 0.750000, 1.000000},
    {0.000000, 1.000000, 1.000000},
    {0.250000, 1.000000, 0.750000},
    {0.500000, 1.000000, 0.500000},
    {0.750000, 1.000000, 0.250000},
    {1.000000, 1.000000, 0.000000},
    {1.000000, 0.750000, 0.000000},
    {1.000000, 0.500000, 0.000000},
    {1.000000, 0.250000, 0.000000},
    {1.000000, 0.000000, 0.000000},
    {0.500000, 0.000000, 0.000000},
}
BlueCyanYellowRed256
const std::vector< Vector3< double > > ColorPalette::BlueCyanYellowRed256 static
Referenced by Page::runColorModifier().
BlueYellow16
const std::vector< Vector3< double > > ColorPalette::BlueYellow16 static
Initial value:
= {
    {0x0 * (1.0 / 15), 1.0, 1.0 - 0x0 * (1.0 / 15)},
    {0x1 * (1.0 / 15), 1.0, 1.0 - 0x1 * (1.0 / 15)},
    {0x2 * (1.0 / 15), 1.0, 1.0 - 0x2 * (1.0 / 15)},
    {0x3 * (1.0 / 15), 1.0, 1.0 - 0x3 * (1.0 / 15)},
    {0x4 * (1.0 / 15), 1.0, 1.0 - 0x4 * (1.0 / 15)},
    {0x5 * (1.0 / 15), 1.0, 1.0 - 0x5 * (1.0 / 15)},
    {0x6 * (1.0 / 15), 1.0, 1.0 - 0x6 * (1.0 / 15)},
    {0x7 * (1.0 / 15), 1.0, 1.0 - 0x7 * (1.0 / 15)},
    {0x8 * (1.0 / 15), 1.0, 1.0 - 0x8 * (1.0 / 15)},
    {0x9 * (1.0 / 15), 1.0, 1.0 - 0x9 * (1.0 / 15)},
    {0xa * (1.0 / 15), 1.0, 1.0 - 0xa * (1.0 / 15)},
    {0xb * (1.0 / 15), 1.0, 1.0 - 0xb * (1.0 / 15)},
    {0xc * (1.0 / 15), 1.0, 1.0 - 0xc * (1.0 / 15)},
    {0xd * (1.0 / 15), 1.0, 1.0 - 0xd * (1.0 / 15)},
    {0xe * (1.0 / 15), 1.0, 1.0 - 0xe * (1.0 / 15)},
    {0xf * (1.0 / 15), 1.0, 1.0 - 0xf * (1.0 / 15)},
}
Classification
const std::vector< Vector3< double > > ColorPalette::Classification static
Initial value:
{
    0xaaaaaaU,
    0xb2b2b2U,
    0xa87102U,
    0x407d00U,
    0x5cb200U,
    0x85ff00U,
    0xe64d43U,
    0xe60101U,
    0xff55ffU,
    0x035ee6U,
    0x8504a9U,
    0xffff03U,
    0xee4feeU,
    0xaaffffU,
    0x00ffffU,
    0xb3b300U,
    0xaaaaffU,
    0xe6e6e6U,
    0xff0000U,
}
Referenced by FilterClassificationWidget::addTreeItem(), and Page::runColorModifier().
MPN65
const std::vector< Vector3< double > > ColorPalette::MPN65 static
Initial value:
= {
    0xff0029U, 0x377eb8U, 0x66a61eU, 0x984ea3U, 0x00d2d5U, 0xff7f00U, 0xaf8d00U,
    0x7f80cdU, 0xb3e900U, 0xc42e60U, 0xa65628U, 0xf781bfU, 0x8dd3c7U, 0xbebadaU,
    0xfb8072U, 0x80b1d3U, 0xfdb462U, 0xfccde5U, 0xbc80bdU, 0xffed6fU, 0xc4eaffU,
    0xcf8c00U, 0x1b9e77U, 0xd95f02U, 0xe7298aU, 0xe6ab02U, 0xa6761dU, 0x0097ffU,
    0x00d067U, 0x000000U, 0x252525U, 0x525252U, 0x737373U, 0x969696U, 0xbdbdbdU,
    0xf43600U, 0x4ba93bU, 0x5779bbU, 0x927accU, 0x97ee3fU, 0xbf3947U, 0x9f5b00U,
    0xf48758U, 0x8caed6U, 0xf2b94fU, 0xeff26eU, 0xe43872U, 0xd9b100U, 0x9d7a00U,
    0x698cffU, 0xd9d9d9U, 0x00d27eU, 0xd06800U, 0x009f82U, 0xc49200U, 0xcbe8ffU,
    0xfecddfU, 0xc27eb6U, 0x8cd2ceU, 0xc4b8d9U, 0xf883b0U, 0xa49100U, 0xf48800U,
    0x27d0dfU, 0xa04a9bU}
Referenced by ComputeSegmentationNNAction::createSegmentFromGroup().
RedBlack16
const std::vector< Vector3< double > > ColorPalette::RedBlack16 static
Initial value:
= {
    {1.0 - 0x0 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x1 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x2 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x3 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x4 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x5 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x6 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x7 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x8 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0x9 * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xa * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xb * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xc * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xd * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xe * (1.0 / 15), 0.0, 0.0},
    {1.0 - 0xf * (1.0 / 15), 0.0, 0.0},
}
RedGreen16
const std::vector< Vector3< double > > ColorPalette::RedGreen16 static
Initial value:
= {
    {1.0 - 0x0 * (1.0 / 15), 0x0 * (1.0 / 15), 0.0},
    {1.0 - 0x1 * (1.0 / 15), 0x1 * (1.0 / 15), 0.0},
    {1.0 - 0x2 * (1.0 / 15), 0x2 * (1.0 / 15), 0.0},
    {1.0 - 0x3 * (1.0 / 15), 0x3 * (1.0 / 15), 0.0},
    {1.0 - 0x4 * (1.0 / 15), 0x4 * (1.0 / 15), 0.0},
    {1.0 - 0x5 * (1.0 / 15), 0x5 * (1.0 / 15), 0.0},
    {1.0 - 0x6 * (1.0 / 15), 0x6 * (1.0 / 15), 0.0},
    {1.0 - 0x7 * (1.0 / 15), 0x7 * (1.0 / 15), 0.0},
    {1.0 - 0x8 * (1.0 / 15), 0x8 * (1.0 / 15), 0.0},
    {1.0 - 0x9 * (1.0 / 15), 0x9 * (1.0 / 15), 0.0},
    {1.0 - 0xa * (1.0 / 15), 0xa * (1.0 / 15), 0.0},
    {1.0 - 0xb * (1.0 / 15), 0xb * (1.0 / 15), 0.0},
    {1.0 - 0xc * (1.0 / 15), 0xc * (1.0 / 15), 0.0},
    {1.0 - 0xd * (1.0 / 15), 0xd * (1.0 / 15), 0.0},
    {1.0 - 0xe * (1.0 / 15), 0xe * (1.0 / 15), 0.0},
    {1.0 - 0xf * (1.0 / 15), 0xf * (1.0 / 15), 0.0},
}
RedYellow16
const std::vector< Vector3< double > > ColorPalette::RedYellow16 static
Initial value:
= {
    {1.0, 0x0 * (1.0 / 15), 0.0},
    {1.0, 0x1 * (1.0 / 15), 0.0},
    {1.0, 0x2 * (1.0 / 15), 0.0},
    {1.0, 0x3 * (1.0 / 15), 0.0},
    {1.0, 0x4 * (1.0 / 15), 0.0},
    {1.0, 0x5 * (1.0 / 15), 0.0},
    {1.0, 0x6 * (1.0 / 15), 0.0},
    {1.0, 0x7 * (1.0 / 15), 0.0},
    {1.0, 0x8 * (1.0 / 15), 0.0},
    {1.0, 0x9 * (1.0 / 15), 0.0},
    {1.0, 0xa * (1.0 / 15), 0.0},
    {1.0, 0xb * (1.0 / 15), 0.0},
    {1.0, 0xc * (1.0 / 15), 0.0},
    {1.0, 0xd * (1.0 / 15), 0.0},
    {1.0, 0xe * (1.0 / 15), 0.0},
    {1.0, 0xf * (1.0 / 15), 0.0},
}
WindowsXp32
const std::vector< Vector3< double > > ColorPalette::WindowsXp32 static
Initial value:
= {
    0x996600U, 0xcc9900U, 0xffcc00U, 0xffff00U, 0xffff99U, 0xffdb9dU,
    0xffcc66U, 0xff9933U, 0xff794bU, 0xff3300U, 0x990000U, 0x333366U,
    0x003399U, 0x0066ccU, 0x0083d7U, 0x0099ffU,
    0x3e9adeU, 0x99ccffU, 0xb4e2ffU, 0xdeffffU, 0xffccffU, 0xccccffU,
    0x9999ffU, 0x6666ccU, 0x9999ccU, 0x666699U, 0x006600U, 0x009900U,
    0x66cc33U, 0x99ff66U, 0xccf4ccU, 0xffffffU}
Referenced by ComputeHeightMapModifier::createColormap().
The documentation for this class was generated from the following files:
ColorPalette.hpp
ColorPalette.cpp