3D Forest: QueryWhere Class Reference
QueryWhere Class Reference
#include <QueryWhere.hpp>
Public Member Functions
QueryWhere ()
~QueryWhere ()
void clear ()
void setDataset (const std::unordered_set< size_t > &list)
void setDataset (const QueryFilterSet &list)
const QueryFilterSet & dataset () const
void setRegion (const Region &region)
const Region & region () const
void setBox (const Box< double > &box)
const Box< double > & box () const
void setCone (double x, double y, double z, double z2, double angle)
const Cone< double > & cone () const
void setCylinder (double ax, double ay, double az, double bx, double by, double bz, double radius)
const Cylinder< double > & cylinder () const
void setSphere (double x, double y, double z, double radius)
const Sphere< double > & sphere () const
void setElevation (const Range< double > &elevation)
const Range< double > & elevation () const
void setDescriptor (const Range< double > &descriptor)
const Range< double > & descriptor () const
void setIntensity (const Range< double > &intensity)
const Range< double > & intensity () const
void setClassification (const std::unordered_set< size_t > &list)
void setClassification (const QueryFilterSet &list)
const QueryFilterSet & classification () const
const std::vector< int > & classificationArray () const
void setSegment (const std::unordered_set< size_t > &list)
void setSegment (const QueryFilterSet &list)
const QueryFilterSet & segment () const
Private Member Functions
void classificationsToArray ()
Private Attributes
Region region_
Range< double > elevation_
Range< double > descriptor_
Range< double > intensity_
QueryFilterSet dataset_
QueryFilterSet classification_
std::vector< int > classificationArray_
QueryFilterSet segment_
Constructor & Destructor Documentation
QueryWhere()
QueryWhere::QueryWhere ()
~QueryWhere()
QueryWhere::~QueryWhere ()
Member Function Documentation
box()
const Box< double > & QueryWhere::box () const inline
Referenced by setBox().
classification()
const QueryFilterSet & QueryWhere::classification () const inline
Referenced by Page::queryWhereClassification().
classificationArray()
const std::vector< int > & QueryWhere::classificationArray () const inline
Referenced by Page::queryWhereClassification().
classificationsToArray()
void QueryWhere::classificationsToArray () private
Referenced by setClassification(), and setClassification().
clear()
void QueryWhere::clear ()
Referenced by Query::clear().
cone()
const Cone< double > & QueryWhere::cone () const inline
cylinder()
const Cylinder< double > & QueryWhere::cylinder () const inline
dataset()
const QueryFilterSet & QueryWhere::dataset () const inline
Referenced by Query::applyCamera(), and Query::exec().
descriptor()
const Range< double > & QueryWhere::descriptor () const inline
Referenced by Page::queryWhereDescriptor(), and setDescriptor().
elevation()
const Range< double > & QueryWhere::elevation () const inline
Referenced by Page::queryWhereElevation(), and setElevation().
intensity()
const Range< double > & QueryWhere::intensity () const inline
Referenced by Page::queryWhereIntensity(), and setIntensity().
region()
const Region & QueryWhere::region () const inline
Referenced by Query::exec(), Page::queryWhere(), Page::queryWhereBox(), Page::queryWhereCone(), Page::queryWhereCylinder(), Page::queryWhereSphere(), and setRegion().
segment()
const QueryFilterSet & QueryWhere::segment () const inline
Referenced by Page::queryWhereSegment().
setBox()
void QueryWhere::setBox (const Box< double > & box)
Referenced by ComputeHeightMapModifier::apply(), ComputeDescriptorPca::computeDistribution(), and Query::nextVoxel().
setClassification() [1/2]
void QueryWhere::setClassification (const QueryFilterSet & list)
setClassification() [2/2]
void QueryWhere::setClassification (const std::unordered_set< size_t > & list)
Referenced by Editor::applyFilters(), and Editor::setClassificationsFilter().
setCone()
void QueryWhere::setCone (double x, double y, double z, double z2, double angle)
setCylinder()
void QueryWhere::setCylinder (double ax, double ay, double az, double bx, double by, double bz, double radius)
setDataset() [1/2]
void QueryWhere::setDataset (const QueryFilterSet & list)
setDataset() [2/2]
void QueryWhere::setDataset (const std::unordered_set< size_t > & list)
Referenced by Editor::applyFilters(), and Editor::setDatasetsFilter().
setDescriptor()
void QueryWhere::setDescriptor (const Range< double > & descriptor)
Referenced by Editor::applyFilters(), and Editor::setDescriptorFilter().
setElevation()
void QueryWhere::setElevation (const Range< double > & elevation)
Referenced by Editor::applyFilters(), and Editor::setElevationFilter().
setIntensity()
void QueryWhere::setIntensity (const Range< double > & intensity)
Referenced by Editor::applyFilters(), and Editor::setIntensityFilter().
setRegion()
void QueryWhere::setRegion (const Region & region)
Referenced by Editor::applyFilters(), and Editor::setClipFilter().
setSegment() [1/2]
void QueryWhere::setSegment (const QueryFilterSet & list)
setSegment() [2/2]
void QueryWhere::setSegment (const std::unordered_set< size_t > & list)
Referenced by Editor::applyFilters(), and Editor::setSegmentsFilter().
setSphere()
void QueryWhere::setSphere (double x, double y, double z, double radius)
Referenced by ComputeDescriptorPca::computeDescriptor(), ComputeDescriptorAction::computePoint(), ComputeElevationAction::createGroundPoint(), ComputeClassificationAction::createVoxel(), and ComputeSegmentationNNAction::createVoxel().
sphere()
const Sphere< double > & QueryWhere::sphere () const inline
Member Data Documentation
classification_
QueryFilterSet QueryWhere::classification_ private
Referenced by classificationsToArray(), clear(), setClassification(), and setClassification().
classificationArray_
std::vector<int> QueryWhere::classificationArray_ private
Referenced by classificationsToArray(), and clear().
dataset_
QueryFilterSet QueryWhere::dataset_ private
Referenced by clear(), setDataset(), and setDataset().
descriptor_
Range<double> QueryWhere::descriptor_ private
Referenced by clear(), and setDescriptor().
elevation_
Range<double> QueryWhere::elevation_ private
Referenced by clear(), and setElevation().
intensity_
Range<double> QueryWhere::intensity_ private
Referenced by clear(), and setIntensity().
region_
Region QueryWhere::region_ private
Referenced by clear(), setBox(), setCone(), setCylinder(), setRegion(), and setSphere().
segment_
QueryFilterSet QueryWhere::segment_ private
Referenced by clear(), setSegment(), and setSegment().
The documentation for this class was generated from the following files:
QueryWhere.hpp
QueryWhere.cpp