3D Forest: FilterTreesTreeWidget Class Reference
FilterTreesTreeWidget Class Reference
#include <FilterTreesTreeWidget.hpp>
Inherits QWidget.
Public Member Functions
FilterTreesTreeWidget (MainWindow *mainWindow)
void setSegment (const Segment &segment)
void clear ()
Protected Member Functions
void setRow (int row, const std::string &key, const std::string &value)
void setRow (int row, const std::string &key, const Vector3< double > &value)
void setRow (int row, const std::string &key, double value, const std::string &comment="")
Protected Attributes
MainWindow * mainWindow_
QTableWidget * table_
Segment segment_
Constructor & Destructor Documentation
FilterTreesTreeWidget()
FilterTreesTreeWidget::FilterTreesTreeWidget (MainWindow * mainWindow)
Member Function Documentation
clear()
void FilterTreesTreeWidget::clear ()
Referenced by FilterTreesWidget::setSegments().
setRow() [1/3]
void FilterTreesTreeWidget::setRow (int row, const std::string & key, const std::string & value) protected
Referenced by setSegment().
setRow() [2/3]
void FilterTreesTreeWidget::setRow (int row, const std::string & key, const Vector3< double > & value) protected
setRow() [3/3]
void FilterTreesTreeWidget::setRow (int row, const std::string & key, double value, const std::string & comment = "") protected
setSegment()
void FilterTreesTreeWidget::setSegment (const Segment & segment)
Referenced by FilterTreesWidget::setSegments(), and FilterTreesWidget::slotItemClicked().
Member Data Documentation
mainWindow_
MainWindow* FilterTreesTreeWidget::mainWindow_ protected
Referenced by setSegment().
segment_
Segment FilterTreesTreeWidget::segment_ protected
Referenced by setSegment().
table_
QTableWidget* FilterTreesTreeWidget::table_ protected
Referenced by clear(), FilterTreesTreeWidget(), setRow(), setRow(), and setSegment().
The documentation for this class was generated from the following files:
FilterTreesTreeWidget.hpp
FilterTreesTreeWidget.cpp