var hierarchy =
[
    [ "ArgumentParser", "classArgumentParser.html", null ],
    [ "std::array", null, [
      [ "Range< double >", "classRange.html", null ],
      [ "Vector3< double >", "classVector3.html", null ],
      [ "Vector3< size_t >", "classVector3.html", null ],
      [ "Range< T >", "classRange.html", null ],
      [ "Vector2< T >", "classVector2.html", null ],
      [ "Vector3< T >", "classVector3.html", null ]
    ] ],
    [ "LasFile::AttributesBuffer", "structLasFile_1_1AttributesBuffer.html", null ],
    [ "Box< T >", "classBox.html", null ],
    [ "Box< double >", "classBox.html", null ],
    [ "RecordFile::Buffer", "structRecordFile_1_1Buffer.html", null ],
    [ "IndexFile::BuildNode", "structIndexFile_1_1BuildNode.html", null ],
    [ "Camera", "classCamera.html", null ],
    [ "ChunkFile::Chunk", "structChunkFile_1_1Chunk.html", null ],
    [ "ChunkFile", "classChunkFile.html", null ],
    [ "Classification", "classClassification.html", null ],
    [ "Classifications", "classClassifications.html", null ],
    [ "ColorPalette", "classColorPalette.html", null ],
    [ "ComputeClassificationParameters", "classComputeClassificationParameters.html", null ],
    [ "ComputeDescriptorParameters", "classComputeDescriptorParameters.html", null ],
    [ "ComputeDescriptorPca", "classComputeDescriptorPca.html", null ],
    [ "ComputeHeightMapModifier", "classComputeHeightMapModifier.html", null ],
    [ "ComputeSegmentationNNParameters", "classComputeSegmentationNNParameters.html", null ],
    [ "ComputeTreeAttributesData", "classComputeTreeAttributesData.html", null ],
    [ "ComputeTreeAttributesLeastSquaredRegression", "classComputeTreeAttributesLeastSquaredRegression.html", null ],
    [ "ComputeTreeAttributesParameters", "classComputeTreeAttributesParameters.html", null ],
    [ "Cone< T >", "classCone.html", null ],
    [ "Cone< double >", "classCone.html", null ],
    [ "Cylinder< T >", "classCylinder.html", null ],
    [ "Cylinder< double >", "classCylinder.html", null ],
    [ "Json::Data", "classJson_1_1Data.html", null ],
    [ "Dataset", "classDataset.html", null ],
    [ "Datasets", "classDatasets.html", null ],
    [ "Editor", "classEditor.html", null ],
    [ "ExportFileFormatInterface", "classExportFileFormatInterface.html", [
      [ "ExportFileFormatCsv", "classExportFileFormatCsv.html", null ],
      [ "ExportFileFormatLas", "classExportFileFormatLas.html", null ]
    ] ],
    [ "ExportFileProperties", "classExportFileProperties.html", null ],
    [ "File", "classFile.html", null ],
    [ "ComputeTreeAttributesLeastSquaredRegression::FittingCircle", "classComputeTreeAttributesLeastSquaredRegression_1_1FittingCircle.html", null ],
    [ "LasFile::Format", "classLasFile_1_1Format.html", null ],
    [ "ComputeSegmentationNNAction::Group", "classComputeSegmentationNNAction_1_1Group.html", null ],
    [ "LasFile::Header", "structLasFile_1_1Header.html", null ],
    [ "RecordFile::Header", "structRecordFile_1_1Header.html", null ],
    [ "ImportFileInterface", "classImportFileInterface.html", [
      [ "ImportFilePlugin", "classImportFilePlugin.html", null ]
    ] ],
    [ "IndexFile", "classIndexFile.html", null ],
    [ "IndexFileBuilder", "classIndexFileBuilder.html", null ],
    [ "MyTestStruct::IO", "classMyTestStruct_1_1IO.html", null ],
    [ "Point::IO", "classPoint_1_1IO.html", null ],
    [ "IOUint32", "classIOUint32.html", null ],
    [ "Json", "classJson.html", null ],
    [ "PageManager::Key", "structPageManager_1_1Key.html", null ],
    [ "Query::Key", "structQuery_1_1Key.html", null ],
    [ "LasFile", "classLasFile.html", null ],
    [ "LasFile", "classLasFile_1_1cpp_1_1LasFile.html", null ],
    [ "LogMessage", "classLogMessage.html", null ],
    [ "LogThread", "classLogThread.html", null ],
    [ "LogThreadCallbackInterface", "classLogThreadCallbackInterface.html", [
      [ "LoggerFile", "classLoggerFile.html", null ],
      [ "LoggerStdout", "classLoggerStdout.html", null ],
      [ "MessageLogWindow", "classMessageLogWindow.html", null ]
    ] ],
    [ "Matrix4< T >", "classMatrix4.html", null ],
    [ "MainWindow::Menu", "classMainWindow_1_1Menu.html", null ],
    [ "MainWindow::MenuItem", "classMainWindow_1_1MenuItem.html", null ],
    [ "Mesh", "classMesh.html", null ],
    [ "ModifierInterface", "classModifierInterface.html", [
      [ "ComputeHeightMapPlugin", "classComputeHeightMapPlugin.html", null ]
    ] ],
    [ "MyTestStruct", "classMyTestStruct.html", null ],
    [ "IndexFile::Node", "structIndexFile_1_1Node.html", null ],
    [ "Null", "classNull.html", null ],
    [ "Numeric", "classNumeric.html", null ],
    [ "ArgumentParser::Option", "classArgumentParser_1_1Option.html", null ],
    [ "Page", "classPage.html", null ],
    [ "VectorFile< T, F >::Page", "classVectorFile_1_1Page.html", null ],
    [ "PageData", "classPageData.html", null ],
    [ "PageManager", "classPageManager.html", null ],
    [ "PluginInterface", "classPluginInterface.html", [
      [ "ComputeClassificationPlugin", "classComputeClassificationPlugin.html", null ],
      [ "ComputeDescriptorPlugin", "classComputeDescriptorPlugin.html", null ],
      [ "ComputeElevationPlugin", "classComputeElevationPlugin.html", null ],
      [ "ComputeHeightMapPlugin", "classComputeHeightMapPlugin.html", null ],
      [ "ComputeSegmentationNNPlugin", "classComputeSegmentationNNPlugin.html", null ],
      [ "ComputeTreeAttributesPlugin", "classComputeTreeAttributesPlugin.html", null ],
      [ "EditPlugin", "classEditPlugin.html", null ],
      [ "ExportFilePlugin", "classExportFilePlugin.html", null ],
      [ "FilterAreaPlugin", "classFilterAreaPlugin.html", null ],
      [ "FilterClassificationPlugin", "classFilterClassificationPlugin.html", null ],
      [ "FilterDescriptorPlugin", "classFilterDescriptorPlugin.html", null ],
      [ "FilterElevationPlugin", "classFilterElevationPlugin.html", null ],
      [ "FilterFilesPlugin", "classFilterFilesPlugin.html", null ],
      [ "FilterIntensityPlugin", "classFilterIntensityPlugin.html", null ],
      [ "FilterTreesPlugin", "classFilterTreesPlugin.html", null ],
      [ "HelpPlugin", "classHelpPlugin.html", null ],
      [ "ImportFilePlugin", "classImportFilePlugin.html", null ],
      [ "MessageLogPlugin", "classMessageLogPlugin.html", null ],
      [ "ProjectFilePlugin", "classProjectFilePlugin.html", null ],
      [ "SettingsUnitsPlugin", "classSettingsUnitsPlugin.html", null ],
      [ "SettingsViewPlugin", "classSettingsViewPlugin.html", null ],
      [ "TreeTablePlugin", "classTreeTablePlugin.html", null ],
      [ "ViewerPlugin", "classViewerPlugin.html", null ]
    ] ],
    [ "LasFile::Point", "structLasFile_1_1Point.html", null ],
    [ "Point", "classPoint.html", null ],
    [ "Points", "classPoints.html", null ],
    [ "ProgressActionInterface", "classProgressActionInterface.html", [
      [ "ComputeClassificationAction", "classComputeClassificationAction.html", null ],
      [ "ComputeDescriptorAction", "classComputeDescriptorAction.html", null ],
      [ "ComputeElevationAction", "classComputeElevationAction.html", null ],
      [ "ComputeSegmentationNNAction", "classComputeSegmentationNNAction.html", null ],
      [ "ComputeTreeAttributesAction", "classComputeTreeAttributesAction.html", null ],
      [ "ExportFileAction", "classExportFileAction.html", null ]
    ] ],
    [ "ProgressCounter", "classProgressCounter.html", null ],
    [ "ProjectFileInterface", "classProjectFileInterface.html", [
      [ "ProjectFilePlugin", "classProjectFilePlugin.html", null ]
    ] ],
    [ "QDialog", null, [
      [ "ComputeClassificationWindow", "classComputeClassificationWindow.html", null ],
      [ "ComputeDescriptorWindow", "classComputeDescriptorWindow.html", null ],
      [ "ComputeElevationWindow", "classComputeElevationWindow.html", null ],
      [ "ComputeHeightMapWindow", "classComputeHeightMapWindow.html", null ],
      [ "ComputeSegmentationNNWindow", "classComputeSegmentationNNWindow.html", null ],
      [ "ComputeTreeAttributesWindow", "classComputeTreeAttributesWindow.html", null ],
      [ "ExportFileDialog", "classExportFileDialog.html", null ],
      [ "ImportFileDialog", "classImportFileDialog.html", null ],
      [ "InfoDialog", "classInfoDialog.html", null ],
      [ "ProgressDialog", "classProgressDialog.html", null ],
      [ "TreeTableExportDialog", "classTreeTableExportDialog.html", null ],
      [ "TreeTableWindow", "classTreeTableWindow.html", null ]
    ] ],
    [ "QDockWidget", null, [
      [ "FilterAreaWindow", "classFilterAreaWindow.html", null ],
      [ "FilterClassificationWindow", "classFilterClassificationWindow.html", null ],
      [ "FilterDescriptorWindow", "classFilterDescriptorWindow.html", null ],
      [ "FilterElevationWindow", "classFilterElevationWindow.html", null ],
      [ "FilterFilesWindow", "classFilterFilesWindow.html", null ],
      [ "FilterIntensityWindow", "classFilterIntensityWindow.html", null ],
      [ "FilterTreesWindow", "classFilterTreesWindow.html", null ],
      [ "MessageLogWindow", "classMessageLogWindow.html", null ],
      [ "SettingsUnitsWindow", "classSettingsUnitsWindow.html", null ],
      [ "SettingsViewWindow", "classSettingsViewWindow.html", null ]
    ] ],
    [ "QIcon", null, [
      [ "ThemeIcon", "classThemeIcon.html", null ]
    ] ],
    [ "QMainWindow", null, [
      [ "MainWindow", "classMainWindow.html", null ]
    ] ],
    [ "QObject", null, [
      [ "ComputeClassificationPlugin", "classComputeClassificationPlugin.html", null ],
      [ "ComputeDescriptorPlugin", "classComputeDescriptorPlugin.html", null ],
      [ "ComputeElevationPlugin", "classComputeElevationPlugin.html", null ],
      [ "ComputeHeightMapPlugin", "classComputeHeightMapPlugin.html", null ],
      [ "ComputeSegmentationNNPlugin", "classComputeSegmentationNNPlugin.html", null ],
      [ "ComputeTreeAttributesPlugin", "classComputeTreeAttributesPlugin.html", null ],
      [ "EditPlugin", "classEditPlugin.html", null ],
      [ "ExportFilePlugin", "classExportFilePlugin.html", null ],
      [ "FilterAreaPlugin", "classFilterAreaPlugin.html", null ],
      [ "FilterClassificationPlugin", "classFilterClassificationPlugin.html", null ],
      [ "FilterDescriptorPlugin", "classFilterDescriptorPlugin.html", null ],
      [ "FilterElevationPlugin", "classFilterElevationPlugin.html", null ],
      [ "FilterFilesPlugin", "classFilterFilesPlugin.html", null ],
      [ "FilterIntensityPlugin", "classFilterIntensityPlugin.html", null ],
      [ "FilterTreesPlugin", "classFilterTreesPlugin.html", null ],
      [ "HelpPlugin", "classHelpPlugin.html", null ],
      [ "ImportFilePlugin", "classImportFilePlugin.html", null ],
      [ "MessageLogPlugin", "classMessageLogPlugin.html", null ],
      [ "ProjectFilePlugin", "classProjectFilePlugin.html", null ],
      [ "SettingsUnitsPlugin", "classSettingsUnitsPlugin.html", null ],
      [ "SettingsViewPlugin", "classSettingsViewPlugin.html", null ],
      [ "TreeTablePlugin", "classTreeTablePlugin.html", null ],
      [ "ViewerPlugin", "classViewerPlugin.html", null ]
    ] ],
    [ "QOpenGLFunctions", null, [
      [ "ViewerOpenGLViewport", "classViewerOpenGLViewport.html", null ]
    ] ],
    [ "QOpenGLWidget", null, [
      [ "ViewerOpenGLViewport", "classViewerOpenGLViewport.html", null ]
    ] ],
    [ "Query", "classQuery.html", null ],
    [ "QueryFilterSet", "classQueryFilterSet.html", null ],
    [ "QueryWhere", "classQueryWhere.html", null ],
    [ "QWidget", null, [
      [ "ColorSwitchWidget", "classColorSwitchWidget.html", null ],
      [ "ComputeClassificationWidget", "classComputeClassificationWidget.html", null ],
      [ "ComputeDescriptorWidget", "classComputeDescriptorWidget.html", null ],
      [ "ComputeElevationWidget", "classComputeElevationWidget.html", null ],
      [ "ComputeHeightMapWidget", "classComputeHeightMapWidget.html", null ],
      [ "ComputeSegmentationNNWidget", "classComputeSegmentationNNWidget.html", null ],
      [ "ComputeTreeAttributesWidget", "classComputeTreeAttributesWidget.html", null ],
      [ "DoubleRangeSliderWidget", "classDoubleRangeSliderWidget.html", null ],
      [ "DoubleSliderWidget", "classDoubleSliderWidget.html", null ],
      [ "FilterAreaBoxWidget", "classFilterAreaBoxWidget.html", null ],
      [ "FilterClassificationWidget", "classFilterClassificationWidget.html", null ],
      [ "FilterDescriptorWidget", "classFilterDescriptorWidget.html", null ],
      [ "FilterElevationWidget", "classFilterElevationWidget.html", null ],
      [ "FilterFilesWidget", "classFilterFilesWidget.html", null ],
      [ "FilterIntensityWidget", "classFilterIntensityWidget.html", null ],
      [ "FilterTreesTreeWidget", "classFilterTreesTreeWidget.html", null ],
      [ "FilterTreesWidget", "classFilterTreesWidget.html", null ],
      [ "RangeSliderWidget", "classRangeSliderWidget.html", null ],
      [ "SettingsUnitsWidget", "classSettingsUnitsWidget.html", null ],
      [ "SettingsViewWidget", "classSettingsViewWidget.html", null ],
      [ "ShowDetailsWidget", "classShowDetailsWidget.html", null ],
      [ "SliderWidget", "classSliderWidget.html", null ],
      [ "ToolTabWidget", "classToolTabWidget.html", null ],
      [ "TreeTableWidget", "classTreeTableWidget.html", null ],
      [ "ViewerViewports", "classViewerViewports.html", null ]
    ] ],
    [ "Dataset::Range", "classDataset_1_1Range.html", null ],
    [ "RecordFile", "classRecordFile.html", null ],
    [ "Region", "classRegion.html", null ],
    [ "Segment", "classSegment.html", null ],
    [ "Segments", "classSegments.html", null ],
    [ "IndexFile::Selection", "structIndexFile_1_1Selection.html", null ],
    [ "IndexFile::SelectionTile", "structIndexFile_1_1SelectionTile.html", null ],
    [ "Settings", "classSettings.html", null ],
    [ "SettingsImport", "classSettingsImport.html", null ],
    [ "SettingsUnits", "classSettingsUnits.html", null ],
    [ "SettingsView", "classSettingsView.html", null ],
    [ "Sphere< T >", "classSphere.html", null ],
    [ "Sphere< double >", "classSphere.html", null ],
    [ "Test", "classTest.html", null ],
    [ "Test::TestCase", "classTest_1_1TestCase.html", null ],
    [ "TestPoint3d", "classTestPoint3d.html", null ],
    [ "TestPoint3f", "classTestPoint3f.html", null ],
    [ "ThreadCallbackInterface", "classThreadCallbackInterface.html", [
      [ "MainWindow", "classMainWindow.html", null ]
    ] ],
    [ "ThreadLoop", "classThreadLoop.html", [
      [ "RenderThread", "classRenderThread.html", null ]
    ] ],
    [ "Time", "classTime.html", null ],
    [ "TreeAttributes", "classTreeAttributes.html", null ],
    [ "TreeTableExportInterface", "classTreeTableExportInterface.html", [
      [ "TreeTableExportCsv", "classTreeTableExportCsv.html", null ]
    ] ],
    [ "TreeTableExportProperties", "classTreeTableExportProperties.html", null ],
    [ "VectorFile< T, F >", "classVectorFile.html", null ],
    [ "VectorFile< Point, Point::IO >", "classVectorFile.html", null ],
    [ "ViewerAabb", "classViewerAabb.html", null ],
    [ "ViewerCamera", "classViewerCamera.html", null ],
    [ "ViewerInterface", "classViewerInterface.html", [
      [ "ViewerPlugin", "classViewerPlugin.html", null ]
    ] ],
    [ "ViewerOpenGL", "classViewerOpenGL.html", null ],
    [ "Viewports", "classViewports.html", null ]
];